#!/usr/bin/env python3
"""Delta net at decode: two columns a warp, and the records accumulate instead of the state being written back every token.

Two columns a warp (STRIX_GDN_COLS=1: one): the decode kernels had one 512-byte column of state in flight a warp, and 8 conversations' 24 MB a layer were read at ~117 GB/s (tmp/dec040/wb_probe2.hip: 207 -> 123 us). Records accumulate (STRIX_GDN_ACC=W, default 8; 0 or 1: as before): a short batch - a decode step, also without MTP now, or a verify - appends its records (delta, key, gate: 33 KB a token) after the pending ones and leaves the state row as it is while the set holds W; only then is the replayed state written back. Writing 3 MB a conversation a layer every token cost 5.9 ms of an 83.5 ms step at 8 conversations (in-run A/B with the write skipped); the replay reads its records in blocks of 6 (one wait a block). Each column is summed by the same lanes in the same order and the replay is the plain net's fmaf chain, so the bits are the same (tmp/dec040/gdn_cols_test.cpp: 78 cases, one column = two; the probes = 0.3.3). The host replay (state saves, seq_cp) gets an AVX2 FMA path, self-checked against fmaf at first use: the CRT's fmaf took 262 ms for 8 records of a conversation, 14 ms vectorised. A memory without recurrent layers (the MTP draft's) records nothing.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 59 hunks across 4 file(s).

Usage: python patches/apply_gdn_records_041.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'rec_append'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "gated_delta_net.cu"): [
        ('''template <int S_v, bool KDA, bool keep_rs_t>
''',
         '''// strixllama: COLS columns a warp. With one, a warp had one 512-byte column of state in flight, and at decode (a token a
// sequence) that is all a warp waits for: 8 conversations' 24 MB were read at ~117 GB/s. With two, both columns' loads
// are in flight together (the read ~0.6 of the time). Each column is summed by the same lanes in the same order.
template <int S_v, bool KDA, bool keep_rs_t, int COLS = 1>
'''),
        ('''    // each warp owns one column, using warp-level primitives to reduce across rows
''',
         '''    // each warp owns COLS columns, using warp-level primitives to reduce across rows
'''),
        ('''    const int      lane     = threadIdx.x;
    const int      col      = blockIdx.z * blockDim.y + threadIdx.y;

''',
         '''    const int      lane     = threadIdx.x;
    const int      col0     = (blockIdx.z * blockDim.y + threadIdx.y) * COLS;

'''),
        ('''    curr_state += state_in_offset + col * S_v;
''',
         '''    curr_state += state_in_offset + col0 * S_v;
'''),
        ('''    float         s_shard[rows_per_lane];
''',
         '''    float         s_shard[COLS][rows_per_lane];
'''),
        ('''    for (int r = 0; r < rows_per_lane; r++) {
        const int i = r * warp_size + lane;
        s_shard[r]  = curr_state[i];
''',
         '''    for (int c = 0; c < COLS; c++) {
#pragma unroll
        for (int r = 0; r < rows_per_lane; r++) {
            const int i   = r * warp_size + lane;
            s_shard[c][r] = curr_state[c * S_v + i];
        }
'''),
        ('''            // kv[col] = (S^T @ k)[col] = sum_i S[i][col] * k[i]
            float kv_shard = 0.0f;
''',
         ''''''),
        ('''            for (int r = 0; r < rows_per_lane; r++) {
                kv_shard += s_shard[r] * k_reg[r];
            }
            float kv_col = warp_reduce_sum<warp_size>(kv_shard);
''',
         '''            for (int c = 0; c < COLS; c++) {
                const int col = col0 + c;
'''),
        ('''            // delta[col] = (v[col] - g * kv[col]) * beta
            float delta_col = (v_t[col] - g_val * kv_col) * beta_val;
''',
         '''                // kv[col] = (S^T @ k)[col] = sum_i S[i][col] * k[i]
                float kv_shard = 0.0f;
#pragma unroll
                for (int r = 0; r < rows_per_lane; r++) {
                    kv_shard += s_shard[c][r] * k_reg[r];
                }
                float kv_col = warp_reduce_sum<warp_size>(kv_shard);
'''),
        ('''            // fused: S[i][col] = g * S[i][col] + k[i] * delta[col]
            // attn[col] = (S^T @ q)[col] = sum_i S[i][col] * q[i]
            float attn_partial = 0.0f;
''',
         '''                // delta[col] = (v[col] - g * kv[col]) * beta
                float delta_col = (v_t[col] - g_val * kv_col) * beta_val;

                // fused: S[i][col] = g * S[i][col] + k[i] * delta[col]
                // attn[col] = (S^T @ q)[col] = sum_i S[i][col] * q[i]
                float attn_partial = 0.0f;
'''),
        ('''            for (int r = 0; r < rows_per_lane; r++) {
                // strixllama: the fmaf the compiler made of g * s + k * delta, spelled out: the deferred-rollback
                // kernels' replay must give these bits
                s_shard[r]  = fmaf(g_val, s_shard[r], k_reg[r] * delta_col);
                attn_partial += s_shard[r] * q_reg[r];
            }
''',
         '''                for (int r = 0; r < rows_per_lane; r++) {
                    // strixllama: the fmaf the compiler made of g * s + k * delta, spelled out: the deferred-rollback
                    // kernels' replay must give these bits
                    s_shard[c][r]  = fmaf(g_val, s_shard[c][r], k_reg[r] * delta_col);
                    attn_partial += s_shard[c][r] * q_reg[r];
                }
'''),
        ('''            float attn_col = warp_reduce_sum<warp_size>(attn_partial);

            if (lane == 0) {
                attn_data[col] = attn_col * scale;
            }
        } else {
            // kv[col] = sum_i g[i] * S[i][col] * k[i]
            float kv_shard = 0.0f;
''',
         '''                float attn_col = warp_reduce_sum<warp_size>(attn_partial);

                if (lane == 0) {
                    attn_data[col] = attn_col * scale;
                }
            }
        } else {
'''),
        ('''            for (int r = 0; r < rows_per_lane; r++) {
                const int i = r * warp_size + lane;
                kv_shard += expf(g_t[i]) * s_shard[r] * k_reg[r];
            }
''',
         '''            for (int c = 0; c < COLS; c++) {
                const int col = col0 + c;
'''),
        ('''            float kv_col = warp_reduce_sum<warp_size>(kv_shard);

            // delta[col] = (v[col] - kv[col]) * beta
            float delta_col = (v_t[col] - kv_col) * beta_val;
''',
         '''                // kv[col] = sum_i g[i] * S[i][col] * k[i]
                float kv_shard = 0.0f;
#pragma unroll
                for (int r = 0; r < rows_per_lane; r++) {
                    const int i = r * warp_size + lane;
                    kv_shard += expf(g_t[i]) * s_shard[c][r] * k_reg[r];
                }

                float kv_col = warp_reduce_sum<warp_size>(kv_shard);
'''),
        ('''            // fused: S[i][col] = g[i] * S[i][col] + k[i] * delta[col]
            // attn[col] = (S^T @ q)[col] = sum_i S[i][col] * q[i]
            float attn_partial = 0.0f;
''',
         '''                // delta[col] = (v[col] - kv[col]) * beta
                float delta_col = (v_t[col] - kv_col) * beta_val;

                // fused: S[i][col] = g[i] * S[i][col] + k[i] * delta[col]
                // attn[col] = (S^T @ q)[col] = sum_i S[i][col] * q[i]
                float attn_partial = 0.0f;
'''),
        ('''            for (int r = 0; r < rows_per_lane; r++) {
                const int i = r * warp_size + lane;
                s_shard[r]  = expf(g_t[i]) * s_shard[r] + k_reg[r] * delta_col;
                attn_partial += s_shard[r] * q_reg[r];
            }
''',
         '''                for (int r = 0; r < rows_per_lane; r++) {
                    const int i = r * warp_size + lane;
                    s_shard[c][r]  = expf(g_t[i]) * s_shard[c][r] + k_reg[r] * delta_col;
                    attn_partial += s_shard[c][r] * q_reg[r];
                }
'''),
        ('''            }

            float attn_col = warp_reduce_sum<warp_size>(attn_partial);

            if (lane == 0) {
                attn_data[col] = attn_col * scale;
            }
        }
''',
         '''            }

                float attn_col = warp_reduce_sum<warp_size>(attn_partial);

                if (lane == 0) {
                    attn_data[col] = attn_col * scale;
                }
            }
        }
'''),
        ('''                for (int r = 0; r < rows_per_lane; r++) {
                    const int i = r * warp_size + lane;
                    curr_state[col * S_v + i] = s_shard[r];
''',
         '''                for (int c = 0; c < COLS; c++) {
#pragma unroll
                    for (int r = 0; r < rows_per_lane; r++) {
                        const int i = r * warp_size + lane;
                        curr_state[(col0 + c) * S_v + i] = s_shard[c][r];
                    }
'''),
        ('''        for (int r = 0; r < rows_per_lane; r++) {
            const int i          = r * warp_size + lane;
            state[col * S_v + i] = s_shard[r];
''',
         '''        for (int c = 0; c < COLS; c++) {
#pragma unroll
            for (int r = 0; r < rows_per_lane; r++) {
                const int i = r * warp_size + lane;
                state[(col0 + c) * S_v + i] = s_shard[c][r];
            }
'''),
        ('''        case 128: {
            ggml_cuda_kernel_launch(gated_delta_net_cuda<128, KDA, keep_rs_t>, launch_params,
''',
         '''        case 128: {
            // strixllama: two columns a warp for batches of a few tokens a sequence (decode, verify); longer ones keep
            // one, as they spend their time in the per-token chain. STRIX_GDN_COLS=1: one column always
            static const int gdn_cols = getenv("STRIX_GDN_COLS") ? (strcmp(getenv("STRIX_GDN_COLS"), "ab") ? atoi(getenv("STRIX_GDN_COLS")) : -1) : 2;
            if constexpr (!KDA) {
                // STRIX_GDN_COLS=ab: one column on side A of the in-run A/B (STRIX_AB), two on B
                if ((gdn_cols == 2 || (gdn_cols < 0 && ggml_cuda_strix_ab())) && warp_size == 32 && n_tokens <= 16) {
                    static unsigned hits = 0;
                    if (hits++ == 0) fprintf(stderr, "FORK_GDN_COLS2 seqs=%ld tokens=%ld keep=%d\\n", n_seqs, n_tokens, int(keep_rs_t));
                    const dim3 grid2(H, n_seqs, S_v / (num_warps * 2));
                    const ggml_cuda_kernel_launch_params params2(grid2, block_dims, 0, stream);
                    ggml_cuda_kernel_launch(gated_delta_net_cuda<128, KDA, keep_rs_t, 2>, params2,
                        q_d, k_d, v_d, g_d, b_d, s_d, dst_d, state_d, H,
                        n_tokens, n_seqs, sq1, sq2, sq3, sv1, sv2, sv3,
                        sb1, sb2, sb3, neqk1_magic, rq3_magic, scale, state_slot_stride, K, state_rows);
                    break;
                }
            }
            ggml_cuda_kernel_launch(gated_delta_net_cuda<128, KDA, keep_rs_t>, launch_params,
'''),
        ('''template <int S_v, bool replay_only>
''',
         '''// COLS columns a warp, as the plain kernel.
template <int S_v, bool replay_only, int COLS = 1>
'''),
        ('''    const int      lane     = threadIdx.x;
    const int      col      = blockIdx.z * blockDim.y + threadIdx.y;
    const int64_t  kh       = h_idx % H_k;
''',
         '''    const int      lane     = threadIdx.x;
    const int      col0     = (blockIdx.z * blockDim.y + threadIdx.y) * COLS;
    const int64_t  kh       = h_idx % H_k;
'''),
        ('''    const float * s_in  = state_all + row_in  * D + h_idx * S_v * S_v + col * S_v;
    float *       s_out = state_all + row_out * D + h_idx * S_v * S_v + col * S_v;
''',
         '''    const float * s_in  = state_all + row_in  * D + h_idx * S_v * S_v + col0 * S_v;
    float *       s_out = state_all + (row_out >= 0 ? row_out : row_in) * D + h_idx * S_v * S_v + col0 * S_v;
'''),
        ('''    float s_shard[rows_per_lane];
''',
         '''    float s_shard[COLS][rows_per_lane];
'''),
        ('''    for (int r = 0; r < rows_per_lane; r++) {
        s_shard[r] = s_in[r * warp_size + lane];
''',
         '''    for (int c = 0; c < COLS; c++) {
#pragma unroll
        for (int r = 0; r < rows_per_lane; r++) {
            s_shard[c][r] = s_in[c * S_v + r * warp_size + lane];
        }
'''),
        ('''    const float * rd = rec + (int64_t) inf[3] * R * rec_floats;
    for (int j = 0; j < n_rep; j++) {
        const float * rj = rd + j * rec_floats;
        const float   d  = rj[h_idx * S_v + col];
        const float   gv = rj[H * S_v + H_k * S_v + h_idx];
        const float * kk = rj + H * S_v + kh * S_v;
''',
         '''    // records by index: inf[3] the first replayed, inf[4] the first this batch writes (R: records a set)
    GGML_UNUSED(R);
    const float * rd = rec + (int64_t) inf[3] * rec_floats;
    // in blocks of RB records: a block's loads (gate, deltas, key) issued together, then its updates in record order -
    // records accumulate (up to STRIX_GDN_ACC a set), and one at a time each waited for its loads
    constexpr int RB = 6;
    for (int j0 = 0; j0 < n_rep; j0 += RB) {
        float gvb[RB], db[RB][COLS], kb[RB][rows_per_lane];
'''),
        ('''        for (int r = 0; r < rows_per_lane; r++) {
            s_shard[r] = fmaf(gv, s_shard[r], kk[r * warp_size + lane] * d);
''',
         '''        for (int b = 0; b < RB; b++) {
            if (j0 + b < n_rep) {
                const float * rj = rd + (int64_t) (j0 + b) * rec_floats;
                gvb[b] = rj[H * S_v + H_k * S_v + h_idx];
#pragma unroll
                for (int c = 0; c < COLS; c++) {
                    db[b][c] = rj[h_idx * S_v + col0 + c];
                }
#pragma unroll
                for (int r = 0; r < rows_per_lane; r++) {
                    kb[b][r] = rj[H * S_v + kh * S_v + r * warp_size + lane];
                }
            }
        }
#pragma unroll
        for (int b = 0; b < RB; b++) {
            if (j0 + b < n_rep) {
#pragma unroll
                for (int c = 0; c < COLS; c++) {
#pragma unroll
                    for (int r = 0; r < rows_per_lane; r++) {
                        s_shard[c][r] = fmaf(gvb[b], s_shard[c][r], kb[b][r] * db[b][c]);
                    }
                }
            }
'''),
        ('''    if (n_rep > 0 || row_in != row_out) {
''',
         '''    // row written -1: the batch's records follow the replayed ones and the row stays as it is
    if (row_out >= 0 && (n_rep > 0 || row_in != row_out)) {
'''),
        ('''        for (int r = 0; r < rows_per_lane; r++) {
            s_out[r * warp_size + lane] = s_shard[r];
''',
         '''        for (int c = 0; c < COLS; c++) {
#pragma unroll
            for (int r = 0; r < rows_per_lane; r++) {
                s_out[c * S_v + r * warp_size + lane] = s_shard[c][r];
            }
'''),
        ('''        float *        wr        = rec + (int64_t) inf[4] * R * rec_floats;
''',
         '''        float *        wr        = rec + (int64_t) inf[4] * rec_floats;
'''),
        ('''            float kv_shard = 0.0f;
#pragma unroll
            for (int r = 0; r < rows_per_lane; r++) {
                kv_shard += s_shard[r] * k_reg[r];
            }
            const float kv_col    = warp_reduce_sum<warp_size>(kv_shard);
            const float delta_col = (v_t[col] - g_val * kv_col) * beta_val;
''',
         '''            // the record: the delta by each column's warp, the key and the gate once per head
            float * rt = wr + t * rec_floats;
#pragma unroll
            for (int c = 0; c < COLS; c++) {
                const int col = col0 + c;
'''),
        ('''            float attn_partial = 0.0f;
#pragma unroll
            for (int r = 0; r < rows_per_lane; r++) {
                s_shard[r]    = fmaf(g_val, s_shard[r], k_reg[r] * delta_col);
                attn_partial += s_shard[r] * q_reg[r];
            }
            const float attn_col = warp_reduce_sum<warp_size>(attn_partial);
            if (lane == 0) {
                attn_data[col] = attn_col * scale;
''',
         '''                float kv_shard = 0.0f;
#pragma unroll
                for (int r = 0; r < rows_per_lane; r++) {
                    kv_shard += s_shard[c][r] * k_reg[r];
                }
                const float kv_col    = warp_reduce_sum<warp_size>(kv_shard);
                const float delta_col = (v_t[col] - g_val * kv_col) * beta_val;

                float attn_partial = 0.0f;
#pragma unroll
                for (int r = 0; r < rows_per_lane; r++) {
                    s_shard[c][r] = fmaf(g_val, s_shard[c][r], k_reg[r] * delta_col);
                    attn_partial += s_shard[c][r] * q_reg[r];
                }
                const float attn_col = warp_reduce_sum<warp_size>(attn_partial);
                if (lane == 0) {
                    attn_data[col]        = attn_col * scale;
                    rt[h_idx * S_v + col] = delta_col;
                }
'''),
        ('''
            // the record: the delta by each column's warp, the key and the gate once per head
            float * rt = wr + t * rec_floats;
            if (lane == 0) {
                rt[h_idx * S_v + col] = delta_col;
            }
''',
         ''''''),
        ('''    const dim3 grid(H, n_seqs, S_v / num_warps);
''',
         '''    // strixllama: two columns a warp (STRIX_GDN_COLS=1: one), as the plain kernel for decode batches
    static const int gdn_cols = getenv("STRIX_GDN_COLS") ? (strcmp(getenv("STRIX_GDN_COLS"), "ab") ? atoi(getenv("STRIX_GDN_COLS")) : -1) : 2;
    const bool two = (gdn_cols == 2 || (gdn_cols < 0 && ggml_cuda_strix_ab())) && warp_size == 32;
    const dim3 grid(H, n_seqs, S_v / num_warps / (two ? 2 : 1));
'''),
        ('''        ggml_cuda_kernel_launch(gated_delta_net_lazy_cuda<128, true>, params,
''',
         '''        ggml_cuda_kernel_launch(two ? gated_delta_net_lazy_cuda<128, true, 2> : gated_delta_net_lazy_cuda<128, true, 1>, params,
'''),
        ('''    ggml_cuda_kernel_launch(gated_delta_net_lazy_cuda<128, false>, params,
''',
         '''    ggml_cuda_kernel_launch(two ? gated_delta_net_lazy_cuda<128, false, 2> : gated_delta_net_lazy_cuda<128, false, 1>, params,
'''),
    ],
    os.path.join(tree, "src", "llama-memory-recurrent.h"): [
        ('''    // the records its rollback kept. Per recurrent layer a record buffer [rec_floats, 1 + n_rs_seq, 2 * size] (two sets
    // per cell: the next batch reads one and writes the other), and per cell how many records its last batch left - 0
    // means its rows hold the state as the plain net leaves them (slot rs_idx of the cell) - and which set holds them.
''',
         '''    // the records its rollback kept. Per recurrent layer a record buffer [rec_floats, rec_cap, 2 * size] (two sets per
    // cell), and per cell how many records are pending - 0 means its rows hold the state as the plain net leaves them
    // (slot rs_idx of the cell) - which set holds them, and how many of them its last batch wrote (what a rollback may
    // take back). While its set has room a short batch appends its records after the pending ones and leaves the row
    // as it is (rec_append, STRIX_GDN_ACC=W: W records a set, default 8; also without MTP, where decode batches then
    // record); else it writes the replayed state back and starts the other set. The row is written once per ~W tokens.
'''),
        ('''    uint32_t rec_floats = 0;
    int32_t  gdn_s  = 0;      // S_v = S_k
''',
         '''    uint32_t rec_floats = 0;
    uint32_t rec_cap    = 0;  // records a set holds
    bool     rec_append = false;
    int32_t  gdn_s  = 0;      // S_v = S_k
'''),
        ('''    std::vector<uint8_t>       rec_set;

''',
         '''    std::vector<uint8_t>       rec_set;
    std::vector<uint32_t>      rec_last;

'''),
    ],
    os.path.join(tree, "src", "llama-memory-recurrent.cpp"): [
        ('''#include "llama-memory-recurrent.h"

''',
         '''#include "llama-memory-recurrent.h"

#if defined(__x86_64__) || defined(_M_X64)
#include <immintrin.h>
#if defined(_WIN32)
#include <intrin.h>
#else
#include <cpuid.h>
#endif
#endif

'''),
        ('''    // [S, S, H_v] per layer, the key [S, H_k]) and only where drafts are rolled back. STRIX_GDN_LAZY=0 turns it off
''',
         '''    // [S, S, H_v] per layer, the key [S, H_k]): where drafts are rolled back, and with STRIX_GDN_ACC=W > 1 (default 8)
    // also without them, the records then accumulating to W a set. STRIX_GDN_LAZY=0 turns it off
'''),
        ('''        const char *  e   = getenv("STRIX_GDN_LAZY");
        const int32_t S   = (int32_t) hparams.ssm_d_state;
''',
         '''        const char *  e   = getenv("STRIX_GDN_LAZY");
        const char *  ea  = getenv("STRIX_GDN_ACC");
        const uint32_t acc = ea ? (uint32_t) std::max(0, atoi(ea)) : 8;
        const int32_t S   = (int32_t) hparams.ssm_d_state;
'''),
        ('''        if ((!e || atoi(e) != 0) && n_rs_seq > 0 && model.arch == LLM_ARCH_QWEN4EXP && S > 0 && H_v > 0 && H_k > 0 &&
                hparams.n_embd_s() == (uint32_t) (S * S * H_v)) {
''',
         '''        if ((!e || atoi(e) != 0) && (n_rs_seq > 0 || acc > 1) && model.arch == LLM_ARCH_QWEN4EXP && S > 0 && H_v > 0 &&
                H_k > 0 && hparams.n_embd_s() == (uint32_t) (S * S * H_v)) {
'''),
        ('''            rec_floats = (uint32_t) (H_v * S + H_k * S + H_v);
        }
''',
         '''            rec_floats = (uint32_t) (H_v * S + H_k * S + H_v);
            rec_append = acc > 1;
            rec_cap    = std::max(1 + n_rs_seq, rec_append ? acc : 0u);
        }
'''),
        ('''    rec_set.assign(mem_size, 0);

''',
         '''    rec_set.assign(mem_size, 0);
    rec_last.assign(mem_size, 0);

'''),
        ('''            ggml_tensor * rc = ggml_new_tensor_3d(ctx, GGML_TYPE_F32, rec_floats, 1 + n_rs_seq, 2 * mem_size);
''',
         '''            ggml_tensor * rc = ggml_new_tensor_3d(ctx, GGML_TYPE_F32, rec_floats, rec_cap, 2 * mem_size);
'''),
        ('''            p_l[i] = p;
        }
    }

''',
         '''            p_l[i] = p;
        }
    }

    // strixllama: a memory without recurrent layers (the MTP draft's) records nothing: its graphs never read the records
    if (n_layer_recr == 0) {
        rec_floats = 0;
        rec_append = false;
    }

'''),
        ('''                // strixllama: a cell with records (deferred rollback) goes back at most as far as its last batch;
                // after a plain batch, as far as the snapshots that batch wrote
                const uint32_t lim = rec_n[tail_id] > 0 ? std::min(rec_n[tail_id], n_rs_seq) : n_rs_seq;
''',
         '''                // strixllama: a cell with records (deferred rollback) goes back at most as far as its last batch
                // (the records before it may be pending too); after a plain batch, as far as its snapshots
                const uint32_t lim = rec_n[tail_id] > 0 ? std::min(rec_last[tail_id], n_rs_seq) : n_rs_seq;
'''),
        ('''
void llama_memory_recurrent::rec_materialize(uint32_t cell, int32_t il, std::vector<float> & out) const {
''',
         '''
// m[i] = fmaf(g, m[i], k[i] * d) over a column, as the kernels do: the multiply rounded, then one fused multiply-add
static void rec_replay_column(float * m, const float * k, float g, float d, int64_t n) {
    for (int64_t i = 0; i < n; ++i) {
        m[i] = fmaf(g, m[i], k[i] * d);
    }
}

#if defined(__x86_64__) || defined(_M_X64)
// AVX2 and FMA, and the OS saving the YMM registers (no __builtin_cpu_supports: its __cpu_model is not linked here)
__attribute__((target("xsave"))) static bool rec_have_fma() {
    unsigned r[4] = { 0, 0, 0, 0 };
#if defined(_WIN32)
    __cpuid((int *) r, 1);
#else
    __get_cpuid(1, &r[0], &r[1], &r[2], &r[3]);
#endif
    if (!((r[2] >> 12) & 1) || !((r[2] >> 27) & 1) || !((r[2] >> 28) & 1) || (_xgetbv(0) & 6) != 6) {
        return false;
    }
#if defined(_WIN32)
    __cpuidex((int *) r, 7, 0);
#else
    __get_cpuid_count(7, 0, &r[0], &r[1], &r[2], &r[3]);
#endif
    return (r[1] >> 5) & 1;
}

// the same with AVX2 / FMA (llama.dll is built without -mfma, and the CRT's fmaf costs ~1.2 ns): the same bits
__attribute__((target("avx2,fma"))) static void rec_replay_column_fma(float * m, const float * k, float g, float d, int64_t n) {
    const __m256 g8 = _mm256_set1_ps(g);
    const __m256 d8 = _mm256_set1_ps(d);
    int64_t i = 0;
    for (; i + 8 <= n; i += 8) {
        const __m256 kd = _mm256_mul_ps(_mm256_loadu_ps(k + i), d8);
        _mm256_storeu_ps(m + i, _mm256_fmadd_ps(g8, _mm256_loadu_ps(m + i), kd));
    }
    for (; i < n; ++i) {
        m[i] = fmaf(g, m[i], k[i] * d);
    }
}
#endif

#if defined(__x86_64__) || defined(_M_X64)
// the vector path only where it gives the CRT's bits: a column of values around 1, tiny, denormal and huge, replayed by both
static bool rec_fma_same() {
    const int64_t n = 1024;
    std::vector<float> a(n), b(n), k(n);
    uint32_t x = 12345;
    for (int64_t i = 0; i < n; ++i) {
        x = x * 1664525u + 1013904223u;
        const float u = (float) (x >> 8) / 16777216.0f - 0.5f;
        const float scale = (i % 4 == 0) ? 1e-39f : (i % 4 == 1) ? 1e-20f : (i % 4 == 2) ? 1.0f : 1e20f;
        a[i] = b[i] = u * scale;
        k[i] = (float) ((x >> 3) % 2001) / 1000.0f - 1.0f;
    }
    for (int rep = 0; rep < 4; ++rep) {
        const float g = 0.75f + 0.0625f * rep, d = rep % 2 ? 3.0e-3f : -1.7e-38f;
        rec_replay_column(a.data(), k.data(), g, d, n);
        rec_replay_column_fma(b.data(), k.data(), g, d, n);
    }
    return memcmp(a.data(), b.data(), n * sizeof(float)) == 0;
}
#endif

void llama_memory_recurrent::rec_materialize(uint32_t cell, int32_t il, std::vector<float> & out) const {
'''),
        ('''    const size_t R = 1 + n_rs_seq;
''',
         '''    const size_t R = rec_cap;
'''),
        ('''                            rec.size() * sizeof(float));
    // as gated_delta_net_lazy_cuda: s = fmaf(g, s, k * delta), the state stored with a column's rows contiguous
''',
         '''                            rec.size() * sizeof(float));
    auto replay = rec_replay_column;
#if defined(__x86_64__) || defined(_M_X64)
    static const bool fma = []() {
        const bool on = rec_have_fma() && rec_fma_same();
        // on stderr: the server's log keeps none of the library's messages
        fprintf(stderr, "rec_materialize: the host replay of delta-net records: %s\\n", on ? "AVX2 FMA" : "fmaf");
        return on;
    }();
    if (fma) {
        replay = rec_replay_column_fma;
    }
#endif
    // as gated_delta_net_lazy_cuda: s = fmaf(g, s, k * delta), the state stored with a column's rows contiguous
'''),
        ('''                const float d = rj[h * S + c];
                float *     m = out.data() + (h * S + c) * S;
                for (int64_t i = 0; i < S; ++i) {
                    m[i] = fmaf(gv, m[i], kk[i] * d);
                }
''',
         '''                replay(out.data() + (h * S + c) * S, kk, gv, rj[h * S + c], S);
'''),
        ('''
void llama_memory_recurrent_context::lazy_info(int32_t * info, int n, bool lazy, uint32_t n_seq_tokens) const {
''',
         '''
// strixllama DEV: STRIX_GDN_ACC_AB=1 - records accumulate only on side B of the HIP backend's in-run A/B (STRIX_AB); on
// side A every short batch writes its state back, as without accumulation
static bool rec_append_now() {
    static const bool ab = getenv("STRIX_GDN_ACC_AB") != nullptr;
    if (!ab) {
        return true;
    }
    static int (*side)() = []() -> int (*)() {
        for (size_t i = 0; i < ggml_backend_reg_count(); ++i) {
            if (void * f = ggml_backend_reg_get_proc_address(ggml_backend_reg_get(i), "ggml_backend_cuda_strix_ab")) {
                return (int (*)()) f;
            }
        }
        return nullptr;
    }();
    return side != nullptr && side() != 0;
}

void llama_memory_recurrent_context::lazy_info(int32_t * info, int n, bool lazy, uint32_t n_seq_tokens) const {
'''),
        ('''    std::vector<uint32_t> replayed;                 // a source cell is replayed once, whoever gathers it
    for (int i = 0; i < n; ++i) {
''',
         '''    std::vector<uint32_t> replayed;                 // a source cell is replayed once, whoever gathers it
    std::vector<uint32_t> appended(n, UINT32_MAX);  // lazy: the pending records a sequence appends to, if it does
    const uint32_t        R = mem->rec_cap;         // records are indexed (2 * cell + set) * R + j
    const bool            append_ok = mem->rec_append && rec_append_now();
    for (int i = 0; i < n; ++i) {
'''),
        ('''            // own cell (the graph checked): the base with its records, or the rolled-back snapshot of the plain net
            inf[0] = rec ? (int32_t) c : (int32_t) (rho * mem->size + c);
            inf[1] = (int32_t) c;
''',
         '''            // own cell (the graph checked): the base with its records, or the rolled-back snapshot of the plain net.
            // While the set has room the batch's records follow the pending ones and the row stays as it is (row
            // written -1); else the replayed state goes back to the row and the records start the other set
            const uint32_t row_in = rec ? c : rho * mem->size + c;
            const uint32_t set    = mem->rec_set[c];
            const bool     app    = append_ok && row_in == c && n_rep + n_seq_tokens <= R;
            inf[0] = (int32_t) row_in;
            inf[1] = app ? -1 : (int32_t) c;
'''),
        ('''            inf[3] = (int32_t) (2 * c + mem->rec_set[c]);
            inf[4] = (int32_t) (2 * c + (mem->rec_set[c] ^ 1));
''',
         '''            inf[3] = (int32_t) ((2 * c + set) * R);
            inf[4] = (int32_t) (app ? (2 * c + set) * R + n_rep : (2 * c + (set ^ 1)) * R);
            if (app) {
                appended[i] = n_rep;
            }
'''),
        ('''            inf[3] = (int32_t) (2 * src + mem->rec_set[src]);
''',
         '''            inf[3] = (int32_t) ((2 * src + mem->rec_set[src]) * R);
'''),
        ('''            mem->rec_set[c] ^= 1;
            mem->rec_n[c]    = n_seq_tokens;
''',
         '''            if (appended[i] != UINT32_MAX) {
                mem->rec_n[c] = appended[i] + n_seq_tokens;
            } else {
                mem->rec_set[c] ^= 1;
                mem->rec_n[c]    = n_seq_tokens;
            }
            mem->rec_last[c] = n_seq_tokens;
'''),
    ],
    os.path.join(tree, "ggml", "include", "ggml.h"): [
        ('''    //   info : [5, n_seqs] I32 per sequence: row read, row written, records replayed, set read, set written
''',
         '''    //   info : [5, n_seqs] I32 per sequence: row read, row written (-1: the row is left as it is), records replayed,
    //          the first record read and the first written (indices into rec's R * n_sets records)
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
