#!/usr/bin/env python3
"""0.5.3: coding-agent compatibility for the Responses and Messages routes (issue #12).

Coding agents failed against /v1/responses and /v1/messages:
- A system or developer message after the conversation started (Codex sends developer messages between turns, Claude
  Code 2.1 sends system messages inside "messages") made templates that only allow a leading one, the Qwen template
  among them, raise "System message must be at the beginning." and the request return HTTP 500.
  oaicompat_chat_params_parse passes such a message on as a user message saying whose it is, only for templates that
  carry that check; the leading ones stay as they are.
- Responses custom (freeform) tools and namespace tools were dropped with a warning, so their calls never happened and
  replaying them failed ("Cannot determine type of 'item'"). The conversion now offers a custom tool as a function
  taking one string "input" (a grammar format is described to the model), the tools of a namespace as functions of
  their own (NAMESPACE__NAME only when a name repeats), tools from additional_tools input items too, and maps
  custom_tool_call / custom_tool_call_output and function calls carrying a namespace back to those functions. The
  map travels as strix_resp_tools to task_params::resp_tools; the response side turns a call back into a
  custom_tool_call item (input unwrapped) or a function_call naming its namespace, in the non-stream output, the
  streamed output_item events (a custom call's input goes out whole at the end, with custom_tool_call_input.delta /
  .done) and response.completed.
- Hosted tools the server cannot run (web_search, file_search, ...) are named in an X-Rulith-Unsupported-Tools response
  header; reasoning items with only encrypted_content, items of hosted tools and other unknown item types are left
  out instead of failing the request; tool outputs with non-text parts say what was left out; a tool_choice object
  maps to required / the allowed_tools mode.
Probed (tmp/resp/probe_codex.py): 12 cases, 0.5.2 failed 8 of the first 9 (HTTP 500, dropped custom tools, 400 on
round trips); with this patch 12/12, and the installed Codex CLI 0.160 (plain, code_mode custom exec) and Claude Code
2.1.247 finish an edit-and-run task against the server.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 34 hunks across 5 file(s).

Usage: python patches/apply_agent_compat_053.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'strix_resp_tools'

EDITS = {
    os.path.join(tree, "tools", "server", "server-chat.cpp"): [
        ('''
#include <sstream>
''',
         '''
#include <algorithm>
#include <map>
#include <set>
#include <sstream>
'''),
        ('''    std::vector<json> chatcmpl_messages;

''',
         '''    std::vector<json> chatcmpl_messages;

    // strixllama: the tools first, so calls in the input can use the names the model is shown (coding agents such as
    // Codex send custom and namespace tools; they were dropped and every round trip of them failed). Tools come from
    // "tools" and from additional_tools input items. Function tools pass through; a custom (freeform) tool becomes a
    // function taking one string "input"; the tools inside a namespace become functions of their own, named as they
    // are when the name is unique and NAMESPACE__NAME otherwise. Tools the server cannot run (web_search, file_search,
    // ...) are left out and listed in strix_resp_unsupported (the X-Rulith-Unsupported-Tools response header).
    // strix_resp_tools tells the response side how to turn a call back into what the client offered.
    struct resp_tool {
        std::string kind; // "function" or "custom"
        std::string name;
        std::string ns;
        json        def;
    };
    std::vector<resp_tool>   resp_tools;
    std::vector<std::string> unsupported_tools;
    const bool has_tools = response_body.contains("tools");
    std::function<void(const json &, const std::string &)> add_resp_tool = [&](const json & tool, const std::string & ns) {
        if (!tool.is_object()) {
            throw std::invalid_argument("'tools' must be an array of objects");
        }
        const std::string type = json_value(tool, "type", std::string());
        if ((type == "function" || type == "custom") && tool.contains("name") && tool.at("name").is_string()) {
            resp_tools.push_back({type, tool.at("name").get<std::string>(), ns, tool});
        } else if (type == "namespace" && ns.empty() && tool.contains("tools") && tool.at("tools").is_array()) {
            const std::string name = json_value(tool, "name", std::string());
            for (const auto & child : tool.at("tools")) {
                add_resp_tool(child, name);
            }
        } else {
            const std::string what = type.empty() ? std::string("unknown") : type;
            if (std::find(unsupported_tools.begin(), unsupported_tools.end(), what) == unsupported_tools.end()) {
                unsupported_tools.push_back(what);
            }
        }
    };
    if (has_tools) {
        if (!response_body.at("tools").is_array()) {
            throw std::invalid_argument("'tools' must be an array of objects");
        }
        for (const auto & tool : response_body.at("tools")) {
            add_resp_tool(tool, "");
        }
    }
    bool has_additional_tools = false;
    if (input_value.is_array()) {
        for (const auto & item : input_value) {
            if (item.is_object() && json_value(item, "type", std::string()) == "additional_tools" &&
                    item.contains("tools") && item.at("tools").is_array()) {
                has_additional_tools = true;
                for (const auto & tool : item.at("tools")) {
                    add_resp_tool(tool, "");
                }
            }
        }
    }
    std::map<std::string, int> n_named;
    for (const auto & t : resp_tools) {
        n_named[t.name]++;
    }
    json chatcmpl_tools = json::array();
    json resp_tool_map  = json::object();
    std::map<std::string, std::string> model_name_of; // namespace + '\\n' + name -> the name the model is shown
    for (const auto & t : resp_tools) {
        const std::string model_name = n_named[t.name] > 1 && !t.ns.empty() ? t.ns + "__" + t.name : t.name;
        model_name_of[t.ns + "\\n" + t.name] = model_name;
        json fn;
        if (t.kind == "function") {
            fn = t.def;
            fn.erase("type");
            if (!fn.contains("strict")) {
                fn["strict"] = true;
            }
        } else {
            std::string input_desc = "The input for the tool as plain text, not JSON";
            const json  format     = json_value(t.def, "format", json::object());
            if (format.is_object() && json_value(format, "type", std::string()) == "grammar") {
                input_desc += ". It must follow this " + json_value(format, "syntax", std::string("lark")) +
                              " grammar:\\n" + json_value(format, "definition", std::string());
            }
            fn = json {
                {"name",        t.name},
                {"description", json_value(t.def, "description", std::string())},
                {"parameters",  json {
                    {"type",       "object"},
                    {"properties", json { {"input", json { {"type", "string"}, {"description", input_desc} }} }},
                    {"required",   json::array({"input"})},
                }},
            };
        }
        fn["name"] = model_name;
        chatcmpl_tools.push_back(json { {"type", "function"}, {"function", fn} });
        if (t.kind == "custom" || !t.ns.empty() || model_name != t.name) {
            json entry = { {"type", t.kind}, {"name", t.name} };
            if (!t.ns.empty()) {
                entry["namespace"] = t.ns;
            }
            resp_tool_map[model_name] = entry;
        }
    }
    for (const auto & what : unsupported_tools) {
        SRV_WRN("Responses tool type '%s' is not supported by this server; the model is not offered it\\n", what.c_str());
    }
    // the name the model knows a called tool by (a call in the input carries the client's name and namespace)
    auto model_tool_name = [&](const json & item) -> std::string {
        const std::string name = json_value(item, "name", std::string());
        const std::string ns   = json_value(item, "namespace", std::string());
        auto it = model_name_of.find(ns + "\\n" + name);
        if (it != model_name_of.end()) {
            return it->second;
        }
        return name;
    };
    // a tool output as chat content: a string as it is, input_text parts as text parts, anything else described
    auto tool_output_content = [](const json & output) -> json {
        if (output.is_string()) {
            return output;
        }
        if (!output.is_array()) {
            return output.dump();
        }
        json parts = json::array();
        for (const auto & part : output) {
            const std::string type = json_value(part, "type", std::string());
            if ((type == "input_text" || type == "output_text" || type == "text") && part.contains("text") &&
                    part.at("text").is_string()) {
                parts.push_back(json { {"text", part.at("text")}, {"type", "text"} });
            } else if (type == "input_image" || type == "input_file") {
                SRV_WRN("a %s part of a tool output is not supported; the model is told it was left out\\n", type.c_str());
                parts.push_back(json { {"text", "[" + type + " left out]"}, {"type", "text"} });
            } else {
                parts.push_back(json { {"text", part.dump()}, {"type", "text"} });
            }
        }
        return parts;
    };
    std::set<std::string> skipped_items;

'''),
        ('''            bool merge_prev = !chatcmpl_messages.empty() && chatcmpl_messages.back().value("role", "") == "assistant";

''',
         '''            bool merge_prev = !chatcmpl_messages.empty() && chatcmpl_messages.back().value("role", "") == "assistant";

            // strixllama: a custom tool call is a call of the function the custom tool became, its output that call's
            // output; additional_tools items only carry tools (collected above)
            if (exists_and_is_string(item, "type")) {
                const std::string item_type = item.at("type").get<std::string>();
                if (item_type == "additional_tools") {
                    continue;
                }
                if (item_type == "custom_tool_call") {
                    item["type"]      = "function_call";
                    item["arguments"] = json { {"input", json_value(item, "input", std::string())} }.dump();
                } else if (item_type == "custom_tool_call_output") {
                    item["type"] = "function_call_output";
                }
            }

'''),
        ('''            } else if (exists_and_is_string(item, "arguments") &&
''',
         '''            } else if (item.contains("arguments") &&
'''),
        ('''                // #responses_create-input-input_item_list-item-function_tool_call
                json tool_call = {
''',
         '''                // #responses_create-input-input_item_list-item-function_tool_call
                // strixllama: under the name the model was shown (namespace tools); arguments given as an object are
                // serialized
                const json & args = item.at("arguments");
                json tool_call = {
'''),
        ('''                        {"arguments", item.at("arguments")},
                        {"name",      item.at("name")},
''',
         '''                        {"arguments", args.is_string() ? args : json(args.dump())},
                        {"name",      model_tool_name(item)},
'''),
        ('''                (exists_and_is_string(item, "output") || exists_and_is_array(item, "output")) &&
''',
         '''                item.contains("output") &&
'''),
        ('''                if (item.at("output").is_string()) {
                    chatcmpl_messages.push_back(json {
                        {"content",      item.at("output")},
                        {"role",         "tool"},
                        {"tool_call_id", item.at("call_id")},
                    });
                } else {
                    json chatcmpl_outputs = item.at("output");
                    for (json & chatcmpl_output : chatcmpl_outputs) {
                        if (!chatcmpl_output.contains("type") || chatcmpl_output.at("type") != "input_text") {
                            throw std::invalid_argument("Output of tool call should be 'Input text'");
                        }
                        chatcmpl_output["type"] = "text";
                    }
                    chatcmpl_messages.push_back(json {
                        {"content",      chatcmpl_outputs},
                        {"role",         "tool"},
                        {"tool_call_id", item.at("call_id")},
                    });
                }
            } else if (exists_and_is_array(item, "summary") &&
                exists_and_is_string(item, "type") &&
''',
         '''                // strixllama: text parts as text, other parts described instead of failing the request
                chatcmpl_messages.push_back(json {
                    {"content",      tool_output_content(item.at("output"))},
                    {"role",         "tool"},
                    {"tool_call_id", item.at("call_id")},
                });
            } else if (exists_and_is_string(item, "type") &&
'''),
        ('''
                if (!exists_and_is_array(item, "content")) {
                    throw std::invalid_argument("item['content'] is not an array");
''',
         '''                // strixllama: the reasoning text, else its summary; a reasoning item with neither (only
                // encrypted_content, as clients replay it) is left out instead of failing the request
                std::string text;
                if (exists_and_is_array(item, "content")) {
                    for (const auto & part : item.at("content")) {
                        if (exists_and_is_string(part, "text")) {
                            text += (text.empty() ? "" : "\\n\\n") + part.at("text").get<std::string>();
                        }
                    }
'''),
        ('''                if (item.at("content").empty()) {
                    throw std::invalid_argument("item['content'] is empty");
''',
         '''                if (text.empty() && exists_and_is_array(item, "summary")) {
                    for (const auto & part : item.at("summary")) {
                        if (exists_and_is_string(part, "text")) {
                            text += (text.empty() ? "" : "\\n\\n") + part.at("text").get<std::string>();
                        }
                    }
'''),
        ('''                if (!exists_and_is_string(item.at("content")[0], "text")) {
                    throw std::invalid_argument("item['content']['text'] is not a string");
''',
         '''                if (text.empty()) {
                    continue;
'''),
        ('''                    prev_msg["reasoning_content"] = item.at("content")[0].at("text");
''',
         '''                    prev_msg["reasoning_content"] = text;
'''),
        ('''                        {"reasoning_content", item.at("content")[0].at("text")},
''',
         '''                        {"reasoning_content", text},
'''),
        ('''                }
            } else {
''',
         '''                }
            } else if (exists_and_is_string(item, "type") && item.at("type") != "message") {
                // strixllama: items of hosted tools and other kinds this server has no use for (web_search_call,
                // local_shell_call, compaction, item_reference, ...) are left out instead of failing the request
                skipped_items.insert(item.at("type").get<std::string>());
            } else {
'''),
        ('''
    if (response_body.contains("tools")) {
        if (!response_body.at("tools").is_array()) {
            throw std::invalid_argument("'tools' must be an array of objects");
        }
        std::vector<json> chatcmpl_tools;
        for (json resp_tool : response_body.at("tools")) {
            json chatcmpl_tool;

            const std::string type = json_value(resp_tool, "type", std::string());
            if (type != "function") {
                // Non-function Responses tools have no Chat Completions equivalent.
                SRV_WRN("unsupported Responses tool type '%s' skipped\\n", type.c_str());
                continue;
            }
            resp_tool.erase("type");
            chatcmpl_tool["type"] = "function";

            if (!resp_tool.contains("strict")) {
                resp_tool["strict"] = true;
            }
            chatcmpl_tool["function"] = resp_tool;
            chatcmpl_tools.push_back(chatcmpl_tool);
        }
''',
         '''    for (const auto & what : skipped_items) {
        SRV_WRN("Responses input items of type '%s' are not supported by this server; left out\\n", what.c_str());
    }

    if (has_tools || has_additional_tools) {
'''),
        ('''            chatcmpl_body["tools"] = chatcmpl_tools;
        }
    }

''',
         '''            chatcmpl_body["tools"] = chatcmpl_tools;
        }
        if (!resp_tool_map.empty()) {
            chatcmpl_body["strix_resp_tools"] = resp_tool_map;
        }
        if (!unsupported_tools.empty()) {
            chatcmpl_body["strix_resp_unsupported"] = unsupported_tools;
        }
    }

    // strixllama: a tool_choice object names one tool (function, custom) or a set (allowed_tools): the closest the
    // chat tool choice can say is "required" or the set's mode; a hosted tool choice is "auto"
    if (response_body.contains("tool_choice") && response_body.at("tool_choice").is_object()) {
        const json &      choice = response_body.at("tool_choice");
        const std::string type   = json_value(choice, "type", std::string());
        std::string       mapped = "auto";
        if (type == "function" || type == "custom") {
            mapped = "required";
        } else if (type == "allowed_tools") {
            mapped = json_value(choice, "mode", std::string("auto"));
        }
        chatcmpl_body["tool_choice"] = chatcmpl_tools.empty() ? std::string("auto") : mapped;
    }

'''),
    ],
    os.path.join(tree, "tools", "server", "server-common.cpp"): [
        ('''
    auto caps = common_chat_templates_get_caps(opt.tmpls.get());
''',
         '''
    // strixllama: a system or developer message after the conversation started (coding agents such as Codex send
    // developer messages between turns) made templates that allow them only at the start raise "System message must be
    // at the beginning." and the request fail with HTTP 500. With such a template it is passed on as a user message
    // saying whose it is; the leading system and developer messages stay as they are.
    if (opt.use_jinja && opt.tmpls) {
        bool started = false;
        bool late    = false;
        for (const auto & msg : messages) {
            const std::string role = json_value(msg, "role", std::string());
            if (role != "system" && role != "developer") {
                started = true;
            } else if (started) {
                late = true;
                break;
            }
        }
        if (late && (common_chat_templates_source(opt.tmpls.get()).find("must be at the beginning") != std::string::npos ||
                     common_chat_templates_source(opt.tmpls.get(), "tool_use").find("must be at the beginning") != std::string::npos)) {
            started = false;
            for (auto & msg : messages) {
                const std::string role = json_value(msg, "role", std::string());
                if (role != "system" && role != "developer") {
                    started = true;
                    continue;
                }
                if (!started) {
                    continue;
                }
                const std::string label = "[" + role + " message]\\n";
                msg["role"] = "user";
                json & content = msg["content"];
                if (content.is_string()) {
                    content = label + content.get<std::string>();
                } else if (content.is_array()) {
                    json parts = json::array();
                    parts.push_back(json { {"type", "text"}, {"text", label} });
                    parts.insert(content);
                    content = parts;
                } else {
                    content = label;
                }
            }
        }
    }

    auto caps = common_chat_templates_get_caps(opt.tmpls.get());
'''),
    ],
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''            task.params.oaicompat_model   = meta->model_name;

''',
         '''            task.params.oaicompat_model   = meta->model_name;
            if (res_type == TASK_RESPONSE_TYPE_OAI_RESP && data.contains("strix_resp_tools") &&
                    data.at("strix_resp_tools").is_object() && !data.at("strix_resp_tools").empty()) {
                task.params.resp_tools = std::make_shared<const json>(data.at("strix_resp_tools"));
            }

'''),
        ('''        SRV_DBG("%s\\n", "Request converted: OpenAI Responses -> OpenAI Chat Completions");
        SRV_DBG("converted request: %s\\n", body.dump().c_str());
        json body_parsed = oaicompat_chat_params_parse(
            body,
''',
         '''        SRV_DBG("%s\\n", "Request converted: OpenAI Responses -> OpenAI Chat Completions");
        SRV_DBG("converted request: %s\\n", body.dump().c_str());
        // strixllama: tools the model was not offered are named in a response header, so a client can tell
        const json unsupported = json_value(body, "strix_resp_unsupported", json::array());
        body.erase("strix_resp_unsupported");
        json body_parsed = oaicompat_chat_params_parse(
            body,
'''),
        ('''        return handle_completions_impl(
            req,
            SERVER_TASK_TYPE_COMPLETION,
            body_parsed,
            files,
            TASK_RESPONSE_TYPE_OAI_RESP);
''',
         '''        auto res_impl = handle_completions_impl(
            req,
            SERVER_TASK_TYPE_COMPLETION,
            body_parsed,
            files,
            TASK_RESPONSE_TYPE_OAI_RESP);
        if (unsupported.is_array() && !unsupported.empty()) {
            std::string names;
            for (const auto & n : unsupported) {
                names += (names.empty() ? "" : ", ") + (n.is_string() ? n.get<std::string>() : n.dump());
            }
            res_impl->headers["X-Rulith-Unsupported-Tools"] = names;
        }
        return res_impl;
'''),
    ],
    os.path.join(tree, "tools", "server", "server-task.h"): [
        ('''
    // realtime control (SERVER_TASK_TYPE_CONTROL)
''',
         '''
    // strixllama: OpenAI Responses tools offered to the model under another form (custom tools as functions taking one
    // string "input", namespace tools as plain functions), keyed by the name the model was shown:
    // {"type": "custom"|"function", "name": ..., "namespace": ...}; null when every tool is a plain function
    std::shared_ptr<const json> resp_tools;

    // realtime control (SERVER_TASK_TYPE_CONTROL)
'''),
        ('''    std::string oai_resp_fc_id; // function call ID for current args delta

''',
         '''    std::string oai_resp_fc_id; // function call ID for current args delta
    bool oai_resp_fc_custom = false; // strixllama: the current call is of a custom tool (its events wait for the end)
    std::shared_ptr<const json> resp_tools; // strixllama: task_params::resp_tools

'''),
        ('''        return task_result_state(params.chat_parser_params);
''',
         '''        task_result_state state(params.chat_parser_params);
        state.resp_tools = params.resp_tools;
        return state;
'''),
        ('''    std::string oai_resp_message_id;

''',
         '''    std::string oai_resp_message_id;
    std::shared_ptr<const json> resp_tools; // strixllama: task_params::resp_tools

'''),
        ('''        oai_resp_message_id = state.oai_resp_message_id;
    }
''',
         '''        oai_resp_message_id = state.oai_resp_message_id;
        resp_tools = state.resp_tools;
    }
'''),
        ('''    std::string oai_resp_fc_id;

''',
         '''    std::string oai_resp_fc_id;
    bool oai_resp_fc_custom = false;        // strixllama: task_result_state::oai_resp_fc_custom
    std::shared_ptr<const json> resp_tools; // strixllama: task_params::resp_tools

'''),
    ],
    os.path.join(tree, "tools", "server", "server-task.cpp"): [
        ('''
json server_task_result_cmpl_final::to_json_oaicompat_resp() {
''',
         '''
// strixllama: the client's view of a tool call for the OpenAI Responses API (task_params::resp_tools). A call of a
// custom tool, offered to the model as a function taking one string "input", is a custom_tool_call carrying that input;
// a call of a tool from a namespace names the tool and its namespace; other calls are left as they are.
static const json * resp_tool_entry(const std::shared_ptr<const json> & tools, const std::string & name) {
    if (!tools || !tools->is_object() || !tools->contains(name)) {
        return nullptr;
    }
    return &tools->at(name);
}

static bool resp_tool_is_custom(const std::shared_ptr<const json> & tools, const std::string & name) {
    const json * e = resp_tool_entry(tools, name);
    return e && json_value(*e, "type", std::string()) == "custom";
}

static std::string resp_custom_input(const std::string & arguments) {
    const json args = json::parse_no_throw(arguments);
    if (!args.is_discarded() && args.is_object() && args.contains("input")) {
        return args.at("input").is_string() ? args.at("input").get<std::string>() : args.at("input").dump_safe();
    }
    return arguments;
}

static json resp_tool_call_item(const std::shared_ptr<const json> & tools, const common_chat_tool_call & tool_call) {
    const json * e = resp_tool_entry(tools, tool_call.name);
    json item;
    if (e && json_value(*e, "type", std::string()) == "custom") {
        item = json {
            {"id",      "ctc_" + tool_call.id},
            {"type",    "custom_tool_call"},
            {"status",  "completed"},
            {"call_id", "call_" + tool_call.id},
            {"name",    json_value(*e, "name", tool_call.name)},
            {"input",   resp_custom_input(tool_call.arguments)},
        };
    } else {
        item = json {
            {"id",        "fc_" + tool_call.id},
            {"type",      "function_call"},
            {"status",    "completed"},
            {"arguments", tool_call.arguments},
            {"call_id",   "call_" + tool_call.id},
            {"name",      e ? json_value(*e, "name", tool_call.name) : tool_call.name},
        };
    }
    if (e && e->contains("namespace")) {
        item["namespace"] = e->at("namespace");
    }
    return item;
}

json server_task_result_cmpl_final::to_json_oaicompat_resp() {
'''),
        ('''        output.push_back(json {
            {"id",        "fc_" + tool_call.id},
            {"type",      "function_call"},
            {"status",    "completed"},
            {"arguments", tool_call.arguments},
            {"call_id",   "call_" + tool_call.id},
            {"name",      tool_call.name},
        });
''',
         '''        output.push_back(resp_tool_call_item(resp_tools, tool_call));
'''),
        ('''        const json output_item = {
            {"id",        "fc_" + tool_call.id},
            {"type",      "function_call"},
            {"status",    "completed"},
            {"arguments", tool_call.arguments},
            {"call_id",   "call_" + tool_call.id},
            {"name",      tool_call.name}
        };
''',
         '''        const json output_item = resp_tool_call_item(resp_tools, tool_call);
        if (output_item.at("type") == "custom_tool_call") {
            // strixllama: the partial results held a custom call's events back (its arguments are the JSON the model
            // wrote around the input); the whole input goes out now
            json added = output_item;
            added["status"] = "in_progress";
            added["input"]  = "";
            server_sent_events.push_back(json {
                {"event", "response.output_item.added"},
                {"data", json {
                    {"type", "response.output_item.added"},
                    {"item", added}
                }}
            });
            server_sent_events.push_back(json {
                {"event", "response.custom_tool_call_input.delta"},
                {"data", json {
                    {"type",    "response.custom_tool_call_input.delta"},
                    {"item_id", output_item.at("id")},
                    {"delta",   output_item.at("input")}
                }}
            });
            server_sent_events.push_back(json {
                {"event", "response.custom_tool_call_input.done"},
                {"data", json {
                    {"type",    "response.custom_tool_call_input.done"},
                    {"item_id", output_item.at("id")},
                    {"input",   output_item.at("input")}
                }}
            });
        }
'''),
        ('''    oai_resp_fc_id         = state.oai_resp_fc_id;

''',
         '''    oai_resp_fc_id         = state.oai_resp_fc_id;
    oai_resp_fc_custom     = state.oai_resp_fc_custom;
    resp_tools             = state.resp_tools;

'''),
        ('''            state.oai_resp_fc_id = diff.tool_call_delta.id;
''',
         '''            state.oai_resp_fc_id     = diff.tool_call_delta.id;
            state.oai_resp_fc_custom = resp_tool_is_custom(state.resp_tools, diff.tool_call_delta.name);
'''),
        ('''            events.push_back(json {
                {"event", "response.output_item.added"},
                {"data", json {
                    {"type",  "response.output_item.added"},
                    {"item", json {
                        {"id",        "fc_" + diff.tool_call_delta.id},
                        {"arguments", ""},
                        {"call_id",   "call_" + diff.tool_call_delta.id},
                        {"name",      diff.tool_call_delta.name},
                        {"type",      "function_call"},
                        {"status",    "in_progress"},
''',
         '''            // strixllama: a custom tool's call goes out whole with the final result; a namespace tool's call names
            // the tool and its namespace (task_params::resp_tools)
            oai_resp_fc_custom = resp_tool_is_custom(resp_tools, diff.tool_call_delta.name);
            if (!oai_resp_fc_custom) {
                json item = json {
                    {"id",        "fc_" + diff.tool_call_delta.id},
                    {"arguments", ""},
                    {"call_id",   "call_" + diff.tool_call_delta.id},
                    {"name",      diff.tool_call_delta.name},
                    {"type",      "function_call"},
                    {"status",    "in_progress"},
                };
                if (const json * e = resp_tool_entry(resp_tools, diff.tool_call_delta.name)) {
                    item["name"] = json_value(*e, "name", diff.tool_call_delta.name);
                    if (e->contains("namespace")) {
                        item["namespace"] = e->at("namespace");
                    }
                }
                events.push_back(json {
                    {"event", "response.output_item.added"},
                    {"data", json {
                        {"type",  "response.output_item.added"},
                        {"item", item},
'''),
        ('''                    }},
                }},
            });
            oai_resp_fc_id = diff.tool_call_delta.id;
''',
         '''                    }},
                });
            }
            oai_resp_fc_id = diff.tool_call_delta.id;
'''),
        ('''
        if (!diff.tool_call_delta.arguments.empty()) {
            events.push_back(json {
''',
         '''
        if (!diff.tool_call_delta.arguments.empty() && !oai_resp_fc_custom) {
            events.push_back(json {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
