#!/usr/bin/env python3
"""Block keys in adjacent rows: the block-key cache laid out by residue class.

A block's key sat in the row of its first cell, so a conversation's keys were 1 KB apart and the DRAM channels aliased; cell c now maps to row (c % r)*S + c/r, a bijection, so the keys of consecutive blocks are adjacent rows.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 12 hunks across 2 file(s).

Usage: python patches/apply_kb_rows_036.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'kb_row(uint32_t cell)'

EDITS = {
    os.path.join(tree, "src", "llama-memory-hybrid-idx.h"): [
        ('''    ggml_tensor * get_kb(int32_t il) const;   // F16 [idx_dim, kv_size + 1]; null when off or no indexer on il
    uint32_t      kb_scratch_row() const;     // the spare row: kv_size of the indexer cache
''',
         '''    ggml_tensor * get_kb(int32_t il) const;   // F16 [idx_dim, kb_r*kb_s]; null when off or no indexer on il
    uint32_t      kb_scratch_row() const;     // the spare row: kb_row(kv_size) of the indexer cache
    // strixllama: a block's key sits in the row of its first cell, and the rows are laid out by residue class: cell c
    // in row (c % kb_r)*kb_s + c/kb_r. A conversation's blocks start every kb_r cells (kb_r = the block ratio), so
    // their keys are adjacent rows, and the decode score reads them as one run. With a row per cell they were 1 KB
    // apart, and eight conversations' keys read that way ran at ~50 GB/s (205 us a layer at 8 x 20K, 45 us adjacent;
    // one conversation at 110K: 33 us, 17 us adjacent): the DRAM channels alias on strides like that. Any c -> row
    // bijection is correct whatever the block layout; this one is also dense.
    uint32_t      kb_row(uint32_t cell) const { return (cell % kb_r)*kb_s + cell/kb_r; }
'''),
        ('''    std::map<int32_t, ggml_tensor *>     kb_map;
    // the sequences whose block keys have to be rebuilt (see kb_needs_full). All of them at the start and after
''',
         '''    std::map<int32_t, ggml_tensor *>     kb_map;
    uint32_t                             kb_r = 1;   // rows laid out by residue class mod kb_r (kb_row)
    uint32_t                             kb_s = 0;   // rows a class: ceil((kv_size + 1)/kb_r)
    // the sequences whose block keys have to be rebuilt (see kb_needs_full). All of them at the start and after
'''),
    ],
    os.path.join(tree, "src", "llama-memory-hybrid-idx.cpp"): [
        ('''
        std::map<ggml_backend_buffer_type_t, ggml_context *> ctx_map;
''',
         '''
        // the rows' residue classes follow the block ratio of the indexer layers (one ratio for all of them, as the
        // graph inputs assume); anything else keeps a row per cell in order
        uint32_t ratio = 0;
        for (uint32_t il = 0; il < n_layer; ++il) {
            if (filter_idx(il)) {
                const uint32_t ril = model.hparams.dsv4_compress_ratios[il];
                ratio = ratio == 0 || ratio == ril ? ril : UINT32_MAX;
            }
        }
        kb_r = ratio >= 1 && ratio <= 64 ? ratio : 1;
        kb_s = (kv_size + 1 + kb_r - 1)/kb_r;

        std::map<ggml_backend_buffer_type_t, ggml_context *> ctx_map;
'''),
        ('''            ggml_tensor * t = ggml_new_tensor_2d(ctx, GGML_TYPE_F16, idx_dim, (int64_t) kv_size + 1);
''',
         '''            ggml_tensor * t = ggml_new_tensor_2d(ctx, GGML_TYPE_F16, idx_dim, (int64_t) kb_r*kb_s);
'''),
        ('''        LLAMA_LOG_INFO("%s: QSA block-key cache: %zu layers, %.1f MiB\\n", __func__, kb_map.size(), bytes/1024.0/1024.0);
''',
         '''        LLAMA_LOG_INFO("%s: QSA block-key cache: %zu layers, %.1f MiB, rows by residue mod %u\\n", __func__, kb_map.size(),
                bytes/1024.0/1024.0, kb_r);
'''),
        ('''    return mem_idx ? mem_idx->get_size() : 0;
''',
         '''    return mem_idx ? kb_row(mem_idx->get_size()) : 0;
'''),
        ('''// A block's key sits at the row of its first cell. The moves lay a sequence out in position order, so its keys
''',
         '''// A block's key sits at the row of its first cell (kb_row). The moves lay a sequence out in position order, so its keys
'''),
        ('''            rows.push_back(m);
''',
         '''            // the cells src + i, i = j, j + kb_r, ... sit in consecutive rows from kb_row(src + j), and so do their
            // destinations: a run per residue class. The cell runs do not overlap, so neither do these
            for (uint32_t j = 0; j < kb_r && j < m.n; ++j) {
                llama_kv_cache::cell_move rm = m;
                rm.src = kb_row(m.src + j);
                rm.dst = kb_row(m.dst + j);
                rm.n   = (m.n - j + kb_r - 1)/kb_r;
                rows.push_back(rm);
            }
'''),
        ('''            out.bid_rows[b] = b < n_bid ? (int32_t) kv_off + bcell(b) : scratch;
''',
         '''            out.bid_rows[b] = b < n_bid ? (int32_t) kb_row(kv_off + bcell(b)) : scratch;
'''),
        ('''                out.dirty_dst[n_dirty] = (int32_t) kv_off + bcell(b);
''',
         '''                out.dirty_dst[n_dirty] = (int32_t) kb_row(kv_off + bcell(b));
'''),
        ('''                br[b] = b < n_bid ? (int32_t) kv_off + bid_cell[b] : scratch;
''',
         '''                br[b] = b < n_bid ? (int32_t) kb_row(kv_off + bid_cell[b]) : scratch;
'''),
        ('''                    dd[n_dirty] = (int32_t) kv_off + bid_cell[b];
''',
         '''                    dd[n_dirty] = (int32_t) kb_row(kv_off + bid_cell[b]);
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
