#!/usr/bin/env python3
"""Layer split when every device reports no free memory.

An integrated GPU counts pinned host buffers (ROCm_Host) against its memory: with ~37 GiB of experts in system memory HIP reported 0 MiB free when the MTP draft loaded, the default split by free memory became 0/0, every layer indexed past the device list and the draft failed with 'invalid vector subscript'. All-zero splits now split evenly.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 1 hunks across 1 file(s).

Usage: python patches/apply_split_no_free_048.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'every device full by its own count'

EDITS = {
    os.path.join(tree, "src", "llama-model.cpp"): [
        ('''            splits[i] = free;
        }
''',
         '''            splits[i] = free;
        }
        // every device full by its own count (an iGPU counts pinned host buffers against its memory): the
        // split points would be 0/0 and every layer would index past the device list, so split evenly
        if (std::all_of(splits.begin(), splits.end(), [](float x) { return x == 0.0f; })) {
            std::fill(splits.begin(), splits.end(), 1.0f);
        }
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
