#!/usr/bin/env python3
"""Lane-ordered activations for the 5-8 column q8_0 and Q6_K vector products (bitwise).

At 5-8 columns the vector kernel was bound by issuing its activation loads; laying q8_1 out by the lane that reads it keeps each lane's share, float order and reduction, so the products are the same bits and a step of eight conversations is 1-2 ms shorter.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 4 hunks across 1 file(s).

Usage: python patches/apply_mmvq_i8_036.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'mul_mat_vec_q8_0_i8'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmvq.cu"): [
        ('''#include <cstdint>
#include <type_traits>
''',
         '''#include <cstdint>
#include <cstring>
#include <vector>
#include <type_traits>
'''),
        ('''
// Dedicated MoE multi-token kernel.
''',
         '''
// strixllama: y for the 5-8 column q8_0 product, quantized exactly as quantize_q8_1 does it but laid out by the lane
// that reads it: the 8 bytes a lane takes of block kb, quarter q, for every column next to each other
// (((kb*4 + q)*NQ + c)*8), then the blocks' scales as floats (kb*ND + c, the half ds holds, widened). A lane loads its
// quarter of all columns with NQ/2 16-byte loads and their scales with ND/4, where the q8_1 layout took three loads a
// column: at 8 columns 6 loads an iteration instead of 24, next to the 5 of the weight. Measured on gfx1151, the model's
// dense q8_0 products of a decode step at 8 columns (tmp/dec036/gemv_bench): 22.5 -> 21.5 ms; at 2-4 columns the
// unroll_q8 path of mul_mat_vec_q stays ahead, so this path takes 5-8 columns (STRIX_MMVQ_I8=0: off, =6..8: from there).
static constexpr __host__ __device__ int mmvq_i8_nq(const int ncols) { return (ncols + 1) & ~1; }
static constexpr __host__ __device__ int mmvq_i8_nd(const int ncols) { return (ncols + 3) & ~3; }

static __global__ void quantize_q8_1_i8(
        const float * __restrict__ x, char * __restrict__ vy, const int ne00, const int s01, const int nq, const int nd) {
    const int i0 = blockDim.x*blockIdx.x + threadIdx.x;
    if (i0 >= ne00) {
        return;
    }
    const int c = blockIdx.y;

    const float xi = x[(int64_t) c*s01 + i0];
    float amax = fabsf(xi);
    amax = warp_reduce_max<QK8_1>(amax);

    const float  d = amax / 127.0f;
    const int8_t q = amax == 0.0f ? 0 : roundf(xi / d);

    const int kb  = i0 / QK8_1;
    const int iqs = i0 % QK8_1;
    vy[((int64_t) (kb*4 + iqs/8)*nq + c)*8 + iqs % 8] = q;

    if (iqs > 0) {
        return;
    }
    const int nb = ne00 / QK8_1;
    float * yd = (float *) (vy + (int64_t) nb*QK8_1*nq);
    yd[kb*nd + c] = __half2float(__float2half(d));
}

// One wave a row, the lane's share of it that of mul_mat_vec_q - the blocks lane/4 + 8i, the int pair 2*(lane%4) - in
// the same order with the same float expressions and the same reduction: each output is the bits the q8_1 path writes.
template <int ncols_dst>
__launch_bounds__(4*32, 1)
static __global__ void mul_mat_vec_q8_0_i8(
        const void * __restrict__ vx, const char * __restrict__ vy, float * __restrict__ dst,
        const int ncols_x, const int nrows_x, const int stride_row_x, const int stride_col_dst) {
#if defined(RDNA3_5)
    constexpr int vdr             = VDR_Q8_0_Q8_1_MMVQ;
    constexpr int lanes_per_block = QI8_0/vdr;
    constexpr int blocks_per_iter = 32/lanes_per_block;
    constexpr int NQ = mmvq_i8_nq(ncols_dst);
    constexpr int ND = mmvq_i8_nd(ncols_dst);
    static_assert(vdr == 2, "one int2 a column");

    const int lane = threadIdx.x;
    const int row  = blockIdx.x*blockDim.y + threadIdx.y;
    if (row >= nrows_x) {
        return;
    }

    const int k0  = lane/lanes_per_block;
    const int qtr = lane % lanes_per_block;
    const int kqs = vdr*qtr;
    const int blocks_per_row_x = ncols_x/QK8_0;

    const block_q8_0 * x  = (const block_q8_0 *) vx + (int64_t) row*stride_row_x + k0;
    const int4       * yq = (const int4 *) (vy + (int64_t) (k0*4 + qtr)*NQ*8);
    const float4     * yd = (const float4 *) (vy + (int64_t) blocks_per_row_x*QK8_1*NQ) + k0*(ND/4);

    float tmp[ncols_dst] = {0.0f};

    for (int kbx = k0; kbx < blocks_per_row_x; kbx += blocks_per_iter) {
        int   u[NQ][vdr];
        float dy[ND];
#pragma unroll
        for (int j = 0; j < NQ/2; ++j) {
            const int4 t = yq[j];
            u[2*j + 0][0] = t.x; u[2*j + 0][1] = t.y;
            u[2*j + 1][0] = t.z; u[2*j + 1][1] = t.w;
        }
#pragma unroll
        for (int j = 0; j < ND/4; ++j) {
            const float4 t = yd[j];
            dy[4*j + 0] = t.x; dy[4*j + 1] = t.y; dy[4*j + 2] = t.z; dy[4*j + 3] = t.w;
        }

        int v[vdr];
#pragma unroll
        for (int i = 0; i < vdr; ++i) {
            v[i] = get_int_b2(x->qs, kqs + i);
        }
        const float dx = x->d;
#pragma unroll
        for (int j = 0; j < ncols_dst; ++j) {
            tmp[j] += vec_dot_q8_0_q8_1_impl<float, vdr>(v, u[j], dx, dy[j]);
        }
        x  += blocks_per_iter;
        yq += blocks_per_iter*4*NQ*8/16;
        yd += blocks_per_iter*ND/4;
    }

#pragma unroll
    for (int j = 0; j < ncols_dst; ++j) {
        tmp[j] = mmvq_warp_reduce_sum<GGML_TYPE_Q8_0, 32>(tmp[j]);
    }

    if (lane == 0) {
#pragma unroll
        for (int j = 0; j < ncols_dst; ++j) {
            dst[j*stride_col_dst + row] = tmp[j];
        }
    }
#else
    GGML_UNUSED_VARS(vx, vy, dst, ncols_x, nrows_x, stride_row_x, stride_col_dst);
    NO_DEVICE_CODE;
#endif // defined(RDNA3_5)
}

static int strix_mmvq_i8_min_cols() {
    static const int v = getenv("STRIX_MMVQ_I8") ? atoi(getenv("STRIX_MMVQ_I8")) : 5;
    return v;
}

// the 5-8 column q8_0 product through the lane-ordered y; false: not this path
static bool ggml_cuda_mul_mat_vec_q8_0_i8(
        ggml_backend_cuda_context & ctx, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst) {
    const int ncols    = src1->ne[1];
    const int min_cols = strix_mmvq_i8_min_cols();
    const int cc       = ggml_cuda_info().devices[ggml_cuda_get_device()].cc;
    if (min_cols <= 0 || ncols < std::max(min_cols, 5) || ncols > 8 || src0->type != GGML_TYPE_Q8_0 || !GGML_CUDA_CC_IS_RDNA3_5(cc) ||
            src0->ne[2] != 1 || src0->ne[3] != 1 || src1->ne[2] != 1 || src1->ne[3] != 1 ||
            src0->nb[0] != ggml_type_size(src0->type) || src1->nb[0] != sizeof(float) || dst->nb[0] != sizeof(float) ||
            src1->ne[0] % QK8_0 != 0 || src1->ne[0] != src0->ne[0]) {
        return false;
    }
    cudaStream_t stream = ctx.stream();

    const int ne00 = src1->ne[0];
    const int nb   = ne00/QK8_1;
    const int nq   = mmvq_i8_nq(ncols);
    const int nd   = mmvq_i8_nd(ncols);
    ggml_cuda_pool_alloc<char> y(ctx.pool(), (size_t) nb*QK8_1*nq + (size_t) nb*nd*sizeof(float));
    {
        const dim3 num_blocks((ne00 + CUDA_QUANTIZE_BLOCK_SIZE - 1)/CUDA_QUANTIZE_BLOCK_SIZE, ncols, 1);
        quantize_q8_1_i8<<<num_blocks, CUDA_QUANTIZE_BLOCK_SIZE, 0, stream>>>(
            (const float *) src1->data, y.get(), ne00, src1->nb[1]/sizeof(float), nq, nd);
    }

    const void * vx             = src0->data;
    float      * dst_d          = (float *) dst->data;
    const int    nrows_x        = src0->ne[1];
    const int    stride_row_x   = src0->nb[1]/ggml_type_size(src0->type);
    const int    stride_col_dst = dst->nb[1]/sizeof(float);
    const dim3   block_dims(32, 4, 1);
    const dim3   block_nums((nrows_x + 3)/4, 1, 1);
    switch (ncols) {
        case 5: mul_mat_vec_q8_0_i8<5><<<block_nums, block_dims, 0, stream>>>(vx, y.get(), dst_d, ne00, nrows_x, stride_row_x, stride_col_dst); break;
        case 6: mul_mat_vec_q8_0_i8<6><<<block_nums, block_dims, 0, stream>>>(vx, y.get(), dst_d, ne00, nrows_x, stride_row_x, stride_col_dst); break;
        case 7: mul_mat_vec_q8_0_i8<7><<<block_nums, block_dims, 0, stream>>>(vx, y.get(), dst_d, ne00, nrows_x, stride_row_x, stride_col_dst); break;
        case 8: mul_mat_vec_q8_0_i8<8><<<block_nums, block_dims, 0, stream>>>(vx, y.get(), dst_d, ne00, nrows_x, stride_row_x, stride_col_dst); break;
        default: return false;
    }
    return true;
}

// strixllama: the same for the Q6_K lm head at 5-8 columns. A lane iqs of mul_mat_vec_q's Q6_K path reads, for
// superblock kb, the int iqs%8 of the q8_1 blocks g and g + 2 (g = 4*(iqs/16) + (iqs%16)/8) and their two scales; here
// those two ints of every column sit next to each other (((kb*32 + iqs)*NQ + c)*8 + i*4), and the two scales of every
// column of the lane's group ((kb*4 + iqs/8)*NQ + c)*2 + i. 32 loads of y an iteration at 8 columns become 8.
static __global__ void quantize_q8_1_q6_K_i8(
        const float * __restrict__ x, char * __restrict__ vy, const int ne00, const int s01, const int nq) {
    const int i0 = blockDim.x*blockIdx.x + threadIdx.x;
    if (i0 >= ne00) {
        return;
    }
    const int c = blockIdx.y;

    const float xi = x[(int64_t) c*s01 + i0];
    float amax = fabsf(xi);
    amax = warp_reduce_max<QK8_1>(amax);

    const float  d = amax / 127.0f;
    const int8_t q = amax == 0.0f ? 0 : roundf(xi / d);

    const int kb  = i0 / QK_K;
    const int qb  = (i0 % QK_K) / QK8_1;   // q8_1 block in the superblock
    const int iq  = i0 % QK8_1;
    const int g   = (qb/4)*2 + qb % 2;       // the lane group that reads it
    const int i   = (qb/2) % 2;              // as its first or second int
    const int iqs = g*8 + iq/4;
    vy[((int64_t) (kb*32 + iqs)*nq + c)*8 + i*4 + iq % 4] = q;

    if (iq > 0) {
        return;
    }
    const int nsb = ne00 / QK_K;
    float * yd = (float *) (vy + (int64_t) nsb*32*nq*8);
    yd[((int64_t) (kb*4 + g)*nq + c)*2 + i] = __half2float(__float2half(d));
}

template <int ncols_dst>
__launch_bounds__(4*32, 1)
static __global__ void mul_mat_vec_q6_K_i8(
        const void * __restrict__ vx, const char * __restrict__ vy, float * __restrict__ dst,
        const int ncols_x, const int nrows_x, const int stride_row_x, const int stride_col_dst) {
#if defined(RDNA3_5)
    constexpr int NQ = mmvq_i8_nq(ncols_dst);

    const int iqs = threadIdx.x;
    const int row = blockIdx.x*blockDim.y + threadIdx.y;
    if (row >= nrows_x) {
        return;
    }

    const int nsb = ncols_x/QK_K;

    // what vec_dot_q6_K_q8_1 takes from the weight, lane iqs
    const int scale_offset = (QI6_K/4) * (iqs / (QI6_K/2)) + (iqs % (QI6_K/2)) / (QI6_K/8);
    const int vh_shift     = 2 * ((iqs % (QI6_K/2)) / (QI6_K/4));
    const int vh_int       = (QI6_K/4) * (iqs / (QI6_K/2)) + iqs % (QI6_K/4);

    const block_q6_K * x  = (const block_q6_K *) vx + (int64_t) row*stride_row_x;
    const int4       * yq = (const int4 *) (vy + (int64_t) iqs*NQ*8);
    const float4     * yd = (const float4 *) ((const float *) (vy + (int64_t) nsb*32*NQ*8) + (iqs/8)*NQ*2);

    float tmp[ncols_dst] = {0.0f};

    for (int kbx = 0; kbx < nsb; ++kbx) {
        int   u[NQ][QR6_K];
        float d8[NQ][QR6_K];
#pragma unroll
        for (int j = 0; j < NQ/2; ++j) {
            const int4 t = yq[j];
            u[2*j + 0][0] = t.x; u[2*j + 0][1] = t.y;
            u[2*j + 1][0] = t.z; u[2*j + 1][1] = t.w;
            const float4 f = yd[j];
            d8[2*j + 0][0] = f.x; d8[2*j + 0][1] = f.y;
            d8[2*j + 1][0] = f.z; d8[2*j + 1][1] = f.w;
        }

        const block_q6_K * bq6_K = x + kbx;
        const int vl = get_int_b2(bq6_K->ql, iqs);
        const int vh = get_int_b2(bq6_K->qh, vh_int) >> vh_shift;
        const int8_t * scales = bq6_K->scales + scale_offset;
        const float d = bq6_K->d;

#pragma unroll
        for (int j = 0; j < ncols_dst; ++j) {
            tmp[j] += vec_dot_q6_K_q8_1_impl_mmvq(vl, vh, u[j], scales, d, d8[j]);
        }
        yq += 32*NQ*8/16;
        yd += 4*NQ*2/4;
    }

#pragma unroll
    for (int j = 0; j < ncols_dst; ++j) {
        tmp[j] = mmvq_warp_reduce_sum<GGML_TYPE_Q6_K, 32>(tmp[j]);
    }

    if (iqs == 0) {
#pragma unroll
        for (int j = 0; j < ncols_dst; ++j) {
            dst[j*stride_col_dst + row] = tmp[j];
        }
    }
#else
    GGML_UNUSED_VARS(vx, vy, dst, ncols_x, nrows_x, stride_row_x, stride_col_dst);
    NO_DEVICE_CODE;
#endif // defined(RDNA3_5)
}

static bool ggml_cuda_mul_mat_vec_q6_K_i8(
        ggml_backend_cuda_context & ctx, const ggml_tensor * src0, const ggml_tensor * src1, ggml_tensor * dst) {
    const int ncols    = src1->ne[1];
    const int min_cols = strix_mmvq_i8_min_cols();
    const int cc       = ggml_cuda_info().devices[ggml_cuda_get_device()].cc;
    if (min_cols <= 0 || ncols < std::max(min_cols, 5) || ncols > 8 || src0->type != GGML_TYPE_Q6_K || !GGML_CUDA_CC_IS_RDNA3_5(cc) ||
            src0->ne[2] != 1 || src0->ne[3] != 1 || src1->ne[2] != 1 || src1->ne[3] != 1 ||
            src0->nb[0] != ggml_type_size(src0->type) || src1->nb[0] != sizeof(float) || dst->nb[0] != sizeof(float) ||
            src1->ne[0] % QK_K != 0 || src1->ne[0] != src0->ne[0]) {
        return false;
    }
    cudaStream_t stream = ctx.stream();

    const int ne00 = src1->ne[0];
    const int nsb  = ne00/QK_K;
    const int nq   = mmvq_i8_nq(ncols);
    ggml_cuda_pool_alloc<char> y(ctx.pool(), (size_t) nsb*32*nq*8 + (size_t) nsb*4*nq*2*sizeof(float));
    {
        const dim3 num_blocks((ne00 + CUDA_QUANTIZE_BLOCK_SIZE - 1)/CUDA_QUANTIZE_BLOCK_SIZE, ncols, 1);
        quantize_q8_1_q6_K_i8<<<num_blocks, CUDA_QUANTIZE_BLOCK_SIZE, 0, stream>>>(
            (const float *) src1->data, y.get(), ne00, src1->nb[1]/sizeof(float), nq);
    }

    const void * vx             = src0->data;
    float      * dst_d          = (float *) dst->data;
    const int    nrows_x        = src0->ne[1];
    const int    stride_row_x   = src0->nb[1]/ggml_type_size(src0->type);
    const int    stride_col_dst = dst->nb[1]/sizeof(float);
    const dim3   block_dims(32, 4, 1);
    const dim3   block_nums((nrows_x + 3)/4, 1, 1);
    switch (ncols) {
        case 5: mul_mat_vec_q6_K_i8<5><<<block_nums, block_dims, 0, stream>>>(vx, y.get(), dst_d, ne00, nrows_x, stride_row_x, stride_col_dst); break;
        case 6: mul_mat_vec_q6_K_i8<6><<<block_nums, block_dims, 0, stream>>>(vx, y.get(), dst_d, ne00, nrows_x, stride_row_x, stride_col_dst); break;
        case 7: mul_mat_vec_q6_K_i8<7><<<block_nums, block_dims, 0, stream>>>(vx, y.get(), dst_d, ne00, nrows_x, stride_row_x, stride_col_dst); break;
        case 8: mul_mat_vec_q6_K_i8<8><<<block_nums, block_dims, 0, stream>>>(vx, y.get(), dst_d, ne00, nrows_x, stride_row_x, stride_col_dst); break;
        default: return false;
    }
    return true;
}

// Dedicated MoE multi-token kernel.
'''),
        ('''
    const int64_t ne10_padded = GGML_PAD(ne10, MATRIX_ROW_PADDING);
''',
         '''
    // STRIX_MMVQ_I8_CHECK=1 (graphs off): the product the usual way, then again through the lane-ordered path into
    // scratch, compared bit for bit (see the end of this function)
    static const bool i8_check = getenv("STRIX_MMVQ_I8_CHECK") && atoi(getenv("STRIX_MMVQ_I8_CHECK")) != 0;
    if (!i8_check && !ids && !fusion &&
            (ggml_cuda_mul_mat_vec_q8_0_i8(ctx, src0, src1, dst) || ggml_cuda_mul_mat_vec_q6_K_i8(ctx, src0, src1, dst))) {
        return;
    }

    const int64_t ne10_padded = GGML_PAD(ne10, MATRIX_ROW_PADDING);
'''),
        ('''        ne03,              ne3,           s03, s13,              s3,               ids_stride, stream);
}
''',
         '''        ne03,              ne3,           s03, s13,              s3,               ids_stride, stream);

    if (i8_check && !ids && !fusion) {
        const size_t n = ggml_nbytes(dst) / sizeof(float);
        ggml_cuda_pool_alloc<float> scratch(ctx.pool(), n);
        ggml_tensor dst_c = *dst;
        dst_c.data = scratch.get();
        if (ggml_cuda_mul_mat_vec_q8_0_i8(ctx, src0, src1, &dst_c) || ggml_cuda_mul_mat_vec_q6_K_i8(ctx, src0, src1, &dst_c)) {
            std::vector<float> want(n), got(n);
            CUDA_CHECK(cudaMemcpyAsync(want.data(), dst->data, n*sizeof(float), cudaMemcpyDeviceToHost, stream));
            CUDA_CHECK(cudaMemcpyAsync(got.data(), scratch.get(), n*sizeof(float), cudaMemcpyDeviceToHost, stream));
            CUDA_CHECK(cudaStreamSynchronize(stream));
            if (memcmp(want.data(), got.data(), n*sizeof(float)) != 0) {
                size_t k = 0;
                while (k < n && memcmp(&want[k], &got[k], sizeof(float)) == 0) { ++k; }
                fprintf(stderr, "MMVQ_I8 check: %s [%lld x %lld] x %lld columns, element %zu differs: %.9g vs %.9g\\n",
                        ggml_type_name(src0->type), (long long) src0->ne[0], (long long) src0->ne[1], (long long) src1->ne[1],
                        k, want[k], got[k]);
                GGML_ABORT("MMVQ_I8 check failed");
            }
            static int64_t n_checked = 0;
            if (++n_checked % 1000 == 0) {
                fprintf(stderr, "MMVQ_I8 check: %lld products, the lane-ordered path's equal\\n", (long long) n_checked);
            }
        }
    }
}
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
