#!/usr/bin/env python3
"""The decode indexer score skips the queries that cannot see a block.

With several conversations in a step, k_idx_score_dec (0.3.4) computed every query's four head scores against every block of the window and only then wrote -inf for the blocks of other conversations: eight conversations at 40K each scored 81K blocks eight times, 0.45-0.55 ms a layer. A thread pair now tests a query's visibility first - the tails as before, and the membership product, whose 0/1 terms make it a test of two bit masks for up to 32 slots (the queries' built once a workgroup, a block's once a pair) - and skips an invisible query's dot products; both threads of the pair skip together, so the shuffle stays inside it. The scores computed are the same bits as before and the skipped ones were -inf before too. Eight conversations at 40K: 105.8 -> 103.3 ms a step. STRIX_IDX_SCORE_DEC=2 still compares every strip with the unfused chain.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 6 hunks across 1 file(s).

Usage: python patches/apply_idx_score_skip_035.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'use_mask && threadIdx.x < (unsigned) nq'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "idx-relu-sum.cu"): [
        ('''// thread pair (2b, 2b + 1) takes key b: thread w the dims [64 w, 64 w + 64), the vector kernel's wave w
static __global__ void __launch_bounds__(256) k_idx_score_dec(const half * __restrict__ kb, const int64_t kbs,
''',
         '''// thread pair (2b, 2b + 1) takes key b: thread w the dims [64 w, 64 w + 64), the vector kernel's wave w
//
// strixllama: with several sequences in a strip a block is seen by the queries of its own sequence only, so each pair tests a
// query's visibility first and skips the dot products of an invisible one (the pair shares its key and query, so both skip
// together, and the shuffle stays inside it). A computed score is the same as before and a skipped one was -inf regardless.
// The membership product's terms are 0 or 1, so it is above 0.5 exactly when the block and the query share a slot: with at
// most 32 slots that is a test of two bit masks, the queries' made once a workgroup and a block's once a pair.
static __global__ void __launch_bounds__(256) k_idx_score_dec(const half * __restrict__ kb, const int64_t kbs,
'''),
        ('''    __shared__ float qsh[IDXD_MAXQ * 4 * 128];
    for (int i = threadIdx.x; i < nq * 4 * 128; i += blockDim.x) {
''',
         '''    __shared__ float qsh[IDXD_MAXQ * 4 * 128];
    __shared__ uint32_t tok_mask[IDXD_MAXQ];
    const bool use_mask = seq_blk != nullptr && n_slots <= 32;
    for (int i = threadIdx.x; i < nq * 4 * 128; i += blockDim.x) {
'''),
        ('''        qsh[i] = q[(int64_t) (i / 128) * qs + i % 128];
    }
''',
         '''        qsh[i] = q[(int64_t) (i / 128) * qs + i % 128];
    }
    if (use_mask && threadIdx.x < (unsigned) nq) {
        uint32_t m = 0;
        for (int sl = 0; sl < n_slots; ++sl) {
            m |= (seq_tok[(int64_t) threadIdx.x * n_slots + sl] > 0.5f ? 1u : 0u) << sl;
        }
        tok_mask[threadIdx.x] = m;
    }
'''),
        ('''    const bool valid = b < nb;
    half2 k[32];
''',
         '''    const bool valid = b < nb;
    uint32_t blk_mask = 0;
    if (valid && use_mask) {
        for (int sl = 0; sl < n_slots; ++sl) {
            blk_mask |= (seq_blk[(int64_t) b * n_slots + sl] > 0.5f ? 1u : 0u) << sl;
        }
    }
    half2 k[32];
'''),
        ('''    for (int t = 0; t < nq; ++t) {
        float acc = 0.0f;
''',
         '''    for (int t = 0; t < nq; ++t) {
        bool vis = valid && tails[t] > st;
        if (vis && seq_blk) {
            if (use_mask) {
                vis = (blk_mask & tok_mask[t]) != 0;
            } else {
                // the membership product's 0/1 terms: exact in any order
                float m = 0.0f;
                for (int sl = 0; sl < n_slots; ++sl) {
                    m += seq_blk[(int64_t) b * n_slots + sl] * seq_tok[(int64_t) t * n_slots + sl];
                }
                vis = m > 0.5f;
            }
        }
        if (!vis) {
            if (valid && w == 0) {
                out[(int64_t) t * nb + b] = -INFINITY;
            }
            continue;
        }
        float acc = 0.0f;
'''),
        ('''        if (valid && w == 0) {
            bool vis = tails[t] > st;
            if (seq_blk) {
                // the membership product's 0/1 terms: exact in any order
                float m = 0.0f;
                for (int sl = 0; sl < n_slots; ++sl) {
                    m += seq_blk[(int64_t) b * n_slots + sl] * seq_tok[(int64_t) t * n_slots + sl];
                }
                vis = vis && m > 0.5f;
            }
            out[(int64_t) t * nb + b] = vis ? acc + zero : -INFINITY;
''',
         '''        if (w == 0) {
            out[(int64_t) t * nb + b] = acc + zero;
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
