#!/usr/bin/env python3
"""Speculative sampling: MTP drafts drawn from q, verified by p / q; sampled requests draft less.

With sampling (temperature above 0) the MTP draft was each step's top candidate and the verification an exact match against the target's own draw, so a draft token was accepted with probability p(x): at Jan's defaults (temperature 0.7, top_k 20, top_p 0.8) on Chinese prose, 63% at the first position. Now the drafter draws the draft from q - its top candidates through the target's top-k, top-p, min-p and temperature - and the verification accepts a draft token with probability min(1, p(x) / q(x)) and replaces a rejected one with a draw from max(0, p - q) (Leviathan et al. 2023, Chen et al. 2023): every token is distributed exactly as the target's sampler draws it, and the first position is accepted with probability sum min(p, q), 67%. Greedy decoding keeps the exact match, bit for bit; so does a sampler whose distribution this cannot compute (mirostat, backend sampling). With p_min, a short drawn draft is kept rather than dropped for n_min (dropping it would bias the tokens kept). Drafts of sampled requests, accepted less often, take their own cap by generating slots (STRIX_SPEC_DRAFT_BY_SLOTS_SAMPLED, which the manager sets to 2,2,1,1,0). tools/spec_sampling_mc.py checks the shipped functions by Monte Carlo. STRIX_SPEC_SAMPLING=0: the exact match as before; STRIX_SPEC_SAMPLING_STATS=1: the expected acceptance per draft temperature in the log; STRIX_SPEC_QSCALE: q's temperature over the target's (1).

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 19 hunks across 5 file(s).

Usage: python patches/apply_spec_sampling_042.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'common_sampler_sample_and_accept_n_spec'

EDITS = {
    os.path.join(tree, "common", "sampling.cpp"): [
        ('''#include <cstring>
#include <unordered_map>
''',
         '''#include <cstring>
#include <mutex>
#include <unordered_map>
'''),
        ('''
uint32_t common_sampler_get_seed(const struct common_sampler * gsmpl) {
''',
         '''
bool common_sampler_spec_supported(const struct common_sampler * gsmpl) {
    if (!gsmpl || gsmpl->params.temp <= 0.0f || gsmpl->params.mirostat != 0 || gsmpl->params.backend_sampling) {
        return false;
    }

    // the chain ends in dist, and what comes before it is a function of the logits and the accepted tokens (xtc's own
    // draws as well: they are independent of the draft)
    static const char * known[] = {
        "logit-bias", "penalties", "dry", "top-n-sigma", "top-k", "typical", "top-p", "min-p", "xtc", "temp", "temp-ext",
    };

    const int n = llama_sampler_chain_n(gsmpl->chain);
    if (n < 1 || std::strcmp(llama_sampler_name(llama_sampler_chain_get(gsmpl->chain, n - 1)), "dist") != 0) {
        return false;
    }
    for (int i = 0; i + 1 < n; ++i) {
        const char * name = llama_sampler_name(llama_sampler_chain_get(gsmpl->chain, i));
        if (name[0] == '?') {
            continue; // a sampler its parameters turned off: an empty one in its place
        }
        bool ok = false;
        for (const char * k : known) {
            ok = ok || std::strcmp(name, k) == 0;
        }
        if (!ok) {
            return false;
        }
    }

    return true;
}

// the distribution common_sampler_sample draws from at idx: the reasoning budget, the chain's samplers but its last
// (dist), then dist's softmax; cur_p holds it, its p normalized as dist leaves them
static void spec_target_probs(struct common_sampler * gsmpl, struct llama_context * ctx, int idx) {
    gsmpl->set_logits(ctx, idx);

    auto & cur_p = gsmpl->cur_p;

    llama_sampler_apply(gsmpl->rbudget, &cur_p);

    const int n = llama_sampler_chain_n(gsmpl->chain);
    for (int i = 0; i + 1 < n; ++i) {
        llama_sampler * smpl = llama_sampler_chain_get(gsmpl->chain, i);
        if (smpl->iface->apply != nullptr) {
            llama_sampler_apply(smpl, &cur_p);
        }
    }

    GGML_ASSERT(cur_p.size > 0 && "no candidates left to sample from - check your sampling configuration");

    float max_l = cur_p.data[0].logit;
    for (size_t i = 1; i < cur_p.size; ++i) {
        max_l = std::max(max_l, cur_p.data[i].logit);
    }

    double sum = 0.0;
    for (size_t i = 0; i < cur_p.size; ++i) {
        const float e = expf(cur_p.data[i].logit - max_l);
        cur_p.data[i].p = e;
        sum += e;
    }
    for (size_t i = 0; i < cur_p.size; ++i) {
        cur_p.data[i].p /= sum;
    }

    cur_p.selected = -1;
}

// an index of cur_p drawn with probabilities proportional to w (non-negative, not all zero)
static size_t spec_draw(const std::vector<double> & w, std::mt19937 & rng) {
    double sum = 0.0;
    for (const double x : w) {
        sum += x;
    }

    std::uniform_real_distribution<double> unif(0.0, 1.0);
    const double u = unif(rng) * sum;

    double cum  = 0.0;
    size_t last = 0;
    for (size_t i = 0; i < w.size(); ++i) {
        if (w[i] > 0.0) {
            cum += w[i];
            last = i;
            if (cum > u) {
                return i;
            }
        }
    }

    return last;
}

static double spec_q_of(const std::vector<llama_token_data> & q, llama_token id) {
    for (const auto & e : q) {
        if (e.id == id) {
            return e.p;
        }
    }
    return 0.0;
}

llama_token common_sampler_spec_draw_q(const llama_token_data_array * cands, float temp, int32_t top_k, float top_p, float min_p,
        float qscale, std::mt19937 & rng, std::vector<llama_token_data> & q) {
    size_t n = 0;
    while (n < cands->size && std::isfinite(cands->data[n].logit)) {
        n++;
    }
    if (top_k > 0) {
        n = std::min(n, (size_t) top_k);
    }
    GGML_ASSERT(n > 0);

    const double l0 = cands->data[0].logit;

    std::vector<double> p1(n);
    double sum1 = 0.0;
    for (size_t i = 0; i < n; ++i) {
        p1[i] = std::exp((double) cands->data[i].logit - l0);
        sum1 += p1[i];
    }

    size_t keep = n;
    if (top_p < 1.0f) {
        double cum = 0.0;
        for (size_t i = 0; i < n; ++i) {
            cum += p1[i] / sum1;
            if (cum >= top_p) {
                keep = i + 1;
                break;
            }
        }
    }
    if (min_p > 0.0f) {
        // relative to the top token's (p1[0] == 1)
        for (size_t i = 1; i < keep; ++i) {
            if (p1[i] < min_p) {
                keep = i;
                break;
            }
        }
    }

    const double t = (double) temp * std::max(qscale, 1e-3f);

    std::vector<double> w(keep);
    double sum = 0.0;
    for (size_t i = 0; i < keep; ++i) {
        w[i] = std::exp(((double) cands->data[i].logit - l0) / t);
        sum += w[i];
    }

    q.resize(keep);
    for (size_t i = 0; i < keep; ++i) {
        q[i] = { cands->data[i].id, cands->data[i].logit, (float) (w[i] / sum) };
        w[i] = q[i].p;
    }

    // drawn from q as recorded
    return q[spec_draw(w, rng)].id;
}

// one position of the verification, cur_p holding p (normalized): with a draft token x drawn from q, x accepted with
// probability min(1, p(x) / q(x)), else a draw from max(0, p - q) and the draft ends (*stop); without a draft token
// (q == nullptr), a draw from p. Returns an index into cur_p
static size_t spec_select(const llama_token_data_array & cur_p, const std::vector<llama_token_data> * q, llama_token x,
        std::mt19937 & rng, std::vector<double> & w, bool * stop) {
    w.resize(cur_p.size);
    for (size_t j = 0; j < cur_p.size; ++j) {
        w[j] = cur_p.data[j].p;
    }

    *stop = q == nullptr;
    if (q == nullptr) {
        return spec_draw(w, rng);
    }

    const double qx = spec_q_of(*q, x);

    int    jx = -1;
    double px = 0.0;
    for (size_t j = 0; j < cur_p.size; ++j) {
        if (cur_p.data[j].id == x) {
            jx = (int) j;
            px = w[j];
            break;
        }
    }

    if (qx <= 0.0) {
        // not drawn from q (no q for it): an exact match with a draw from p, which is always right
        const size_t sel = spec_draw(w, rng);
        *stop = cur_p.data[sel].id != x;
        return sel;
    }

    std::uniform_real_distribution<double> unif(0.0, 1.0);
    if (jx >= 0 && unif(rng) * qx < px) {
        return (size_t) jx;
    }

    // rejected (so p(x) < q(x)): a draw from max(0, p - q), which is zero at x
    double sum = 0.0;
    for (size_t j = 0; j < cur_p.size; ++j) {
        const double r = w[j] - spec_q_of(*q, cur_p.data[j].id);
        w[j] = r > 0.0 ? r : 0.0;
        sum += w[j];
    }
    if (!(sum > 0.0)) {
        // p and q equal to rounding: p itself
        for (size_t j = 0; j < cur_p.size; ++j) {
            w[j] = cur_p.data[j].p;
        }
    }

    *stop = true;
    return spec_draw(w, rng);
}

// STRIX_SPEC_SAMPLING_STATS=1 (measurement only): at every verified draft position, the expected acceptance
// sum_y min(p(y), q'(y)) of q' = q's support at other temperatures (q's logits / (temp * s)) and of the greedy draft
// (p of q's top token), printed every 256 first positions. A first position's numbers hold for any s; a later one's
// are conditional on the prefixes the draft actually drew.
struct spec_stats {
    static constexpr int    N_POS    = 8;
    static constexpr int    N_SCALES = 9;
    static constexpr double scales[N_SCALES] = { 0.0, 0.25, 0.4, 0.55, 0.7, 0.85, 1.0, 1.15, 1.3 };

    std::mutex mtx;
    int64_t n     [N_POS] = {};
    double  e     [N_POS][N_SCALES] = {};
    double  e_used[N_POS] = {};
    int64_t n_acc [N_POS] = {};

    static bool enabled() {
        static const bool on = getenv("STRIX_SPEC_SAMPLING_STATS") && atoi(getenv("STRIX_SPEC_SAMPLING_STATS")) != 0;
        return on;
    }

    void add(int pos, const llama_token_data_array & cur_p, const std::vector<llama_token_data> & q, float temp, bool accepted) {
        if (pos >= N_POS || q.empty()) {
            return;
        }

        std::vector<double> pq(q.size(), 0.0);
        for (size_t k = 0; k < q.size(); ++k) {
            for (size_t j = 0; j < cur_p.size; ++j) {
                if (cur_p.data[j].id == q[k].id) {
                    pq[k] = cur_p.data[j].p;
                    break;
                }
            }
        }

        size_t k_top = 0;
        for (size_t k = 1; k < q.size(); ++k) {
            if (q[k].logit > q[k_top].logit) {
                k_top = k;
            }
        }

        double es[N_SCALES];
        for (int s = 0; s < N_SCALES; ++s) {
            if (scales[s] <= 0.0) {
                es[s] = pq[k_top];
                continue;
            }
            const double t = (double) temp * scales[s];
            double sum = 0.0;
            std::vector<double> w(q.size());
            for (size_t k = 0; k < q.size(); ++k) {
                w[k] = std::exp(((double) q[k].logit - (double) q[k_top].logit) / t);
                sum += w[k];
            }
            es[s] = 0.0;
            for (size_t k = 0; k < q.size(); ++k) {
                es[s] += std::min(pq[k], w[k] / sum);
            }
        }

        double eu = 0.0;
        for (size_t k = 0; k < q.size(); ++k) {
            eu += std::min(pq[k], (double) q[k].p);
        }

        std::lock_guard<std::mutex> lock(mtx);

        n[pos]++;
        n_acc[pos] += accepted ? 1 : 0;
        e_used[pos] += eu;
        for (int s = 0; s < N_SCALES; ++s) {
            e[pos][s] += es[s];
        }

        if (pos == 0 && n[0] % 256 == 0) {
            for (int i = 0; i < N_POS && n[i] > 0; ++i) {
                std::string line;
                for (int s = 0; s < N_SCALES; ++s) {
                    line += string_format(" %s%.3f", s == 0 ? "greedy " : string_format("s%.2f ", scales[s]).c_str(), e[i][s] / n[i]);
                }
                LOG_INF("spec stats: pos %d n %6lld accepted %.3f (expected %.3f) |%s\\n", i, (long long) n[i],
                        (double) n_acc[i] / n[i], e_used[i] / n[i], line.c_str());
            }
        }
    }
};

static spec_stats g_spec_stats;

std::vector<llama_token> common_sampler_sample_and_accept_n_spec(
        struct common_sampler * gsmpl, struct llama_context * ctx, const std::vector<int> & idxs, const llama_tokens & draft,
        const std::vector<std::vector<llama_token_data>> & draft_q, std::mt19937 & rng, bool is_replay) {
    GGML_ASSERT(idxs.size() == draft.size() + 1 && "idxs.size() must be draft.size() + 1");
    GGML_ASSERT((is_replay || draft_q.size() >= draft.size()) && "every draft token needs its q");

    std::vector<llama_token> result;
    result.reserve(idxs.size());

    llama_synchronize(ctx);

    auto & cur_p = gsmpl->cur_p;

    std::vector<double> w;

    for (size_t i = 0; i < idxs.size(); ++i) {
        const bool has_draft = i < draft.size();

        if (is_replay && has_draft) {
            common_sampler_accept(gsmpl, draft[i], true);
            result.push_back(draft[i]);
            continue;
        }

        llama_token id   = LLAMA_TOKEN_NULL;
        bool        stop = true;

        {
            const auto tm = gsmpl->tm();

            spec_target_probs(gsmpl, ctx, idxs[i]);

            const size_t sel = spec_select(cur_p, has_draft ? &draft_q[i] : nullptr, has_draft ? draft[i] : LLAMA_TOKEN_NULL,
                    rng, w, &stop);

            if (has_draft && spec_stats::enabled()) {
                g_spec_stats.add((int) i, cur_p, draft_q[i], gsmpl->params.temp, !stop && cur_p.data[sel].id == draft[i]);
            }

            cur_p.selected = (int64_t) sel;
            id = cur_p.data[sel].id;
        }

        // the grammar-based rejection sampling of common_sampler_sample: a token the grammar rejects is replaced by a
        // draw from the chain applied after the grammar, which is what common_sampler_sample returns after drawing it
        if (grammar_should_apply(gsmpl)) {
            const auto tm = gsmpl->tm();

            llama_token_data       single_token_data       = { id, 1.0f, 0.0f };
            llama_token_data_array single_token_data_array = { &single_token_data, 1, -1, false };

            llama_sampler_apply(gsmpl->grmr, &single_token_data_array);

            if (single_token_data_array.data[0].logit == -INFINITY) {
                gsmpl->set_logits(ctx, idxs[i]);

                llama_sampler_apply(gsmpl->rbudget, &cur_p);
                llama_sampler_apply(gsmpl->grmr,    &cur_p);
                llama_sampler_apply(gsmpl->chain,   &cur_p);

                GGML_ASSERT(cur_p.selected != -1 && "no selected token during sampling - check your sampling configuration");

                id   = cur_p.data[cur_p.selected].id;
                stop = true;
            }
        }

        common_sampler_accept(gsmpl, id, true);

        result.push_back(id);

        if (stop || id != draft[i]) {
            break;
        }
    }

    return result;
}

uint32_t common_sampler_get_seed(const struct common_sampler * gsmpl) {
'''),
    ],
    os.path.join(tree, "common", "sampling.h"): [
        ('''
#include <string>
''',
         '''
#include <random>
#include <string>
'''),
        ('''
uint32_t common_sampler_get_seed(const struct common_sampler * gsmpl);
''',
         '''
// strixllama: speculative sampling (Leviathan et al. 2023, Chen et al. 2023). Draft token i was drawn from draft_q[i]
// (its support: id and p); it is accepted with probability min(1, p(x) / q(x)), p being the distribution the target's
// sampler chain samples from (every sampler but the final dist, then dist's softmax). A rejected token is replaced
// by a draw from max(0, p - q), normalized, and the draft ends; after a draft accepted whole, the next token is drawn
// from p. Each emitted token is distributed exactly as common_sampler_sample's (with a grammar, a token it rejects is
// resampled the way common_sampler_sample does, and the draft ends there), and the draft tokens are accepted far more
// often than by an exact match when the draft is drawn from a q close to p. The random draws come from rng.
// is_replay: the draft is tokens already accepted before a checkpoint restore - they are accepted again as they are.
//
// requires: idxs.size() == draft.size() + 1, draft_q.size() >= draft.size() unless is_replay
bool common_sampler_spec_supported(const struct common_sampler * gsmpl);

std::vector<llama_token> common_sampler_sample_and_accept_n_spec(
        struct common_sampler * gsmpl, struct llama_context * ctx, const std::vector<int> & idxs, const llama_tokens & draft,
        const std::vector<std::vector<llama_token_data>> & draft_q, std::mt19937 & rng, bool is_replay);

// strixllama: a drafter's q for speculative sampling, from its candidates (sorted, highest first, their logits): the
// target's top-k, then its top-p and min-p on their probabilities at temperature 1 (the target's chain applies them
// before its temperature), then their softmax at the target's temperature times qscale. Returns a token drawn from q;
// q receives q's support (id, the candidate's logit, p)
llama_token common_sampler_spec_draw_q(const llama_token_data_array * cands, float temp, int32_t top_k, float top_p, float min_p,
        float qscale, std::mt19937 & rng, std::vector<llama_token_data> & q);

uint32_t common_sampler_get_seed(const struct common_sampler * gsmpl);
'''),
    ],
    os.path.join(tree, "common", "speculative.cpp"): [
        ('''            n_drafting++;
            drafting[seq_id] = true;
            common_sampler_reset(smpls[seq_id].get());

            common_batch_add(batch, dp.id_last, dp.pos0, { seq_id }, true);
            if (pending_pos[seq_id] >= 0 && pending_pos[seq_id] == dp.pos0 - 1) {
''',
         '''            n_drafting++;
            drafting[seq_id] = true;
            common_sampler_reset(smpls[seq_id].get());
            if (dp.sample) {
                dp.sample->q->clear();
            }

            common_batch_add(batch, dp.id_last, dp.pos0, { seq_id }, true);
            if (pending_pos[seq_id] >= 0 && pending_pos[seq_id] == dp.pos0 - 1) {
'''),
        ('''                            common_token_to_piece(ctx_dft, cur_p->data[k].id).c_str());
                }

                // add drafted token for each sequence
                const llama_token id = cur_p->data[0].id;

                // only collect very high-confidence draft tokens
                if (cur_p->data[0].p < params.p_min) {
                    if (!even) {
''',
         '''                            common_token_to_piece(ctx_dft, cur_p->data[k].id).c_str());
                }

                // add drafted token for each sequence
                llama_token id = cur_p->data[0].id;

                // only collect very high-confidence draft tokens
                if (cur_p->data[0].p < params.p_min) {
                    if (!even) {
'''),
        ('''                    }
                }

                common_sampler_accept(smpl, id, true);

                auto & dp = dparams.at(seq_id);
                auto & result = *dp.result;

                result.push_back(id);
                if (confident[seq_id]) {
''',
         '''                    }
                }

                auto & dp = dparams.at(seq_id);
                auto & result = *dp.result;

                // strixllama: speculative sampling - the token drawn from q. Whether a step drafts at all (p_min above)
                // depends only on the tokens before it, which keeps the verification exact
                if (dp.sample) {
                    const auto & sp = *dp.sample;
                    id = common_sampler_spec_draw_q(cur_p, sp.temp, sp.top_k, sp.top_p, sp.min_p, sp.qscale, *sp.rng,
                            sp.q->emplace_back());
                }

                common_sampler_accept(smpl, id, true);

                result.push_back(id);
                if (confident[seq_id]) {
'''),
        ('''                    dparams[seq_id].result->resize(len);
                }
''',
         '''                    dparams[seq_id].result->resize(len);
                    if (dparams[seq_id].sample) {
                        dparams[seq_id].sample->q->resize(len);
                    }
                }
'''),
        ('''            }
        }

        for (llama_seq_id seq_id = 0; seq_id < (llama_seq_id) n_seq; ++seq_id) {
            auto & dp = dparams[seq_id];
            if (!dp.drafting) {
                continue;
            }

            if (dp.result->size() < (size_t) params.n_min) {
                dp.result->clear();
            }
        }
    }

    void accept(llama_seq_id seq_id, uint16_t n_accepted, bool /*is_other*/) override {
        if (seq_id < 0 || seq_id >= (llama_seq_id) n_seq) {
            return;
        }

''',
         '''            }
        }

        for (llama_seq_id seq_id = 0; seq_id < (llama_seq_id) n_seq; ++seq_id) {
            auto & dp = dparams[seq_id];
            if (!dp.drafting) {
                continue;
            }

            // strixllama: with drawn drafts and p_min, a short draft's length depends on the tokens it drew (the steps
            // after them were unconfident): dropping it for that would bias the tokens kept, so it is kept
            if (dp.result->size() < (size_t) params.n_min && !(dp.sample && params.p_min > 0.0f)) {
                dp.result->clear();
                if (dp.sample) {
                    dp.sample->q->clear();
                }
            }
        }
    }

    void accept(llama_seq_id seq_id, uint16_t n_accepted, bool /*is_other*/) override {
        if (seq_id < 0 || seq_id >= (llama_seq_id) n_seq) {
            return;
        }

'''),
    ],
    os.path.join(tree, "common", "speculative.h"): [
        ('''#include "common.h"

''',
         '''#include "common.h"

#include <random>
#include <vector>

'''),
        ('''
struct common_speculative_draft_params {
''',
         '''
// strixllama: speculative sampling (see common_sampler_sample_and_accept_n_spec). A drafter that supports it (MTP)
// draws each draft token from q - its own top candidates through the target's top-k, top-p and min-p (at temperature 1,
// as the target's chain applies them) and the target's temperature times qscale - and records q's support
struct common_speculative_sample_params {
    float   temp   = 0.0f;
    int32_t top_k  = 0;
    float   top_p  = 1.0f;
    float   min_p  = 0.0f;
    float   qscale = 1.0f;

    std::mt19937 * rng = nullptr;

    // one entry per draft token, in step with the draft
    std::vector<std::vector<llama_token_data>> * q = nullptr;
};

struct common_speculative_draft_params {
'''),
        ('''    llama_tokens * result;
};
''',
         '''    llama_tokens * result;

    // strixllama: set to draw the draft (nullptr: each step's top candidate, as before)
    const common_speculative_sample_params * sample = nullptr;
};
'''),
    ],
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''    std::mt19937 spec_synth_rng;

''',
         '''    std::mt19937 spec_synth_rng;

    // strixllama: speculative sampling (STRIX_SPEC_SAMPLING, see common_sampler_sample_and_accept_n_spec): when this
    // task's sampler allows it, the drafter draws the draft from q with spec_draft_rng and records q in spec_draft_q,
    // and the verification accepts by p / q with spec_verify_rng
    bool spec_sampling = false;
    common_speculative_sample_params spec_sample;
    std::vector<std::vector<llama_token_data>> spec_draft_q;
    std::mt19937 spec_draft_rng;
    std::mt19937 spec_verify_rng;

'''),
        ('''            spec_draft.clear();
            spec_i_batch.clear();
''',
         '''            spec_draft.clear();
            spec_draft_q.clear();
            spec_i_batch.clear();
'''),
        ('''                slot.spec_synth_rng.seed(seed);
            }
        } else {
            slot.smpl.reset();
''',
         '''                slot.spec_synth_rng.seed(seed);
            }

            // strixllama: speculative sampling, with a sampler whose distribution it can compute (temperature above 0,
            // no mirostat, the chain ending in dist); greedy decoding keeps the exact match
            {
                static const bool on = !getenv("STRIX_SPEC_SAMPLING") || atoi(getenv("STRIX_SPEC_SAMPLING")) != 0;
                static const float qscale = getenv("STRIX_SPEC_QSCALE") ? (float) atof(getenv("STRIX_SPEC_QSCALE")) : 1.0f;

                slot.spec_sampling = on && spec && common_speculative_get_synth_probs(spec.get()).empty() &&
                    common_sampler_spec_supported(slot.smpl.get());
                SLT_DBG(slot, "speculative sampling %s (chain: %s)\\n", slot.spec_sampling ? "on" : "off",
                        common_sampler_print(slot.smpl.get()).c_str());
                if (slot.spec_sampling) {
                    const uint32_t seed = task.params.sampling.seed == LLAMA_DEFAULT_SEED
                        ? std::random_device{}()
                        : task.params.sampling.seed;
                    slot.spec_draft_rng.seed(seed ^ 0x9e3779b9u);
                    slot.spec_verify_rng.seed(seed ^ 0x85ebca6bu);

                    const auto & sp = task.params.sampling;
                    slot.spec_sample.temp   = sp.temp;
                    slot.spec_sample.top_k  = sp.top_k;
                    slot.spec_sample.top_p  = sp.top_p;
                    slot.spec_sample.min_p  = sp.min_p;
                    slot.spec_sample.qscale = qscale;
                }
            }
        } else {
            slot.smpl.reset();
'''),
        ('''        int n_draft_cap = INT_MAX;
        if (spec) {
            static const std::vector<int> by_slots = [] {
                std::vector<int> v;
                const char * e = getenv("STRIX_SPEC_DRAFT_BY_SLOTS");
                for (const char * p = e; p && *p; ) {
                    v.push_back(std::max(0, atoi(p)));
                    p = strchr(p, ',');
                    p = p ? p + 1 : nullptr;
                }
                return v;
            }();
            if (!by_slots.empty()) {
                int n_gen = 0;
                for (const auto & s : slots) {
                    n_gen += s.state == SLOT_STATE_GENERATING;
                }
                if (n_gen > 0) {
                    n_draft_cap = by_slots[std::min<size_t>(n_gen, by_slots.size()) - 1];
                }
            }
        }

        // strixllama: the cells this step's answers take so far (see pool_guard_on)
        int64_t n_pool_step = 0;
        const int64_t n_spec_max = spec ? std::min<int64_t>(common_speculative_n_max(spec.get()), n_draft_cap) : 0;
''',
         '''        // A request that samples (speculative sampling, see spec_sampling) has its drafts accepted less often than a
        // greedy one - at temperature 0.7 on prose ~67% at the first position against ~86% - so a draft position pays
        // for itself less often: STRIX_SPEC_DRAFT_BY_SLOTS_SAMPLED is its table, also with one slot (unset: as greedy).
        int n_draft_cap         = INT_MAX;
        int n_draft_cap_sampled = INT_MAX;
        if (spec) {
            auto table = [](const char * name) {
                std::vector<int> v;
                const char * e = getenv(name);
                for (const char * p = e; p && *p; ) {
                    v.push_back(std::max(0, atoi(p)));
                    p = strchr(p, ',');
                    p = p ? p + 1 : nullptr;
                }
                return v;
            };
            static const std::vector<int> by_slots         = table("STRIX_SPEC_DRAFT_BY_SLOTS");
            static const std::vector<int> by_slots_sampled = table("STRIX_SPEC_DRAFT_BY_SLOTS_SAMPLED");
            int n_gen = 0;
            for (const auto & s : slots) {
                n_gen += s.state == SLOT_STATE_GENERATING;
            }
            if (n_gen > 0 && !by_slots.empty()) {
                n_draft_cap = by_slots[std::min<size_t>(n_gen, by_slots.size()) - 1];
            }
            n_draft_cap_sampled = n_gen > 0 && !by_slots_sampled.empty()
                ? by_slots_sampled[std::min<size_t>(n_gen, by_slots_sampled.size()) - 1]
                : n_draft_cap;
        }

        // strixllama: the cells this step's answers take so far (see pool_guard_on)
        int64_t n_pool_step = 0;
        const int64_t n_spec_max = spec ? std::min<int64_t>(common_speculative_n_max(spec.get()), std::max(n_draft_cap, n_draft_cap_sampled)) : 0;
'''),
        ('''                const int n_draft_max = std::min(slot.get_n_draft_max(), n_draft_cap);
''',
         '''                const int n_draft_max = std::min(slot.get_n_draft_max(), slot.spec_sampling ? n_draft_cap_sampled : n_draft_cap);
'''),
        ('''                        };

''',
         '''                        };

                        slot.spec_draft_q.clear();
                        if (slot.spec_sampling) {
                            slot.spec_sample.rng = &slot.spec_draft_rng;
                            slot.spec_sample.q   = &slot.spec_draft_q;
                            common_speculative_get_draft_params(spec.get(), slot.id).sample = &slot.spec_sample;
                        }

'''),
        ('''                auto accepted = synth_probs.empty()
                    ? common_sampler_sample_and_accept_n(slot.smpl.get(), slot.ctx_tgt, slot.spec_i_batch, slot.spec_draft)
                    : server_sample_and_accept_synth(
                            slot.smpl.get(), slot.ctx_tgt, slot.spec_i_batch, slot.spec_draft,
                            synth_probs, slot.spec_synth_rng, slot.spec_is_replay);
''',
         '''                // strixllama: a draft drawn from q (every token with its q) is verified by speculative sampling, as is a
                // replay of one; a draft without q (another drafter's) by an exact match
                const bool use_spec = synth_probs.empty() && slot.spec_sampling &&
                    (slot.spec_is_replay || slot.spec_draft_q.size() >= slot.spec_draft.size());
                auto accepted = !synth_probs.empty()
                    ? server_sample_and_accept_synth(
                            slot.smpl.get(), slot.ctx_tgt, slot.spec_i_batch, slot.spec_draft,
                            synth_probs, slot.spec_synth_rng, slot.spec_is_replay)
                    : use_spec
                    ? common_sampler_sample_and_accept_n_spec(slot.smpl.get(), slot.ctx_tgt, slot.spec_i_batch, slot.spec_draft,
                            slot.spec_draft_q, slot.spec_verify_rng, slot.spec_is_replay)
                    : common_sampler_sample_and_accept_n(slot.smpl.get(), slot.ctx_tgt, slot.spec_i_batch, slot.spec_draft);
                slot.spec_draft_q.clear();
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
