#!/usr/bin/env python3
"""The op-class ablation can drop a class without a zero fill, and select by output width.

STRIX_SKIP_OPS replaced each skipped node by a zero fill, which is itself a dispatch, so what a class of small kernels costs inside a HIP graph could not be measured. STRIX_SKIP_NOFILL=1 skips the node outright (output garbage), and OP@ne0 selects the nodes of an op whose ne[0] is ne0 (MUL_MAT@320: the hyper-connection down projections). Measurement only; nothing changes unless STRIX_SKIP_OPS is set.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 2 hunks across 1 file(s).

Usage: python patches/apply_skip_ops_shape_035.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_SKIP_NOFILL'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ggml-cuda.cu"): [
        ('''    for (const auto & w : wanted) {
        const size_t colon = w.find(':');
''',
         '''    for (const auto & w : wanted) {
        // DEV: OP@ne0 skips only the nodes of that op whose ne[0] is ne0 (e.g. MUL_MAT@320)
        const size_t at = w.find('@');
        if (at != std::string::npos) {
            if (w.compare(0, at, op) == 0 && atoll(w.c_str() + at + 1) == node->ne[0]) { return true; }
            continue;
        }
        const size_t colon = w.find(':');
'''),
        ('''                    CUDA_CHECK(cudaMemsetAsync(node->data, 0, ggml_nbytes(node), cuda_ctx->stream()));
''',
         '''                    // STRIX_SKIP_NOFILL=1: no zero fill either, so the dispatch itself goes (its cost with it)
                    static const bool nofill = getenv("STRIX_SKIP_NOFILL") && atoi(getenv("STRIX_SKIP_NOFILL"));
                    if (!nofill) {
                        CUDA_CHECK(cudaMemsetAsync(node->data, 0, ggml_nbytes(node), cuda_ctx->stream()));
                    }
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
