#!/usr/bin/env python3
"""0.5.4: text after an image keeps the compact sparse-attention inputs (issue #13).

Once a conversation held an image, every later ubatch of it took the dense sparse-attention inputs: a KQ mask and a
per-block bias over n_kv x n_tokens filled on the host, and since issue #2 a ubatch held to n_kv x n_tokens <= 2^27
(about 800 tokens at 170K cells). Prefill of the text after one image fell as the context grew: 1,465 t/s before the
image, 224 t/s at 140K, 147K tokens in 364 s against 107 s without the image (issue #13).
qsa_scalar_visibility (from upstream) refused the compact inputs whenever an image cell was in the window. For a text
ubatch whose conversation's image cells all lie before its first position, every image cell is visible to every query
by position alone (the M-RoPE rule only orders cells that share the query's position), and set_input_qsa already ranks
the cells and fills the compact metadata in that rank space - the path the MTP draft context takes after every image.
Such a ubatch now keeps the compact inputs; only an image cell at or after the ubatch's first position rules them out.
The 2^27 bound applies only to batches that still take the dense inputs: an image (embeddings without tokens), several
conversations, or text that an image cell does not wholly precede. The MTP draft's catch-up batches (tokens with
embeddings) were held to it for nothing and are not any more. STRIX_IMAGE_TEXT_COMPACT=0 restores the dense inputs.
Measured, 147K tokens with a 1920x1080 image after the first 45K, MTP off: 404 -> 1,259 t/s (text alone 1,351), the
last interval 224 -> 1,260; MTP on 1,219. Against the dense inputs on the same build: a question about the image 75K
tokens back answered the same, and a 300-token greedy continuation after an image identical token for token (chosen
log-probabilities within 0.0013 on average).

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 3 hunks across 1 file(s).

Usage: python patches/apply_image_text_compact_054.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'hybrid_idx_image_text_compact'

EDITS = {
    os.path.join(tree, "src", "llama-memory-hybrid-idx.cpp"): [
        ('''
llama_memory_context_ptr llama_memory_hybrid_idx::init_batch(llama_batch_allocr & balloc, uint32_t n_ubatch, bool embd_all) {
''',
         '''
// strixllama (issue #13): a text ubatch of one conversation that holds images keeps the compact sparse-attention
// inputs when every image cell of the conversation lies before the ubatch's first position: such a cell is visible to
// every query by its position alone (the M-RoPE rule only orders cells that share the query's position), and
// set_input_qsa ranks the cells and fills the compact metadata in that rank space, as it does for the MTP draft after
// an image. It used to take the dense inputs for the rest of the conversation - a mask and a bias over n_kv x n_tokens
// built on the host, its ubatch held to 2^27 cell-token pairs - and prefill after one image fell from ~1,500 to
// ~200 t/s at 170K. STRIX_IMAGE_TEXT_COMPACT=0: the dense inputs again.
static bool hybrid_idx_image_text_compact() {
    static const bool on = [] {
        const char * e = getenv("STRIX_IMAGE_TEXT_COMPACT");
        return !e || atoi(e) != 0;
    }();
    return on;
}

// whether a cell of `seq` holds an image token (its 2-D position differs from its 1-D one) at or after `pmin`
static bool hybrid_idx_image_from(const llama_kv_cells & cells, llama_seq_id seq, llama_pos pmin, uint32_t off, uint32_t n) {
    for (uint32_t j = off; j < off + n && j < cells.size(); ++j) {
        if (!cells.is_empty(j) && cells.seq_has(j, seq) && cells.pos_get(j) >= pmin &&
                cells.ext_get(j).is_2d_gt(cells.pos_get(j), cells.pos_get(j))) {
            return true;
        }
    }
    return false;
}

llama_memory_context_ptr llama_memory_hybrid_idx::init_batch(llama_batch_allocr & balloc, uint32_t n_ubatch, bool embd_all) {
'''),
        ('''    if (kb_dup) {
''',
         '''    // strixllama (issue #13): only batches that take the dense inputs are bound - an image (embeddings without tokens),
    // several conversations, or text that an image cell does not wholly precede. One conversation's text after its
    // images takes the compact inputs (qsa_scalar_visibility), and so does the MTP draft head (tokens with embeddings),
    // whose catch-up after an image was held to the bound for nothing.
    bool dense_batch = kb_dup;
    if (dense_batch && hybrid_idx_image_text_compact()) {
        const llama_batch & b = balloc.get_batch();
        bool one_text_seq = b.token != nullptr && b.n_tokens > 0 && b.pos && b.n_seq_id && b.seq_id &&
                b.n_seq_id[0] == 1 && b.seq_id[0][0] >= 0 && b.seq_id[0][0] < LLAMA_MAX_SEQ;
        llama_pos pmin = one_text_seq ? b.pos[0] : 0;
        for (int32_t i = 0; one_text_seq && i < b.n_tokens; ++i) {
            one_text_seq = b.n_seq_id[i] == 1 && b.seq_id[i][0] == b.seq_id[0][0];
            pmin = std::min(pmin, b.pos[i]);
        }
        if (one_text_seq) {
            const auto & cells = get_mem_idx()->get_cells(b.seq_id[0][0]);
            dense_batch = hybrid_idx_image_from(cells, b.seq_id[0][0], pmin, 0, cells.size());
        }
    }
    if (dense_batch) {
'''),
        ('''        for (uint32_t j=off;!runs && j<off+get_idx()->get_n_kv();++j) {
            if (!cells.is_empty(j) && (cells.seq_get_all(j) & seqs).any() && cells.ext_get(j).is_2d_gt(cells.pos_get(j),cells.pos_get(j))) { return false; }
''',
         '''        // strixllama (issue #13): an image cell before every query of this text ubatch is visible to all of them by its
        // position alone, and set_input_qsa ranks the cells for the compact metadata; only one at or after the
        // ubatch's first position needs the dense inputs (see hybrid_idx_image_text_compact)
        const bool text_compact=hybrid_idx_image_text_compact();
        llama_pos pmin=ubatch.pos[0];
        for (uint32_t i=1;text_compact && i<ubatch.n_tokens;++i) { pmin=std::min(pmin,ubatch.pos[i]); }
        for (uint32_t j=off;!runs && j<off+get_idx()->get_n_kv();++j) {
            if (!cells.is_empty(j) && (cells.seq_get_all(j) & seqs).any() && cells.ext_get(j).is_2d_gt(cells.pos_get(j),cells.pos_get(j)) &&
                    (!text_compact || cells.pos_get(j)>=pmin)) { return false; }
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
