#!/usr/bin/env python3
"""UD-Q4_K_XL's routed experts on the matrix-core GEMM: Q4_K gate/up through the fused GLU (glu3), Q5_1 down.

The tuned prefill kernels covered the expert types of UD-IQ4_XS (IQ3_S gate/up, IQ4_NL down); UD-Q4_K_XL's experts (gate/up Q4_K, down Q5_1) took the stock MMQ path, and a reader's llama-bench on Linux read pp2048 804 t/s against 1254 for IQ4_XS. glu3 now also dequantizes Q4_K (WQ 12: a quarter of a 144-byte superblock a step, the sub-block's 6-bit scale and min decoded at load time, one nibble of 16 bytes a thread) and the routed plain kernel Q5_1 (WTYPE 4: two 24-byte blocks a step, the fifth bits spread with one multiply). Q4_K_XL prefill of 9.8K tokens 982.6 -> 1234.3 t/s. Not bitwise against the stock path (BF16 dequantized weights instead of Q8_1 activations): paired perplexity 40 chunks of 8192 +0.84% (t = 1.2, lower in 17 of 40), 80 chunks of 4096 -0.05% (t = -0.6). IQ4_XS is untouched (bitwise). STRIX_MMB_KQ=0: the stock path.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 20 hunks across 1 file(s).

Usage: python patches/apply_mmb_kq_042.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'mmb_dq_row48'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmb.cu"): [
        ('''            out[2*w] = mmb_pack2(e0, e1); out[2*w + 1] = mmb_pack2(e2, e3);
        }
''',
         '''            out[2*w] = mmb_pack2(e0, e1); out[2*w + 1] = mmb_pack2(e2, e3);
        }
    }
}

// strixllama: dequantize one weight row's two consecutive Q5_1 blocks (48 bytes: d0 m0 qh0 qs0[16] d1 m1 qh1 qs1[16])
// into 64 bf16 in LDS. Weight j of a block is (qs[j] & 15 | bit j of qh << 4) * d + m and weight j + 16 is
// (qs[j] >> 4 | bit j + 16 of qh << 4) * d + m, as dequantize_row_q5_1 (one rounding: an fma). Four high bits go to
// bit 4 of four bytes with one multiply: b * 0x00204081 puts bit i of b at bit 8i, nothing overlapping.
__device__ __forceinline__ void mmb_dq_row48(const uint4 w0, const uint4 w1, const uint4 w2, uint32_t * arow) {
    const uint32_t ws[12] = {w0.x, w0.y, w0.z, w0.w, w1.x, w1.y, w1.z, w1.w, w2.x, w2.y, w2.z, w2.w};
#pragma unroll
    for (int blk = 0; blk < 2; ++blk) {
        const uint32_t * b = ws + 6 * blk;
        const float d = mmb_h2f((uint16_t)(b[0] & 0xffff)), m = mmb_h2f((uint16_t)(b[0] >> 16));
        const uint32_t qh = b[1];
        uint32_t * out = arow + blk * 16;
#pragma unroll
        for (int w = 0; w < 4; ++w) {
            const uint32_t v  = b[2 + w];
            const uint32_t h0 = ((((qh >> (4 * w)) & 0xfu) * 0x00204081u) & 0x01010101u) << 4;
            const uint32_t h1 = ((((qh >> (16 + 4 * w)) & 0xfu) * 0x00204081u) & 0x01010101u) << 4;
            const uint32_t x0 = (v & 0x0f0f0f0fu) | h0, x1 = ((v >> 4) & 0x0f0f0f0fu) | h1;
            float a[4], c[4];
#pragma unroll
            for (int k = 0; k < 4; ++k) {
                a[k] = fmaf((float)((x0 >> (8 * k)) & 0xffu), d, m);
                c[k] = fmaf((float)((x1 >> (8 * k)) & 0xffu), d, m);
            }
            out[2*w] = mmb_pack2(a[0], a[1]); out[2*w + 1] = mmb_pack2(a[2], a[3]);
            out[8 + 2*w] = mmb_pack2(c[0], c[1]); out[8 + 2*w + 1] = mmb_pack2(c[2], c[3]);
        }
'''),
        ('''                    a0[i] = *(const uint4 *)(p); a1[i] = *(const uint4 *)(p + 16); a3[i] = *(const uint4 *)(p + 32); a4[i] = *(const uint4 *)(p + 48); a2[i] = *(const uint32_t *)(p + 64); }
                else { const uint4 * p = (const uint4 *)(Wbase + (size_t)row * wrow_bytes + (size_t)ks * 128);
''',
         '''                    a0[i] = *(const uint4 *)(p); a1[i] = *(const uint4 *)(p + 16); a3[i] = *(const uint4 *)(p + 32); a4[i] = *(const uint4 *)(p + 48); a2[i] = *(const uint32_t *)(p + 64); }
                else if constexpr (WTYPE == 4) { const uint8_t * p = Wbase + (size_t)row * wrow_bytes + (size_t)ks * 48;
                    a0[i] = *(const uint4 *)(p); a1[i] = *(const uint4 *)(p + 16); a3[i] = *(const uint4 *)(p + 32); }
                else { const uint4 * p = (const uint4 *)(Wbase + (size_t)row * wrow_bytes + (size_t)ks * 128);
'''),
        ('''            else if constexpr (WTYPE == 1) mmb_dq_row68(a0[i], a1[i], a3[i], a4[i], a2[i], (uint32_t *)(As + row * MMB_LDS_STRIDE));
            else { uint4 * d = (uint4 *)(As + row * MMB_LDS_STRIDE); d[0] = a0[i]; d[1] = a1[i]; d[2] = a3[i]; d[3] = a4[i]; d[4] = a5[i]; d[5] = a6[i]; d[6] = a7[i]; d[7] = a8[i]; } } }
''',
         '''            else if constexpr (WTYPE == 1) mmb_dq_row68(a0[i], a1[i], a3[i], a4[i], a2[i], (uint32_t *)(As + row * MMB_LDS_STRIDE));
            else if constexpr (WTYPE == 4) mmb_dq_row48(a0[i], a1[i], a3[i], (uint32_t *)(As + row * MMB_LDS_STRIDE));
            else { uint4 * d = (uint4 *)(As + row * MMB_LDS_STRIDE); d[0] = a0[i]; d[1] = a1[i]; d[2] = a3[i]; d[3] = a4[i]; d[4] = a5[i]; d[5] = a6[i]; d[6] = a7[i]; d[7] = a8[i]; } } }
'''),
        ('''template <int BM, int BN, int WTM, int WTN>
''',
         '''template <int BM, int BN, int WTM, int WTN, int WTYPE = 0>
'''),
        ('''    const size_t wrow_bytes = (size_t)(K / 32) * 18;
    mmb_tile_gemm<BM, BN, WTM, WTN, 0, true>(W + (size_t)e * expert_bytes + (size_t)m0 * wrow_bytes, wrow_bytes, M - m0, Xh, K,
''',
         '''    const size_t wrow_bytes = (size_t)(K / 32) * (WTYPE == 4 ? 24 : 18);
    mmb_tile_gemm<BM, BN, WTM, WTN, WTYPE, true>(W + (size_t)e * expert_bytes + (size_t)m0 * wrow_bytes, wrow_bytes, M - m0, Xh, K,
'''),
        ('''template <int BN, int WTM, int WTN, typename XRowFn, typename DRowFn>
''',
         '''template <int BN, int WTM, int WTN, int WQ, typename XRowFn, typename DRowFn>
'''),
        ('''    raw3 rg, ru;
''',
         '''    // strixllama: Q4_K (WQ 12). Quarter q of a superblock is sub-blocks 2q (the low nibbles of qs[32q..32q + 31]) and
    // 2q + 1 (their high nibbles), so this thread's 16 weights are one nibble of 16 bytes: half ph picks the nibble and
    // the sub-block, tid & 1 the bytes. Its scale and min (6 bits each, get_scale_min_k4) are decoded at load time.
    struct raw4 { uint4 qs; uint32_t dm; uint32_t sm; };
    std::conditional_t<WQ == 12, raw4, raw3> rg, ru;
    const uint32_t k_qs = ro + 16 + 16 * (uint32_t) (tid & 1);
    auto ld4 = [&](const uint8_t * __restrict__ sb, const int q, raw4 & r) __attribute__((always_inline)) {
        r.dm = *(const uint32_t *)(sb + ro);
        const uint8_t * sc = sb + ro + 4;
        const int j = 2 * q + ph;
        uint32_t a, m;
        if (j < 4) { a = sc[j] & 63; m = sc[j + 4] & 63; }
        else       { a = (sc[j + 4] & 0xf) | ((sc[j - 4] >> 6) << 4); m = (sc[j + 4] >> 4) | ((sc[j] >> 6) << 4); }
        r.sm = a | (m << 8);
        r.qs = *(const uint4 *)((sb + 32 * q) + k_qs);
    };
    auto dq4 = [&](const raw4 & r, uint32_t * arow) __attribute__((always_inline)) {
        const float d1 = mmb_h2f((uint16_t)(r.dm & 0xffff)) * (float)(r.sm & 0xff);
        const float m1 = mmb_h2f((uint16_t)(r.dm >> 16)) * (float)(r.sm >> 8);
        const uint32_t qs[4] = {r.qs.x, r.qs.y, r.qs.z, r.qs.w};
        uint32_t * out = arow + (32 * ph + 16 * (tid & 1)) / 2;
#pragma unroll
        for (int w = 0; w < 4; ++w) {
            const uint32_t x = (qs[w] >> (4 * ph)) & 0x0f0f0f0fu;
            float a[4];
#pragma unroll
            for (int k = 0; k < 4; ++k) { a[k] = fmaf((float)((x >> (8 * k)) & 0xffu), d1, -m1); }
            out[2*w] = mmb_pack2(a[0], a[1]); out[2*w + 1] = mmb_pack2(a[2], a[3]);
        }
    };
'''),
        ('''        const size_t sbo = (size_t)(ks >> 2) * 110;
        ld3(Wg + sbo, ks & 3, rg);
        ld3(Wu + sbo, ks & 3, ru);
''',
         '''        const size_t sbo = (size_t)(ks >> 2) * (WQ == 12 ? 144 : 110);
        if constexpr (WQ == 12) { ld4(Wg + sbo, ks & 3, rg); ld4(Wu + sbo, ks & 3, ru); }
        else                    { ld3(Wg + sbo, ks & 3, rg); ld3(Wu + sbo, ks & 3, ru); }
'''),
        ('''        dq3(rg, agr); dq3(ru, aur);
''',
         '''        if constexpr (WQ == 12) { dq4(rg, agr); dq4(ru, aur); }
        else                    { dq3(rg, agr); dq3(ru, aur); }
'''),
        ('''template <int BN, int WTM, int WTN>
''',
         '''template <int BN, int WTM, int WTN, int WQ = 3>
'''),
        ('''    for (int i = threadIdx.x; i < 512; i += MMB_NT) {
''',
         '''    for (int i = threadIdx.x; WQ == 3 && i < 512; i += MMB_NT) {
'''),
        ('''    const uint32_t wrow_bytes = (uint32_t)(K / 256) * 110;
    mmb_tile_gemm_glu3<BN, WTM, WTN>(Wg + (size_t)e * expert_bytes + (size_t)m0 * wrow_bytes, Wu + (size_t)e * expert_bytes + (size_t)m0 * wrow_bytes, wrow_bytes, Xh, K,
''',
         '''    const uint32_t wrow_bytes = (uint32_t)(K / 256) * (WQ == 12 ? 144 : 110);
    mmb_tile_gemm_glu3<BN, WTM, WTN, WQ>(Wg + (size_t)e * expert_bytes + (size_t)m0 * wrow_bytes, Wu + (size_t)e * expert_bytes + (size_t)m0 * wrow_bytes, wrow_bytes, Xh, K,
'''),
        ('''
bool ggml_cuda_mmb_supported_mmid(const ggml_tensor * src0, const ggml_tensor * src1, const ggml_tensor * ids, const ggml_tensor * dst, bool allow_iq3s) {
''',
         '''
// strixllama: UD-Q4_K_XL's experts - gate/up Q4_K (through the fused GLU only) and down Q5_1. STRIX_MMB_KQ=0 sends
// them back to the stock MMQ path
static bool mmb_kq_enabled() {
    static const bool e = !getenv("STRIX_MMB_KQ") || atoi(getenv("STRIX_MMB_KQ")) != 0;
    return e;
}

bool ggml_cuda_mmb_supported_mmid(const ggml_tensor * src0, const ggml_tensor * src1, const ggml_tensor * ids, const ggml_tensor * dst, bool allow_iq3s) {
'''),
        ('''    if ((src0->type != GGML_TYPE_IQ4_NL && !iq3s) || src1->type != GGML_TYPE_F32 || dst->type != GGML_TYPE_F32 || ids->type != GGML_TYPE_I32) return false;
''',
         '''    const bool q4k  = allow_iq3s && mmb_kq_enabled() && src0->type == GGML_TYPE_Q4_K;
    const bool q51  = mmb_kq_enabled() && src0->type == GGML_TYPE_Q5_1;
    if ((src0->type != GGML_TYPE_IQ4_NL && !iq3s && !q4k && !q51) || src1->type != GGML_TYPE_F32 || dst->type != GGML_TYPE_F32 || ids->type != GGML_TYPE_I32) return false;
'''),
        ('''    if (iq3s && K % 256 != 0) return false;
''',
         '''    if ((iq3s || q4k) && K % 256 != 0) return false;
'''),
        ('''    mmb_routed_kernel<128, BN, 32, 64><<<gbig, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_big.get(), M, K);
    mmb_routed_kernel<128, BN_SMALL, 32, 16><<<gsmall, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_small.get(), M, K);
''',
         '''    if (src0->type == GGML_TYPE_Q5_1) {
        mmb_routed_kernel<128, BN, 32, 64, 4><<<gbig, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_big.get(), M, K);
        mmb_routed_kernel<128, BN_SMALL, 32, 16, 4><<<gsmall, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_small.get(), M, K);
    } else {
        mmb_routed_kernel<128, BN, 32, 64><<<gbig, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_big.get(), M, K);
        mmb_routed_kernel<128, BN_SMALL, 32, 16><<<gsmall, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_small.get(), M, K);
    }
'''),
        ('''    if (gw->type != GGML_TYPE_IQ4_NL && gw->type != GGML_TYPE_IQ3_S) return false;
''',
         '''    if (gw->type != GGML_TYPE_IQ4_NL && gw->type != GGML_TYPE_IQ3_S && gw->type != GGML_TYPE_Q4_K) return false;
'''),
        ('''    const bool use3 = iq3s && glu3;
''',
         '''    const bool q4k = gw->type == GGML_TYPE_Q4_K;   // glu3 only: the older kernel has no Q4_K
    const bool use3 = (iq3s && glu3) || q4k;
'''),
        ('''    static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "MMB_GLU fused gate/up+swiglu: M=%d K=%d rows=%d store_f32=%d type=%s\\n", M, K, n_rows, (int) store_f32, iq3s ? "IQ3_S" : "IQ4_NL");
''',
         '''    static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "MMB_GLU fused gate/up+swiglu: M=%d K=%d rows=%d store_f32=%d type=%s\\n", M, K, n_rows, (int) store_f32, ggml_type_name(gw->type));
'''),
        ('''    if (use3) {
''',
         '''    if (use3 && q4k) {
        GGML_ASSERT((size_t) n_rows_x * K * 2 < ((size_t) 1 << 32));   // glu3's 32-bit activation offsets
        mmb_routed_glu3_kernel<BN, 32, 32, 12><<<gbig, MMB_NT, 0, stream>>>(Wg, Wu, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_big.get(), M, K);
        mmb_routed_glu3_kernel<BN_SMALL, 16, 16, 12><<<gsmall, MMB_NT, 0, stream>>>(Wg, Wu, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_small.get(), M, K);
    } else if (use3) {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
