#!/usr/bin/env python3
"""IndexShare for the MTP draft, and a draft catch-up that only stores.

A draft step of the QSA MTP layer read the draft's whole cache densely (0.9 ms at 86K, 2.5 ms at 212K, three steps a pass). As SGLang/TRT-LLM do for DeepSeek-V3.2 MTP, a catch-up runs the layer's indexer and keeps each position's selection (llama_memory_hybrid_idx::share_sel, a ring of rows per sequence); a draft step then attends to the latest kept selection plus the cells of every position since, through the decode gather. Unlike the reference, a catch-up runs the indexer only when the latest selection is more than LLAMA_MTP_INDEX_SHARE_REFRESH (32) positions behind, and only on views of LLAMA_MTP_INDEX_SHARE_MIN_KV (32K) cells or more; a draft loop reuses a selection at most share_max_gap (48) positions old. A ubatch of the draft without outputs (a prompt, the catch-up after a verify) now stores K, V and the indexer keys and builds no query, attention or wo: nothing reads them (LLAMA_MTP_STORE_ONLY=0 restores them). Measured 2026-09-28 per speculative pass: 86K 79.75 -> 76.90 ms, 212K 93.70 -> 87.60 ms at the same acceptance; the store-only catch-up alone: 2.3K 66.2 -> 65.0 ms with byte-identical text. LLAMA_MTP_INDEX_SHARE=1 turns IndexShare on (the manager sets it).

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 32 hunks across 10 file(s).

Usage: python patches/apply_mtp_index_share_031.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'share_capture_due'

EDITS = {
    os.path.join(tree, "src", "llama-memory-hybrid-idx.h"): [
        ('''    bool          kb_pos_dup() const;


private:
''',
         '''    bool          kb_pos_dup() const;

    // strixllama: IndexShare for a QSA MTP draft context (LLAMA_MTP_INDEX_SHARE=1, llama_set_mtp_share_reuse). A catch-up
    // that runs the indexer keeps the sparse-attention selection of the positions it decodes in a ring of share_ring rows
    // per sequence (row seq*share_ring + pos % share_ring). A draft step then attends to the latest selection kept before
    // it plus every cell of the positions since, instead of running the indexer; a catch-up runs it again only when that
    // selection is more than a refresh distance behind. A row holds absolute cell + 1 for each selected cell (0 = none), so
    // it survives the graph's view of the cache moving; whatever drops, moves or rewrites a sequence's cells forgets its rows.
    //   share_sel F32 [share_width, n_seq_max*share_ring + 2]: the rows, then a scratch row and an all-zero row
    // a draft step's extra columns (cells of the positions after the reused selection) and the widest gap it may cover:
    // the rest is room for 16 draft positions
    static constexpr int32_t share_extra   = 64;
    static constexpr int32_t share_max_gap = share_extra - 16;
    ggml_tensor * share_sel()   const { return share_t; }
    int64_t       share_width() const { return share_w; }
    llama_seq_id  share_n_seqs() const { return (llama_seq_id) share_n_seq; }
    uint32_t      share_ring_len() const { return share_ring; }
    int32_t       share_row(llama_seq_id seq_id, llama_pos pos) const;
    int32_t       share_scratch_row() const;
    int32_t       share_none_row() const;
    void          share_note(llama_seq_id seq_id, llama_pos pos) const;   // a graph being set up captures (seq_id, pos)
    bool          share_ready(llama_seq_id seq_id, llama_pos pos) const;  // a selection is kept for exactly pos
    llama_pos     share_latest(llama_seq_id seq_id, llama_pos below) const;   // the latest kept position < below, -1: none
    // the absolute cells of seq_id's positions in [p0, p1], in position order
    void          share_cells(llama_seq_id seq_id, llama_pos p0, llama_pos p1, std::vector<int64_t> & out) const;
    // whether a catch-up ubatch has to run the indexer to keep selections: a sequence of it has none kept before it, or
    // the latest is more than `refresh` positions behind the ubatch's last
    bool          share_capture_due(const llama_ubatch & ubatch, llama_pos refresh) const;

private:
'''),
        ('''    bool                                 kb_dup      = false;

''',
         '''    bool                                 kb_dup      = false;

    // strixllama: IndexShare storage and bookkeeping (see share_sel)
    ggml_context_ptr                     share_ctx;
    ggml_backend_buffer_ptr              share_buf;
    ggml_tensor *                        share_t     = nullptr;
    int64_t                              share_w     = 0;
    uint32_t                             share_ring  = 8;
    uint32_t                             share_n_seq = 0;
    mutable std::vector<llama_pos>       share_pos;     // the position each ring row holds, -1 none
    // drop seq_id's rows for positions in [p0, p1) (p1 < 0: to the end); seq_id < 0: every sequence
    void share_forget(llama_seq_id seq_id, llama_pos p0 = -1, llama_pos p1 = -1) const;

'''),
        ('''    bool          kb_pos_dup() const;

private:
    const llama_memory_hybrid_idx * mem = nullptr;
''',
         '''    bool          kb_pos_dup() const;

    // strixllama: IndexShare pass-throughs (see llama_memory_hybrid_idx::share_sel)
    const llama_memory_hybrid_idx * get_mem() const { return mem; }

private:
    const llama_memory_hybrid_idx * mem = nullptr;
'''),
    ],
    os.path.join(tree, "src", "llama-memory-hybrid-idx.cpp"): [
        ('''#include <limits>
''',
         ''''''),
        ('''#include <cstdlib>

''',
         '''#include <cstdlib>
#include <limits>

'''),
        ('''        LLAMA_LOG_INFO("%s: QSA block-key cache: %zu layers, %.1f MiB\\n", __func__, kb_map.size(), bytes/1024.0/1024.0);
    }
''',
         '''        LLAMA_LOG_INFO("%s: QSA block-key cache: %zu layers, %.1f MiB\\n", __func__, kb_map.size(), bytes/1024.0/1024.0);
    }

    // strixllama: IndexShare rows for the MTP layer's selection (LLAMA_MTP_INDEX_SHARE=1), when that layer has an indexer
    {
        const char * env = getenv("LLAMA_MTP_INDEX_SHARE");
        const uint32_t il = model.hparams.n_layer();
        const int64_t  r  = il < model.hparams.n_layer_all ? (int64_t) model.hparams.dsv4_compress_ratios[il] : 0;
        if (env && atoi(env) != 0 && mem_idx && model.hparams.n_layer_nextn > 0 && il < model.hparams.n_layer_all &&
                filter_idx(il) && r > 0 && model.hparams.indexer_top_k > 0) {
            share_w     = (int64_t) model.hparams.indexer_top_k + r - 1;
            share_n_seq = n_seq_max;
            ggml_init_params params = { ggml_tensor_overhead(), nullptr, true };
            ggml_context * ctx = ggml_init(params);
            if (ctx == nullptr) {
                throw std::runtime_error("failed to create ggml context for the IndexShare rows");
            }
            share_ctx.reset(ctx);
            share_t = ggml_new_tensor_2d(ctx, GGML_TYPE_F32, share_w, (int64_t) n_seq_max*share_ring + 2);
            ggml_format_name(share_t, "cache_idx_share_l%u", il);
            ggml_backend_buffer_type_t buft = offload ? ggml_backend_dev_buffer_type(model.dev_layer(il)) : ggml_backend_cpu_buffer_type();
            ggml_backend_buffer_t buf = ggml_backend_alloc_ctx_tensors_from_buft(ctx, buft);
            if (buf == nullptr) {
                throw std::runtime_error("failed to allocate the IndexShare rows");
            }
            ggml_backend_buffer_clear(buf, 0);   // 0 = no cell, so the all-zero row selects nothing
            share_buf.reset(buf);
            share_pos.assign((size_t) n_seq_max*share_ring, -1);
            LLAMA_LOG_INFO("%s: IndexShare: %u sequences x %u positions, %lld cells a selection\\n", __func__,
                    n_seq_max, share_ring, (long long) share_w);
        }
    }
'''),
        ('''
// A block's key sits at the row of its first cell. The moves lay a sequence out in position order, so its keys
''',
         '''
int32_t llama_memory_hybrid_idx::share_row(llama_seq_id seq_id, llama_pos pos) const {
    GGML_ASSERT(seq_id >= 0 && (uint32_t) seq_id < share_n_seq && pos >= 0);
    return (int32_t) (seq_id*share_ring + (uint32_t) pos % share_ring);
}

int32_t llama_memory_hybrid_idx::share_scratch_row() const {
    return (int32_t) (share_n_seq*share_ring);
}

int32_t llama_memory_hybrid_idx::share_none_row() const {
    return (int32_t) (share_n_seq*share_ring + 1);
}

void llama_memory_hybrid_idx::share_note(llama_seq_id seq_id, llama_pos pos) const {
    if (share_t && seq_id >= 0 && (uint32_t) seq_id < share_n_seq && pos >= 0) {
        share_pos[share_row(seq_id, pos)] = pos;
    }
}

bool llama_memory_hybrid_idx::share_ready(llama_seq_id seq_id, llama_pos pos) const {
    return share_t && seq_id >= 0 && (uint32_t) seq_id < share_n_seq && pos >= 0 && share_pos[share_row(seq_id, pos)] == pos;
}

llama_pos llama_memory_hybrid_idx::share_latest(llama_seq_id seq_id, llama_pos below) const {
    if (!share_t || seq_id < 0 || (uint32_t) seq_id >= share_n_seq) {
        return -1;
    }
    llama_pos best = -1;
    for (uint32_t k = 0; k < share_ring; ++k) {
        const llama_pos p = share_pos[seq_id*share_ring + k];
        if (p >= 0 && p < below && p > best) {
            best = p;
        }
    }
    return best;
}

void llama_memory_hybrid_idx::share_cells(llama_seq_id seq_id, llama_pos p0, llama_pos p1, std::vector<int64_t> & out) const {
    out.clear();
    const auto & sp = get_mem_attn()->get_cells(seq_id).seq_pos_cells(seq_id);
    for (auto it = sp.lower_bound({ p0, 0 }); it != sp.end() && it->first <= p1; ++it) {
        out.push_back((int64_t) it->second);
    }
}

bool llama_memory_hybrid_idx::share_capture_due(const llama_ubatch & ubatch, llama_pos refresh) const {
    if (!share_t || !ubatch.seq_id || !ubatch.n_seq_id) {
        return false;
    }
    std::map<llama_seq_id, std::pair<llama_pos, llama_pos>> own;   // per sequence: its first and last position here
    for (uint32_t i = 0; i < ubatch.n_tokens; ++i) {
        const llama_seq_id s = ubatch.seq_id[i][0];
        auto & r = own.try_emplace(s, ubatch.pos[i], ubatch.pos[i]).first->second;
        r.first  = std::min(r.first,  ubatch.pos[i]);
        r.second = std::max(r.second, ubatch.pos[i]);
    }
    for (const auto & [s, r] : own) {
        const llama_pos c = share_latest(s, r.first);
        if (c < 0 || r.second - c > refresh) {
            return true;
        }
    }
    return false;
}

void llama_memory_hybrid_idx::share_forget(llama_seq_id seq_id, llama_pos p0, llama_pos p1) const {
    if (!share_t) {
        return;
    }
    const llama_pos lo = p0 < 0 ? 0 : p0;
    const llama_pos hi = p1 < 0 ? std::numeric_limits<llama_pos>::max() : p1;
    for (uint32_t s = 0; s < share_n_seq; ++s) {
        if (seq_id >= 0 && (uint32_t) seq_id != s) {
            continue;
        }
        for (uint32_t k = 0; k < share_ring; ++k) {
            llama_pos & p = share_pos[s*share_ring + k];
            if (p >= lo && p < hi) {
                p = -1;
            }
        }
    }
}

// A block's key sits at the row of its first cell. The moves lay a sequence out in position order, so its keys
'''),
        ('''    for (const auto & m : moves) {
        if (m.ordered) {
''',
         '''    for (const auto & m : moves) {
        share_forget(m.seq);   // strixllama: the IndexShare rows name the cells before the move
        if (m.ordered) {
'''),
        ('''void llama_memory_hybrid_idx::clear(bool data) {
    kb_mark_stale(-1);   // strixllama: block keys depend on positions and cell contents; rebuild them once
''',
         '''void llama_memory_hybrid_idx::clear(bool data) {
    share_forget(-1);    // strixllama: IndexShare rows name cells
    kb_mark_stale(-1);   // strixllama: block keys depend on positions and cell contents; rebuild them once
'''),
        ('''
    return get_mem_attn()->seq_rm(seq_id, p0, p1);
''',
         '''
    // strixllama: a selection names cells of its own and earlier positions, so every selection from p0 on goes (a
    // later one may name a removed cell); one of an earlier position names only cells that stay
    share_forget(seq_id, p0, -1);

    return get_mem_attn()->seq_rm(seq_id, p0, p1);
'''),
        ('''        mem_idx->seq_cp(seq_id_src, seq_id_dst, p0, p1);
    }
}

''',
         '''        mem_idx->seq_cp(seq_id_src, seq_id_dst, p0, p1);
    }

    share_forget(seq_id_dst);   // strixllama: the destination's cells changed under its IndexShare rows
}

'''),
        ('''void llama_memory_hybrid_idx::seq_keep(llama_seq_id seq_id) {
    llama_memory_hybrid::seq_keep(seq_id);
''',
         '''void llama_memory_hybrid_idx::seq_keep(llama_seq_id seq_id) {
    for (uint32_t s = 0; s < share_n_seq; ++s) {
        if ((llama_seq_id) s != seq_id) {
            share_forget((llama_seq_id) s);
        }
    }
    llama_memory_hybrid::seq_keep(seq_id);
'''),
        ('''void llama_memory_hybrid_idx::seq_add(llama_seq_id seq_id, llama_pos p0, llama_pos p1, llama_pos shift) {
    kb_mark_stale(-1);   // strixllama: block keys depend on positions; a shifted cell can be shared, so all of them
''',
         '''void llama_memory_hybrid_idx::seq_add(llama_seq_id seq_id, llama_pos p0, llama_pos p1, llama_pos shift) {
    share_forget(-1);    // strixllama: positions move under the IndexShare rows
    kb_mark_stale(-1);   // strixllama: block keys depend on positions; a shifted cell can be shared, so all of them
'''),
        ('''void llama_memory_hybrid_idx::seq_div(llama_seq_id seq_id, llama_pos p0, llama_pos p1, int d) {
    kb_mark_stale(-1);   // strixllama: block keys depend on positions; a shifted cell can be shared, so all of them
''',
         '''void llama_memory_hybrid_idx::seq_div(llama_seq_id seq_id, llama_pos p0, llama_pos p1, int d) {
    share_forget(-1);    // strixllama: positions move under the IndexShare rows
    kb_mark_stale(-1);   // strixllama: block keys depend on positions; a shifted cell can be shared, so all of them
'''),
        ('''void llama_memory_hybrid_idx::state_read(llama_io_read_i & io, llama_seq_id seq_id, llama_state_seq_flags flags) {
    kb_mark_stale(seq_id);   // strixllama: the restored cells' block keys were never written; rebuild them once
''',
         '''void llama_memory_hybrid_idx::state_read(llama_io_read_i & io, llama_seq_id seq_id, llama_state_seq_flags flags) {
    share_forget(seq_id);   // strixllama: the restored cells are not the ones the IndexShare rows name
    kb_mark_stale(seq_id);   // strixllama: the restored cells' block keys were never written; rebuild them once
'''),
        ('''    }
    return get_mem_attn()->seq_rows_set(seq_id, p0, n, src, src_rows) &&
''',
         '''    }
    share_forget(seq_id);
    return get_mem_attn()->seq_rows_set(seq_id, p0, n, src, src_rows) &&
'''),
        ('''    }
    return get_mem_attn()->seq_rows_copy(seq_src, seq_dst, p0, n) &&
''',
         '''    }
    share_forget(seq_dst);
    return get_mem_attn()->seq_rows_copy(seq_src, seq_dst, p0, n) &&
'''),
    ],
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''
llama_model_qwen4exp::graph_mtp::graph_mtp(const llama_model & model, const llm_graph_params & params) :
''',
         '''
static bool qwen4exp_pos_scalar(const llama_ubatch & ubatch);

// strixllama: IndexShare (see llama_memory_hybrid_idx::share_sel). A catch-up keeps the selections of its tokens (at most
// QWEN4EXP_SHARE_KEEP_ALL of them - a verify's catch-up, several slots at once; a prompt keeps none) when a sequence's
// latest kept selection is more than LLAMA_MTP_INDEX_SHARE_REFRESH positions behind. A draft step attends to that
// selection plus up to QWEN4EXP_SHARE_EXTRA cells of the positions since: the refresh distance, the catch-up, the draft
// steps. The gather pads the selection to 2304 cells anyway, so the extra columns are free up to 253.
static constexpr int64_t QWEN4EXP_SHARE_KEEP_ALL = 32;
static constexpr int64_t QWEN4EXP_SHARE_EXTRA    = llama_memory_hybrid_idx::share_extra;

// the refresh distance, at most the widest gap a draft step's extra columns cover
static llama_pos qwen4exp_share_refresh() {
    static const llama_pos v = getenv("LLAMA_MTP_INDEX_SHARE_REFRESH") ? atoi(getenv("LLAMA_MTP_INDEX_SHARE_REFRESH")) : 32;
    return std::max<llama_pos>(0, std::min<llama_pos>(v, llama_memory_hybrid_idx::share_max_gap));
}

// whether the MTP layer's graph for this ubatch takes part in IndexShare: the memory keeps selections, the layer is
// sparse, one stream, 1-D positions, and a view long enough to pay. A draft step's dense read of a short view costs
// next to nothing, so below LLAMA_MTP_INDEX_SHARE_MIN_KV cells nothing is kept and the draft runs as without it
// (measured 09-28: -0.6% a pass at 30K, -3.6% at 86K, -6.5% at 212K; the old every-catch-up design lost 4% at 4K).
static bool qwen4exp_mtp_share_on(const llama_memory_hybrid_idx_context * mctx_hyb, const llama_ubatch & ubatch,
        const llama_hparams & hparams) {
    static const int64_t min_kv = getenv("LLAMA_MTP_INDEX_SHARE_MIN_KV") ? atoll(getenv("LLAMA_MTP_INDEX_SHARE_MIN_KV")) : 32768;
    const auto * mem = mctx_hyb ? mctx_hyb->get_mem() : nullptr;
    const uint32_t il = hparams.n_layer();
    return mem && mem->share_sel() != nullptr && il < hparams.n_layer_all && hparams.dsv4_compress_ratios[il] > 0 &&
        mctx_hyb->get_idx() != nullptr && mctx_hyb->get_n_stream() == 1 && qwen4exp_pos_scalar(ubatch) &&
        (int64_t) mctx_hyb->get_idx()->get_n_kv() >= min_kv;
}

// whether an MTP ubatch without outputs runs the indexer to keep its tokens' selections
static bool qwen4exp_mtp_capture(const llama_memory_hybrid_idx_context * mctx_hyb, const llama_ubatch & ubatch,
        const llama_hparams & hparams) {
    if (!qwen4exp_mtp_share_on(mctx_hyb, ubatch, hparams) || (int64_t) ubatch.n_tokens > QWEN4EXP_SHARE_KEEP_ALL) {
        return false;
    }
    const int64_t r = hparams.dsv4_compress_ratios[hparams.n_layer()];
    if ((int64_t) mctx_hyb->get_idx()->get_n_kv() <= (int64_t) hparams.indexer_top_k + r - 1) {
        return false;
    }
    return mctx_hyb->get_mem()->share_capture_due(ubatch, qwen4exp_share_refresh());
}

// the choice qwen4exp_mtp_capture made when the graph was built, re-checked before the graph is reused
class llama_model_qwen4exp::llm_graph_input_mtp_capture : public llm_graph_input_i {
public:
    explicit llm_graph_input_mtp_capture(bool capture) : capture(capture) {}
    virtual ~llm_graph_input_mtp_capture() = default;

    void set_input(const llama_ubatch * ubatch) override {
        GGML_UNUSED(ubatch);
    }

    bool can_reuse(const llm_graph_params & params) override {
        const auto * m = static_cast<const llama_memory_hybrid_idx_context *>(params.mctx);
        return qwen4exp_mtp_capture(m, params.ubatch, params.hparams) == capture;
    }

    const bool capture;
};

llama_model_qwen4exp::graph_mtp::graph_mtp(const llama_model & model, const llm_graph_params & params) :
'''),
        ('''    ggml_tensor * Qcur_full = build_lora_mm(layer.wq, cur, layer.wq_s);
    cb(Qcur_full, "mtp_Qcur_full", il);

    ggml_tensor * Qcur = ggml_view_3d(ctx0, Qcur_full, n_embd_head, n_head, n_tokens,
        ggml_element_size(Qcur_full) * n_embd_head * 2,
        ggml_element_size(Qcur_full) * n_embd_head * 2 * n_head, 0);
    Qcur = build_norm(Qcur, layer.attn_q_norm, nullptr, LLM_NORM_RMS, il);
    cb(Qcur, "mtp_Qcur_normed", il);

    ggml_tensor * gate = ggml_view_3d(ctx0, Qcur_full, n_embd_head, n_head, n_tokens,
        ggml_element_size(Qcur_full) * n_embd_head * 2,
        ggml_element_size(Qcur_full) * n_embd_head * 2 * n_head,
        ggml_element_size(Qcur_full) * n_embd_head);
    gate = ggml_cont_2d(ctx0, gate, n_embd_head * n_head, n_tokens);
    cb(gate, "mtp_gate", il);
''',
         '''    // strixllama: a ubatch without outputs - the catch-up after a verify, a prompt - only fills the draft's caches: its
    // attention output reaches no output row (the FFN and the head see only those), so K, V and the indexer keys are
    // stored and the query, the attention and wo are not built (LLAMA_MTP_STORE_ONLY=0 builds them)
    static const bool store_only_on = !getenv("LLAMA_MTP_STORE_ONLY") || atoi(getenv("LLAMA_MTP_STORE_ONLY")) != 0;
    const bool store_only = store_only_on && n_outputs == 0 && inp_out_ids != nullptr;

    ggml_tensor * Qcur = nullptr;
    ggml_tensor * gate = nullptr;
    if (!store_only) {
    ggml_tensor * Qcur_full = build_lora_mm(layer.wq, cur, layer.wq_s);
    cb(Qcur_full, "mtp_Qcur_full", il);

    Qcur = ggml_view_3d(ctx0, Qcur_full, n_embd_head, n_head, n_tokens,
        ggml_element_size(Qcur_full) * n_embd_head * 2,
        ggml_element_size(Qcur_full) * n_embd_head * 2 * n_head, 0);
    Qcur = build_norm(Qcur, layer.attn_q_norm, nullptr, LLM_NORM_RMS, il);
    cb(Qcur, "mtp_Qcur_normed", il);

    gate = ggml_view_3d(ctx0, Qcur_full, n_embd_head, n_head, n_tokens,
        ggml_element_size(Qcur_full) * n_embd_head * 2,
        ggml_element_size(Qcur_full) * n_embd_head * 2 * n_head,
        ggml_element_size(Qcur_full) * n_embd_head);
    gate = ggml_cont_2d(ctx0, gate, n_embd_head * n_head, n_tokens);
    cb(gate, "mtp_gate", il);
    }
'''),
        ('''    Qcur = ggml_rope_multi(ctx0, Qcur, inp_pos, nullptr,
            n_rot, sections, rope_type, n_ctx_orig, freq_base, freq_scale,
            ext_factor, attn_factor, beta_fast, beta_slow);
    Kcur = ggml_rope_multi(ctx0, Kcur, inp_pos, nullptr,
            n_rot, sections, rope_type, n_ctx_orig, freq_base, freq_scale,
            ext_factor, attn_factor, beta_fast, beta_slow);
    cb(Qcur, "mtp_Qcur", il);
''',
         '''    if (Qcur) {
    Qcur = ggml_rope_multi(ctx0, Qcur, inp_pos, nullptr,
            n_rot, sections, rope_type, n_ctx_orig, freq_base, freq_scale,
            ext_factor, attn_factor, beta_fast, beta_slow);
    cb(Qcur, "mtp_Qcur", il);
    }
    Kcur = ggml_rope_multi(ctx0, Kcur, inp_pos, nullptr,
            n_rot, sections, rope_type, n_ctx_orig, freq_base, freq_scale,
            ext_factor, attn_factor, beta_fast, beta_slow);
'''),
        ('''        if (r > 0 && n_kv_idx > width && (int64_t) n_tokens >= mtp_min_t) {
            top_k = build_qsa_top_k(mctx_hyb, cur, inp_pos, inp_attn->get_kq_mask(), sections, il);
        } else if (r > 0) {
            build_qsa_store_k(mctx_hyb, cur, il);
        }
        if (top_k) {
            cur = build_attn_qsa(inp_attn, Qcur, Kcur, Vcur, top_k, kq_scale, il);
        } else {
            cur = build_attn(inp_attn, nullptr, nullptr, nullptr,
                    Qcur, Kcur, Vcur, nullptr, nullptr, nullptr, kq_scale, il);
        }
    } else {
    cur = build_attn(inp_attn,
            nullptr, nullptr, nullptr,
            Qcur, Kcur, Vcur, nullptr, nullptr, nullptr, kq_scale, il);
    }
    cb(cur, "mtp_attn_pregate", il);

    cur = ggml_mul(ctx0, cur, ggml_sigmoid(ctx0, gate));
    cb(cur, "mtp_attn_gated", il);

    cur = build_lora_mm(layer.wo, cur, layer.wo_s);
    cb(cur, "mtp_attn_out", il);

    if (inp_out_ids) {
        cur    = ggml_get_rows(ctx0, cur,    inp_out_ids);
''',
         '''        if (qwen4exp_mtp_share_on(mctx_hyb, ubatch, hparams) && cparams.mtp_share_reuse && !store_only) {
            // strixllama: IndexShare - a draft step attends to the selection a catch-up kept, plus the positions since
            build_qsa_store_k(mctx_hyb, cur, il);
            top_k = build_mtp_share_reuse(mctx_hyb);
        } else if (store_only) {
            // strixllama: IndexShare - a catch-up keeps its tokens' selections when the latest kept one is too far behind
            // (qwen4exp_mtp_capture); the graph fixes the choice, so an input re-checks it before the graph is reused
            const bool capture = qwen4exp_mtp_capture(mctx_hyb, ubatch, hparams);
            if (capture) {
                ggml_tensor * sel = build_qsa_top_k(mctx_hyb, cur, inp_pos, inp_attn->get_kq_mask(), sections, il);
                GGML_ASSERT(sel->ne[0] == mctx_hyb->get_mem()->share_width() && sel->ne[1] == n_tokens &&
                        sel->ne[2] == 1 && sel->ne[3] == 1);
                build_mtp_share_capture(mctx_hyb, sel);
            } else if (r > 0) {
                build_qsa_store_k(mctx_hyb, cur, il);
            }
            res->add_input(std::make_unique<llm_graph_input_mtp_capture>(capture));
        } else if (r > 0 && n_kv_idx > width && (int64_t) n_tokens >= mtp_min_t) {
            top_k = build_qsa_top_k(mctx_hyb, cur, inp_pos, inp_attn->get_kq_mask(), sections, il);
        } else if (r > 0) {
            build_qsa_store_k(mctx_hyb, cur, il);
        }
        if (store_only) {
            build_mtp_store_kv(inp_attn, Kcur, Vcur, il);
        } else if (top_k) {
            cur = build_attn_qsa(inp_attn, Qcur, Kcur, Vcur, top_k, kq_scale, il);
        } else {
            cur = build_attn(inp_attn, nullptr, nullptr, nullptr,
                    Qcur, Kcur, Vcur, nullptr, nullptr, nullptr, kq_scale, il);
        }
    } else if (store_only) {
        build_mtp_store_kv(inp_attn, Kcur, Vcur, il);
    } else {
    cur = build_attn(inp_attn,
            nullptr, nullptr, nullptr,
            Qcur, Kcur, Vcur, nullptr, nullptr, nullptr, kq_scale, il);
    }

    if (store_only) {
        // no row is an output: every node from here on is empty, so the rows are taken before the attention's place
        cur = ggml_get_rows(ctx0, cur, inp_out_ids);
    } else {
    cb(cur, "mtp_attn_pregate", il);

    cur = ggml_mul(ctx0, cur, ggml_sigmoid(ctx0, gate));
    cb(cur, "mtp_attn_gated", il);

    cur = build_lora_mm(layer.wo, cur, layer.wo_s);
    cb(cur, "mtp_attn_out", il);
    }

    if (inp_out_ids) {
        if (!store_only) {
        cur    = ggml_get_rows(ctx0, cur,    inp_out_ids);
        }
'''),
        ('''    const llama_memory_hybrid_idx_context * mctx;
};

void llama_model_qwen4exp::graph::build_qsa_store_k(
''',
         '''    const llama_memory_hybrid_idx_context * mctx;
};

class llama_model_qwen4exp::llm_graph_input_mtp_share : public llm_graph_input_i {
public:
    llm_graph_input_mtp_share(const llama_memory_hybrid_idx_context * mctx, bool reuse) : mctx(mctx), reuse(reuse) {}
    virtual ~llm_graph_input_mtp_share() = default;

    void set_input(const llama_ubatch * ubatch) override {
        const auto * mem  = mctx->get_mem();
        const auto * attn = mctx->get_attn();
        const int64_t kv_off = attn->get_kv_off();

        llama_host_write(off);
        ((float *) off->data)[0] = (float) kv_off;
        ((float *) off->data)[1] = (float) attn->get_n_kv();

        llama_host_write(rows);
        int32_t * r = (int32_t *) rows->data;
        const uint32_t n_tokens = ubatch->n_tokens;

        if (!reuse) {
            llama_host_write(dst);
            int32_t * d = (int32_t *) dst->data;
            // each sequence's last position in the ubatch
            std::map<llama_seq_id, llama_pos> last;
            std::map<llama_seq_id, uint32_t>  last_i;
            for (uint32_t i = 0; i < n_tokens; ++i) {
                const llama_seq_id s = ubatch->seq_id[i][0];
                if (!last.count(s) || ubatch->pos[i] >= last[s]) {
                    last[s]   = ubatch->pos[i];
                    last_i[s] = i;
                }
            }
            const llama_pos ring = (llama_pos) mem->share_ring_len();
            if ((int64_t) n_tokens == rows->ne[0]) {
                for (uint32_t i = 0; i < n_tokens; ++i) {
                    const llama_seq_id s = ubatch->seq_id[i][0];
                    const llama_pos    p = ubatch->pos[i];
                    r[i] = (int32_t) i;
                    // only the last `ring` positions of a sequence: two tokens must never write one row
                    if (p > last[s] - ring && s >= 0 && s < mem->share_n_seqs()) {
                        d[i] = mem->share_row(s, p);
                        mem->share_note(s, p);
                    } else {
                        d[i] = mem->share_scratch_row();
                    }
                }
            } else {
                int64_t k = 0;
                for (const auto & [s, i] : last_i) {
                    if (k >= rows->ne[0]) {
                        break;
                    }
                    r[k] = (int32_t) i;
                    if (s >= 0 && s < mem->share_n_seqs()) {
                        d[k] = mem->share_row(s, ubatch->pos[i]);
                        mem->share_note(s, ubatch->pos[i]);
                    } else {
                        d[k] = mem->share_scratch_row();
                    }
                    ++k;
                }
                for (; k < rows->ne[0]; ++k) {
                    r[k] = 0;
                    d[k] = mem->share_scratch_row();
                }
            }
            return;
        }

        llama_host_write(extra);
        int32_t * e = (int32_t *) extra->data;
        const int64_t n_extra = extra->ne[0];
        const int64_t n_kv    = attn->get_n_kv();
        std::vector<int64_t> since;
        for (uint32_t i = 0; i < n_tokens; ++i) {
            const llama_seq_id s = ubatch->seq_id[i][0];
            const llama_pos    p = ubatch->pos[i];
            // the latest selection kept before this position, and the cells of the positions after it up to this one:
            // the tokens accepted since, the ones drafted in this loop, this one (its cell is already in the cache)
            const llama_pos cap = mem->share_latest(s, p);
            r[i] = cap >= 0 ? mem->share_row(s, cap) : mem->share_none_row();
            mem->share_cells(s, cap >= 0 ? cap + 1 : std::max<llama_pos>(0, p - (llama_pos) n_extra + 1), p, since);
            // the most recent positions if there are more than the columns hold
            const size_t first = since.size() > (size_t) n_extra ? since.size() - (size_t) n_extra : 0;
            for (int64_t k = 0; k < n_extra; ++k) {
                const size_t  j = first + (size_t) k;
                const int64_t c = j < since.size() ? since[j] - kv_off : -1;
                e[i*n_extra + k] = c >= 0 && c < n_kv ? (int32_t) c : -1;
            }
        }
    }

    bool can_reuse(const llm_graph_params & params) override {
        mctx = static_cast<const llama_memory_hybrid_idx_context *>(params.mctx);
        if (params.cparams.mtp_share_reuse != reuse) {
            return false;
        }
        const int64_t n_tokens = params.ubatch.n_tokens;
        if (reuse) {
            return rows->ne[0] == n_tokens && extra->ne[1] == n_tokens;
        }
        return rows->ne[0] == (n_tokens <= QWEN4EXP_SHARE_KEEP_ALL ? n_tokens : (int64_t) params.ubatch.n_seqs_unq);
    }

    ggml_tensor * off   = nullptr;   // F32 [2]: the first cell of the graph's view of the cache, and the view's length
    ggml_tensor * rows  = nullptr;   // I32 capture: the ubatch rows kept [n_keep]; reuse: each token's share row [n_tokens]
    ggml_tensor * dst   = nullptr;   // I32 [n_keep]: capture: the share rows written (scratch for rows not kept)
    ggml_tensor * extra = nullptr;   // I32 [QWEN4EXP_SHARE_EXTRA, n_tokens]: reuse: view cells of the positions since, -1 padding

    const llama_memory_hybrid_idx_context * mctx;
    const bool reuse;
};

void llama_model_qwen4exp::graph::build_mtp_store_kv(
        llm_graph_input_attn_kv * inp,
        ggml_tensor *             k_cur,
        ggml_tensor *             v_cur,
        int                       il) {
    // rotated before a quantized cache and stored exactly as build_attn and build_attn_qsa do it
    if (inp->self_k_rot) {
        k_cur = llama_mul_mat_hadamard(ctx0, k_cur, inp->self_k_rot);
    }
    if (inp->self_v_rot) {
        v_cur = llama_mul_mat_hadamard(ctx0, v_cur, inp->self_v_rot);
    }
    ggml_build_forward_expand(gf, v_cur);
    ggml_build_forward_expand(gf, k_cur);

    const auto * mctx_cur = inp->mctx;
    ggml_build_forward_expand(gf, mctx_cur->cpy_k(ctx0, k_cur, inp->get_k_idxs(), il));
    ggml_build_forward_expand(gf, mctx_cur->cpy_v(ctx0, v_cur, inp->get_v_idxs(), il));
}

void llama_model_qwen4exp::graph::build_mtp_share_capture(
        const llama_memory_hybrid_idx_context * mctx_hyb,
        ggml_tensor *                           top_k) {
    const auto * mem = mctx_hyb->get_mem();
    const int64_t w = mem->share_width();
    GGML_ASSERT(top_k->ne[0] == w && top_k->ne[1] == n_tokens && top_k->ne[2] == 1 && top_k->ne[3] == 1);

    const int64_t n_keep = n_tokens <= QWEN4EXP_SHARE_KEEP_ALL ? (int64_t) n_tokens : (int64_t) ubatch.n_seqs_unq;
    auto inp = std::make_unique<llm_graph_input_mtp_share>(mctx_hyb, false);
    inp->off  = ggml_new_tensor_1d(ctx0, GGML_TYPE_F32, 2);
    inp->rows = ggml_new_tensor_1d(ctx0, GGML_TYPE_I32, n_keep);
    inp->dst  = ggml_new_tensor_1d(ctx0, GGML_TYPE_I32, n_keep);
    ggml_set_input(inp->off);
    ggml_set_input(inp->rows);
    ggml_set_input(inp->dst);

    // a view cell c becomes absolute c + 1 (the view moves between graphs), "no cell" (-1) becomes 0
    ggml_tensor * off   = ggml_view_1d(ctx0, inp->off, 1, 0);
    ggml_tensor * sel   = ggml_cast(ctx0, ggml_reshape_2d(ctx0, ggml_cont(ctx0, top_k), w, n_tokens), GGML_TYPE_F32);
    ggml_tensor * valid = ggml_step(ctx0, ggml_scale_bias(ctx0, sel, 1.0f, 0.5f));
    ggml_tensor * abs1  = ggml_mul(ctx0, ggml_add(ctx0, ggml_scale_bias(ctx0, sel, 1.0f, 1.0f), off), valid);
    ggml_tensor * keep  = ggml_get_rows(ctx0, abs1, inp->rows);
    cb(keep, "mtp_share_keep", -1);

    ggml_tensor * t    = mem->share_sel();
    ggml_tensor * view = ggml_view_2d(ctx0, t, t->ne[0], t->ne[1], t->nb[1], 0);
    ggml_build_forward_expand(gf, ggml_set_rows(ctx0, view, keep, inp->dst));

    res->add_input(std::move(inp));
}

ggml_tensor * llama_model_qwen4exp::graph::build_mtp_share_reuse(
        const llama_memory_hybrid_idx_context * mctx_hyb) {
    const auto * mem = mctx_hyb->get_mem();
    const int64_t w = mem->share_width();

    auto inp = std::make_unique<llm_graph_input_mtp_share>(mctx_hyb, true);
    inp->off   = ggml_new_tensor_1d(ctx0, GGML_TYPE_F32, 2);
    inp->rows  = ggml_new_tensor_1d(ctx0, GGML_TYPE_I32, n_tokens);
    inp->extra = ggml_new_tensor_2d(ctx0, GGML_TYPE_I32, QWEN4EXP_SHARE_EXTRA, n_tokens);
    ggml_set_input(inp->off);
    ggml_set_input(inp->rows);
    ggml_set_input(inp->extra);

    ggml_tensor * off  = ggml_view_1d(ctx0, inp->off, 1, 0);
    ggml_tensor * n_kv = ggml_view_1d(ctx0, inp->off, 1, ggml_element_size(inp->off));
    ggml_tensor * t    = mem->share_sel();
    ggml_tensor * view = ggml_view_2d(ctx0, t, t->ne[0], t->ne[1], t->nb[1], 0);
    ggml_tensor * g    = ggml_get_rows(ctx0, view, inp->rows);                    // [w, n_tokens]: absolute + 1, 0 = none
    // back to cells of this graph's view: d = absolute - off + 1 is a cell of the view when 1 <= d <= n_kv. "None" and a
    // cell outside the view (a row the bookkeeping failed to drop) both become -1: the gather must never read past the view
    ggml_tensor * d     = ggml_sub(ctx0, g, off);
    ggml_tensor * valid = ggml_mul(ctx0,
            ggml_step(ctx0, ggml_scale_bias(ctx0, d, 1.0f, -0.5f)),
            ggml_step(ctx0, ggml_scale_bias(ctx0, ggml_sub(ctx0, d, n_kv), -1.0f, 0.5f)));
    ggml_tensor * rel  = ggml_scale_bias(ctx0, ggml_mul(ctx0, d, valid), 1.0f, -1.0f);
    rel = ggml_cast(ctx0, rel, GGML_TYPE_I32);
    ggml_tensor * sel  = ggml_concat(ctx0, rel, inp->extra, 0);                  // [w + extra, n_tokens]
    cb(sel, "mtp_share_sel", -1);

    res->add_input(std::move(inp));
    return ggml_reshape_4d(ctx0, sel, w + QWEN4EXP_SHARE_EXTRA, n_tokens, 1, 1);
}

void llama_model_qwen4exp::graph::build_qsa_store_k(
'''),
    ],
    os.path.join(tree, "src", "models", "models.h"): [
        ('''    class llm_graph_input_qsa_k;

''',
         '''    class llm_graph_input_qsa_k;
    class llm_graph_input_mtp_share;
    class llm_graph_input_mtp_capture;

'''),
        ('''  const llama_memory_hybrid_idx_context * mctx_hyb,
                    ggml_tensor * cur,
                            int   il);

''',
         '''  const llama_memory_hybrid_idx_context * mctx_hyb,
                    ggml_tensor * cur,
                            int   il);

        // strixllama: IndexShare for the MTP draft (LLAMA_MTP_INDEX_SHARE=1, llama_set_mtp_share_reuse): a catch-up
        // keeps its tokens' selections; a draft step takes the one kept for the position before its loop, plus the
        // cells of the positions drafted since, as its own top_k
        void build_mtp_share_capture(
  const llama_memory_hybrid_idx_context * mctx_hyb,
                    ggml_tensor * top_k);

        ggml_tensor * build_mtp_share_reuse(
  const llama_memory_hybrid_idx_context * mctx_hyb);

        // strixllama: a ubatch without outputs stores K and V (rotated as build_attn would) and attends to nothing
        void build_mtp_store_kv(
        llm_graph_input_attn_kv * inp,
                    ggml_tensor * k_cur,
                    ggml_tensor * v_cur,
                            int   il);

'''),
    ],
    os.path.join(tree, "src", "llama-context.h"): [
        ('''    void set_nextn_layer_offset(int32_t offset);
    void set_causal_attn(bool value);
''',
         '''    void set_nextn_layer_offset(int32_t offset);
    void set_mtp_share_reuse(bool reuse);
    bool mtp_share_ready(llama_seq_id seq_id, llama_pos pos) const;
    void set_causal_attn(bool value);
'''),
    ],
    os.path.join(tree, "src", "llama-context.cpp"): [
        ('''    cparams.nextn_layer_offset = offset;
}
''',
         '''    cparams.nextn_layer_offset = offset;
}

// strixllama: IndexShare (LLAMA_MTP_INDEX_SHARE=1). While on, a draft step attends to the latest selection a catch-up kept
// for its sequence plus the cells of every position since (llama_memory_hybrid_idx::share_sel)
void llama_context::set_mtp_share_reuse(bool reuse) {
    cparams.mtp_share_reuse = reuse;
}

bool llama_context::mtp_share_ready(llama_seq_id seq_id, llama_pos pos) const {
    const auto * mem = dynamic_cast<const llama_memory_hybrid_idx *>(memory.get());
    // a selection too far behind (the previous turn's, before a prompt) would leave the steps blind to the positions since
    const llama_pos c = mem != nullptr ? mem->share_latest(seq_id, pos + 1) : -1;
    return c >= 0 && pos - c <= llama_memory_hybrid_idx::share_max_gap;
}
'''),
        ('''
llama_memory_t llama_get_memory(const struct llama_context * ctx) {
''',
         '''
void llama_set_mtp_share_reuse(llama_context * ctx, bool reuse) {
    ctx->set_mtp_share_reuse(reuse);
}

bool llama_mtp_share_ready(llama_context * ctx, llama_seq_id seq_id, llama_pos pos) {
    return ctx->mtp_share_ready(seq_id, pos);
}

llama_memory_t llama_get_memory(const struct llama_context * ctx) {
'''),
    ],
    os.path.join(tree, "src", "llama-cparams.h"): [
        ('''    int32_t  nextn_layer_offset = 0;

''',
         '''    int32_t  nextn_layer_offset = 0;

    // strixllama: IndexShare for a QSA MTP draft (llama_set_mtp_share_reuse): the draft steps reuse the sparse-attention
    // selection the catch-up captured instead of running the indexer
    bool     mtp_share_reuse = false;

'''),
    ],
    os.path.join(tree, "src", "llama-ext.h"): [
        ('''LLAMA_API void llama_set_nextn_layer_offset(struct llama_context * ctx, int32_t offset);

// mirrors:
// LLAMA_API float * llama_get_embeddings(struct llama_context * ctx);
''',
         '''LLAMA_API void llama_set_nextn_layer_offset(struct llama_context * ctx, int32_t offset);

// strixllama: IndexShare for a QSA MTP draft context (LLAMA_MTP_INDEX_SHARE=1). Its catch-up decodes keep the sparse-attention
// selections of the positions they decode (every LLAMA_MTP_INDEX_SHARE_REFRESH positions); between
// llama_set_mtp_share_reuse(ctx, true) and (ctx, false) a draft step reuses the latest selection kept for its sequence plus
// every position since, instead of running the indexer. llama_mtp_share_ready: whether a selection is kept for seq_id at
// or before pos.
LLAMA_API void llama_set_mtp_share_reuse(struct llama_context * ctx, bool reuse);
LLAMA_API bool llama_mtp_share_ready(struct llama_context * ctx, llama_seq_id seq_id, llama_pos pos);

// mirrors:
// LLAMA_API float * llama_get_embeddings(struct llama_context * ctx);
'''),
    ],
    os.path.join(tree, "src", "llama-graph.h"): [
        ('''
        return
''',
         '''
        // strixllama: a draft step that reuses the captured selection builds a different graph (IndexShare)
        if (cparams.mtp_share_reuse != other.cparams.mtp_share_reuse) {
            return false;
        }

        return
'''),
    ],
    os.path.join(tree, "common", "speculative.cpp"): [
        ('''        int n_confident = n_drafting;

        int i = 0;

''',
         '''        int n_confident = n_drafting;

        // strixllama: IndexShare (LLAMA_MTP_INDEX_SHARE=1): the draft steps reuse the sparse-attention selection the
        // catch-up kept for the position before each sequence's first step, when every drafting sequence has one
        static const bool share_env = getenv("LLAMA_MTP_INDEX_SHARE") && atoi(getenv("LLAMA_MTP_INDEX_SHARE")) != 0;
        bool share = share_env && !chain_heads && !is_mem_shared && n_drafting > 0;
        for (llama_seq_id seq_id = 0; share && seq_id < (llama_seq_id) n_seq; ++seq_id) {
            if (drafting[seq_id]) {
                share = llama_mtp_share_ready(ctx_dft, seq_id, dparams[seq_id].pos0 - 1);
            }
        }
        if (share) {
            llama_set_mtp_share_reuse(ctx_dft, true);
        }

        int i = 0;

'''),
        ('''            llama_set_nextn_layer_offset(ctx_dft, 0); // restore default for non-draft decodes
        }
''',
         '''            llama_set_nextn_layer_offset(ctx_dft, 0); // restore default for non-draft decodes
        }
        if (share) {
            llama_set_mtp_share_reuse(ctx_dft, false);
        }
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
