#!/usr/bin/env python3
"""Ragged ubatches for the hybrid memory: sequences of different lengths in one pass

The hybrid memory needed every sequence of a ubatch to have the same token count, so a batch of conversations decoding next to a prompt, or of several prompts, ran as several equal-length ubatches, each a pass over all the weights: five prompt tails of 292-556 tokens took six passes. split_ragged makes one ubatch of them (llama_ubatch::ragged: per-set token counts and offsets), the recurrent memory takes per-set counts, a ragged ubatch replays the deferred rollback first and runs the plain net, and qwen4exp builds its per-sequence parts - the gated delta net's conv and net, the per-layer-embedding conv - once per group of sets with one count, the per-token rest once. Equal-length ubatches build the graph they did. STRIX_RAGGED=0: the equal-length split. Six agents on eight slots: time to first token p50 4.7 -> 3.3-3.6 s; outputs of prompts batched together stay inside the batch-shape noise floor.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 33 hunks across 9 file(s).

Usage: python patches/apply_ragged_ubatch_027.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'split_ragged'

EDITS = {
    os.path.join(tree, "src", "llama-batch.h"): [
        ('''        std::vector<llama_seq_id> seq_id_data;
    };
''',
         '''        std::vector<llama_seq_id> seq_id_data;

        std::vector<uint32_t> seq_ntok;          // strixllama: ragged ubatches, see below
        std::vector<uint32_t> seq_tok0;
    };
'''),
        ('''    std::shared_ptr<data_t> data;
};
''',
         '''    std::shared_ptr<data_t> data;

    // strixllama: a ragged ubatch (split_ragged) gives its sequence sets different token counts: set s owns the
    // tokens [seq_tok0[s], seq_tok0[s] + seq_ntok[s]), sets of one count next to each other, and n_seq_tokens is 0.
    // Every other ubatch leaves these null, and set s owns n_seq_tokens tokens from s*n_seq_tokens.
    const uint32_t * seq_ntok = nullptr; // [n_seqs]
    const uint32_t * seq_tok0 = nullptr; // [n_seqs]

    bool ragged() const {
        return seq_ntok != nullptr;
    }
    uint32_t ntok(uint32_t s) const {
        return seq_ntok ? seq_ntok[s] : n_seq_tokens;
    }
    uint32_t tok0(uint32_t s) const {
        return seq_tok0 ? seq_tok0[s] : s*n_seq_tokens;
    }
};
'''),
        ('''
    // a helper method for creating a well-defined ubatch of tokens
''',
         '''
    // strixllama: one ubatch for sequence sets of different lengths (llama_ubatch::ragged): the shortest sets whole,
    // the rest of n_ubatch to the longer ones in turn, and no set leaves fewer than n_keep_tail tokens for a later
    // ubatch. Needs a batch without coupled sequences (has_coupled)
    llama_ubatch split_ragged(uint32_t n_ubatch, uint32_t n_keep_tail);

    bool has_coupled() const {
        return has_cpl;
    }

    // a helper method for creating a well-defined ubatch of tokens
'''),
        ('''    llama_ubatch ubatch_add(const std::vector<int32_t> & idxs, uint32_t n_seqs, bool equal_seqs);
''',
         '''    // strixllama: seq_ntok, when given, makes a ragged ubatch: the token count of each of the n_seqs sets, in order
    llama_ubatch ubatch_add(const std::vector<int32_t> & idxs, uint32_t n_seqs, bool equal_seqs,
                            const std::vector<uint32_t> * seq_ntok = nullptr);
'''),
    ],
    os.path.join(tree, "src", "llama-batch.cpp"): [
        ('''
void llama_batch_allocr::clear() {
''',
         '''
// strixllama: the hybrid memory ran a batch of sequences with different token counts - conversations decoding next to
// a prompt, several prompts at once - as several equal-length ubatches, each a pass over all the weights: five prompt
// tails of 292-556 tokens took six passes. Here they are one ubatch, and the model runs its per-sequence parts (the
// recurrent layers) once per group of equal counts (llama_ubatch::ragged).
llama_ubatch llama_batch_allocr::split_ragged(uint32_t n_ubatch, uint32_t n_keep_tail) {
    GGML_ASSERT(!has_cpl && "split_ragged needs a batch without coupled sequences");

    // the sequence sets with tokens left, and where each stands
    std::vector<seq_set_t> sets;
    std::vector<int32_t>   cur;   // index into seq_set_map[set] of the first unused token
    std::vector<uint32_t>  rem;   // unused tokens left
    for (int32_t i = 0; i < batch.n_tokens && sets.size() < n_ubatch; ++i) {
        if (used[i]) {
            continue;
        }
        bool seen = false;
        for (const auto & s : sets) {
            if (s == seq_set[i]) {
                seen = true;
                break;
            }
        }
        if (seen) {
            continue;
        }
        const auto & idxs = seq_set_map[seq_set[i]];
        int32_t c = 0;
        while (c < (int32_t) idxs.size() && used[idxs[c]]) {
            ++c;
        }
        sets.push_back(seq_set[i]);
        cur.push_back(c);
        rem.push_back((uint32_t) (idxs.size() - c));
    }

    if (sets.empty()) {
        return {};
    }

    // the shortest first, whole; what n_ubatch has left goes to the longer ones in turn
    std::vector<uint32_t> order(sets.size());
    for (uint32_t s = 0; s < order.size(); ++s) {
        order[s] = s;
    }
    std::stable_sort(order.begin(), order.end(), [&](uint32_t x, uint32_t y) { return rem[x] < rem[y]; });

    std::vector<uint32_t> take(sets.size(), 0);
    uint32_t budget = n_ubatch;
    for (const uint32_t s : order) {
        uint32_t t = std::min(rem[s], budget);
        // [TAG_RECURRENT_ROLLBACK_SPLITS] the trailing n_keep_tail tokens of a set stay in one ubatch
        if (t < rem[s] && rem[s] - t < n_keep_tail) {
            t = rem[s] > n_keep_tail ? std::min(t, rem[s] - n_keep_tail) : 0;
        }
        take[s] = t;
        budget -= t;
    }

    uint32_t n_total = 0;
    for (const uint32_t t : take) {
        n_total += t;
    }
    if (n_total == 0) {
        // nothing fit under the tail rule: the first set alone, as split_equal would take it
        const uint32_t s = order[0];
        uint32_t t = std::min(rem[s], n_ubatch);
        if (t < rem[s] && rem[s] - t < n_keep_tail && rem[s] > n_keep_tail) {
            t = std::min(t, rem[s] - n_keep_tail);
        }
        take[s] = std::max<uint32_t>(t, 1);
    }

    // sets of one count next to each other, the longest first
    std::vector<uint32_t> chosen;
    for (const uint32_t s : order) {
        if (take[s] > 0) {
            chosen.push_back(s);
        }
    }
    std::stable_sort(chosen.begin(), chosen.end(), [&](uint32_t x, uint32_t y) { return take[x] > take[y]; });

    std::vector<int32_t>  idxs;
    std::vector<uint32_t> seq_ntok;
    for (const uint32_t s : chosen) {
        const auto & all = seq_set_map[sets[s]];
        for (uint32_t k = 0; k < take[s]; ++k) {
            const int32_t idx = all[cur[s] + k];
            idxs.push_back(idx);
            used[idx] = true;
            ++n_used;
        }
        seq_ntok.push_back(take[s]);
    }

    // one count for all: an ordinary equal-length ubatch
    bool uniform = true;
    for (const uint32_t t : seq_ntok) {
        uniform = uniform && t == seq_ntok[0];
    }

    return ubatch_add(idxs, (uint32_t) seq_ntok.size(), true, uniform ? nullptr : &seq_ntok);
}

void llama_batch_allocr::clear() {
'''),
        ('''llama_ubatch llama_batch_allocr::ubatch_add(const std::vector<int32_t> & idxs, uint32_t n_seqs, bool equal_seqs) {
''',
         '''llama_ubatch llama_batch_allocr::ubatch_add(const std::vector<int32_t> & idxs, uint32_t n_seqs, bool equal_seqs,
                                            const std::vector<uint32_t> * seq_ntok) {
'''),
        ('''    assert(n_tokens%n_seqs == 0);
''',
         '''    assert(seq_ntok || n_tokens%n_seqs == 0);
'''),
        ('''
    auto udata = std::make_shared<llama_ubatch::data_t>();

    const int64_t n_embd_all = batch.embd ? (int64_t) n_tokens*n_embd : 0;
''',
         '''
    auto udata = std::make_shared<llama_ubatch::data_t>();

    if (seq_ntok) {
        GGML_ASSERT(seq_ntok->size() == n_seqs);
        udata->seq_ntok = *seq_ntok;
        udata->seq_tok0.resize(n_seqs);
        uint32_t t0 = 0;
        for (uint32_t s = 0; s < n_seqs; ++s) {
            udata->seq_tok0[s] = t0;
            t0 += (*seq_ntok)[s];
        }
        GGML_ASSERT(t0 == n_tokens);
    }

    const int64_t n_embd_all = batch.embd ? (int64_t) n_tokens*n_embd : 0;
'''),
        ('''    }

    llama_ubatch res {
        /*.b_equal_seqs =*/ equal_seqs,
''',
         '''    }

    const uint32_t * p_ntok = seq_ntok ? udata->seq_ntok.data() : nullptr;
    const uint32_t * p_tok0 = seq_ntok ? udata->seq_tok0.data() : nullptr;

    llama_ubatch res {
        /*.b_equal_seqs =*/ equal_seqs,
'''),
        ('''        /*.n_seq_tokens =*/ n_tokens/n_seqs,
''',
         '''        /*.n_seq_tokens =*/ seq_ntok ? 0 : n_tokens/n_seqs,
'''),
        ('''        /*.seq_idx      =*/ udata->seq_idx.data(),
        /*.output       =*/ udata->output.data(),
        /*.data         =*/ std::move(udata),
    };

    if (debug > 0) {
''',
         '''        /*.seq_idx      =*/ udata->seq_idx.data(),
        /*.output       =*/ udata->output.data(),
        /*.data         =*/ std::move(udata),
        /*.seq_ntok     =*/ p_ntok,
        /*.seq_tok0     =*/ p_tok0,
    };

    if (debug > 0) {
'''),
        ('''        LLAMA_LOG_DEBUG("%s:   n_seq_tokens = %d\\n", __func__, ubatch.n_seq_tokens);
        LLAMA_LOG_DEBUG("%s:   n_seqs       = %d\\n", __func__, ubatch.n_seqs);
''',
         '''        LLAMA_LOG_DEBUG("%s:   n_seq_tokens = %d\\n", __func__, ubatch.n_seq_tokens);
        if (ubatch.ragged()) {
            std::stringstream ss;
            for (uint32_t s = 0; s < ubatch.n_seqs; ++s) {
                ss << ubatch.ntok(s) << " ";
            }
            LLAMA_LOG_DEBUG("%s:   ragged       = [ %s]\\n", __func__, ss.str().c_str());
        }
        LLAMA_LOG_DEBUG("%s:   n_seqs       = %d\\n", __func__, ubatch.n_seqs);
'''),
    ],
    os.path.join(tree, "src", "llama-memory-recurrent.cpp"): [
        ('''    const uint32_t n_seq_tokens = ubatch.n_seq_tokens;
''',
         '''    // strixllama: a ragged ubatch gives each sequence set its own token count (ubatch.tok0 / ubatch.ntok)
'''),
        ('''        const uint32_t i = s*n_seq_tokens; // first token of sequence set s
''',
         '''        const uint32_t i = ubatch.tok0(s); // first token of sequence set s
'''),
        ('''    for (uint32_t s = 0; s < n_seqs; ++s) {
        const uint32_t i = s*n_seq_tokens;
        const llama_seq_id seq_id = ubatch.seq_id[i][0];
''',
         '''    for (uint32_t s = 0; s < n_seqs; ++s) {
        const uint32_t i = ubatch.tok0(s);
        const llama_seq_id seq_id = ubatch.seq_id[i][0];
'''),
        ('''    for (uint32_t s = 0; s < n_seqs; ++s) {
        const uint32_t i = s*n_seq_tokens;
        const int32_t dst_id = s + min;
''',
         '''    for (uint32_t s = 0; s < n_seqs; ++s) {
        const uint32_t i = ubatch.tok0(s);
        const int32_t dst_id = s + min;
'''),
        ('''    for (uint32_t s = 0; s < n_seqs; ++s) {
        const uint32_t i = s*n_seq_tokens;
        const llama_pos last_pos = ubatch.pos[i + n_seq_tokens - 1];
''',
         '''    for (uint32_t s = 0; s < n_seqs; ++s) {
        const uint32_t i = ubatch.tok0(s);
        const uint32_t n_seq_tokens = ubatch.ntok(s);
        const llama_pos last_pos = ubatch.pos[i + n_seq_tokens - 1];
'''),
    ],
    os.path.join(tree, "src", "llama-graph.h"): [
        ('''        bool can_reuse_ubatch =
''',
         '''        // strixllama: a ragged ubatch builds its per-sequence parts per group of token counts; it carries a prompt, so
        // a graph built for it is not worth keeping
        bool can_reuse_ubatch =
            !ubatch.ragged() && !other.ubatch.ragged() &&
'''),
    ],
    os.path.join(tree, "src", "llama-graph.cpp"): [
        ('''    // cell's state to copy along (build_rs does that, and the deferred-rollback net goes without it)
    const bool is_short = ubatch.n_seq_tokens <= mctx->get_n_rs_seq() + 1;
''',
         '''    // cell's state to copy along (build_rs does that, and the deferred-rollback net goes without it). A ragged ubatch
    // replays first and runs the plain net, group by group
    const bool is_short = !ubatch.ragged() && ubatch.n_seq_tokens <= mctx->get_n_rs_seq() + 1;
'''),
    ],
    os.path.join(tree, "src", "llama-memory-hybrid-idx.cpp"): [
        ('''                ubatch = balloc.split_equal(n_ubatch, !unified, n_rs_seq > 0 ? n_rs_seq + 1 : 0);
''',
         '''                // strixllama: sequences of different lengths in one ubatch (llama_ubatch::ragged), where the model
                // (qwen4exp, the only user of this memory) builds its recurrent layers per group of lengths;
                // STRIX_RAGGED=0: the equal-length split
                static const bool ragged = [] {
                    const char * e = getenv("STRIX_RAGGED");
                    return e == nullptr || atoi(e) != 0;
                }();
                if (ragged && unified && !balloc.has_coupled()) {
                    ubatch = balloc.split_ragged(n_ubatch, n_rs_seq > 0 ? n_rs_seq + 1 : 0);
                } else {
                    ubatch = balloc.split_equal(n_ubatch, !unified, n_rs_seq > 0 ? n_rs_seq + 1 : 0);
                }
'''),
    ],
    os.path.join(tree, "src", "models", "models.h"): [
        ('''    // s: (head_v_dim, head_v_dim, num_v_heads, n_seqs); returns output: (head_v_dim, num_v_heads, n_seq_tokens, n_seqs)
    ggml_tensor * build_recurrent_attn(
''',
         '''    // s: (head_v_dim, head_v_dim, num_v_heads, n_seqs); returns output: (head_v_dim, num_v_heads, n_seq_tokens, n_seqs)
    // strixllama: s0 - the sequences are the ubatch's from set s0 on (a group of a ragged ubatch), their cells
    // head + s0 on
    ggml_tensor * build_recurrent_attn(
'''),
        ('''            ggml_tensor *        s,
            int                  il);
};
''',
         '''            ggml_tensor *        s,
            int                  il,
            int64_t              s0 = 0);
};
'''),
        ('''        // one conv history per cache tensor: delta-net and PLE each have their own
''',
         '''        // one conv history per cache tensor: delta-net and PLE each have their own. strixllama: s0, n_seqs - the
        // group of a ragged ubatch x holds (x [channels, tokens, n_seqs]); -1: all the ubatch's sequences
'''),
        ('''                        int64_t   channels,
                            int   il);

''',
         '''                        int64_t   channels,
                            int   il,
                        int64_t   s0 = 0,
                        int64_t   n_seqs = -1);

'''),
    ],
    os.path.join(tree, "src", "models", "delta-net-base.cpp"): [
        ('''        int                  il) {
    const auto * mctx_cur   = inp->mctx;
    const auto   kv_head    = mctx_cur->get_head();
''',
         '''        int                  il,
        int64_t              s0) {
    const auto * mctx_cur   = inp->mctx;
    const auto   kv_head    = mctx_cur->get_head() + s0;
'''),
    ],
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''                        int   il) {
    const int64_t n_seqs       = ubatch.n_seqs;
    const int64_t n_seq_tokens = ubatch.n_seq_tokens;

''',
         '''                        int   il) {
    // strixllama: a ragged ubatch keeps one column per token; build_layer_attn_linear takes each group's columns
    const int64_t n_seqs       = ubatch.ragged() ? 1 : ubatch.n_seqs;
    const int64_t n_seq_tokens = ubatch.ragged() ? n_tokens : ubatch.n_seq_tokens;

'''),
        ('''
ggml_tensor * llama_model_qwen4exp::graph::build_layer_attn_linear(
''',
         '''
// strixllama: the sequence sets of a ubatch in groups of one token count - split_ragged puts sets of one count next to
// each other (llama_ubatch::ragged): group g is n_seqs sets from set s0, n_tok tokens each, its tokens from t0. An
// equal-length ubatch is one group
struct qwen4exp_seq_group {
    int64_t s0;
    int64_t n_seqs;
    int64_t n_tok;
    int64_t t0;
};

static std::vector<qwen4exp_seq_group> qwen4exp_seq_groups(const llama_ubatch & ub) {
    std::vector<qwen4exp_seq_group> res;
    for (uint32_t s = 0; s < ub.n_seqs; ++s) {
        const int64_t n  = ub.ntok(s);
        const int64_t t0 = ub.tok0(s);
        if (!res.empty() && res.back().n_tok == n && res.back().t0 + res.back().n_seqs * n == t0) {
            res.back().n_seqs++;
        } else {
            res.push_back({ (int64_t) s, 1, n, t0 });
        }
    }
    return res;
}

// strixllama: the groups' outputs back in one tensor, a column of `rows` values per token, in token order.
// split_ragged puts the longest group first; the short ones are joined first, so the long one is copied once
static ggml_tensor * qwen4exp_concat_groups(ggml_context * ctx, const std::vector<ggml_tensor *> & parts, int64_t rows) {
    std::vector<ggml_tensor *> cols;
    for (ggml_tensor * p : parts) {
        cols.push_back(ggml_reshape_2d(ctx, p, rows, ggml_nelements(p) / rows));
    }
    ggml_tensor * rest = nullptr;
    for (size_t k = 1; k < cols.size(); ++k) {
        rest = rest ? ggml_concat(ctx, rest, cols[k], 1) : cols[k];
    }
    return rest ? ggml_concat(ctx, cols[0], rest, 1) : cols[0];
}

ggml_tensor * llama_model_qwen4exp::graph::build_layer_attn_linear(
'''),
        ('''    const int64_t n_seq_tokens = ubatch.n_seq_tokens;

    GGML_ASSERT(n_seqs != 0);
    GGML_ASSERT(ubatch.equal_seqs());
    GGML_ASSERT(ubatch.n_tokens == n_seq_tokens * n_seqs);
    GGML_ASSERT(head_v_dim * num_v_heads == d_inner);

    auto qkvz = build_qkvz(cur, il);
    ggml_tensor * qkv_mixed = qkvz.first;
    ggml_tensor * z         = qkvz.second;

    ggml_tensor * beta = build_lora_mm(model.layers[il].ssm_beta, cur, model.layers[il].ssm_beta_s);
    beta = ggml_reshape_4d(ctx0, beta, 1, num_v_heads, n_seq_tokens, n_seqs);
    cb(beta, "beta", il);

    beta = ggml_sigmoid(ctx0, beta);
    cb(beta, "beta_sigmoid", il);

    ggml_tensor * alpha = build_lora_mm(model.layers[il].ssm_alpha, cur, model.layers[il].ssm_alpha_s);
    alpha = ggml_reshape_3d(ctx0, alpha, num_v_heads, n_seq_tokens, n_seqs);
''',
         '''
    // strixllama: a ragged ubatch (llama_ubatch::ragged) builds the per-sequence part - the conv, the net and the
    // states they read and write - once per group of sets with one token count (qwen4exp_seq_groups), and the per-token
    // rest once, as a single set of all the tokens. An equal-length ubatch is one group and builds the graph it did
    const bool    ragged       = ubatch.ragged();
    const int64_t n_seq_tokens = ragged ? (int64_t) ubatch.n_tokens : (int64_t) ubatch.n_seq_tokens;
    const int64_t n_seqs_tok   = ragged ? 1 : n_seqs;

    GGML_ASSERT(n_seqs != 0);
    GGML_ASSERT(ubatch.equal_seqs());
    GGML_ASSERT(ubatch.n_tokens == n_seq_tokens * n_seqs_tok);
    GGML_ASSERT(head_v_dim * num_v_heads == d_inner);

    auto qkvz = build_qkvz(cur, il);
    ggml_tensor * qkv_mixed = qkvz.first;
    ggml_tensor * z         = qkvz.second;

    ggml_tensor * beta = build_lora_mm(model.layers[il].ssm_beta, cur, model.layers[il].ssm_beta_s);
    beta = ggml_reshape_4d(ctx0, beta, 1, num_v_heads, n_seq_tokens, n_seqs_tok);
    cb(beta, "beta", il);

    beta = ggml_sigmoid(ctx0, beta);
    cb(beta, "beta_sigmoid", il);

    ggml_tensor * alpha = build_lora_mm(model.layers[il].ssm_alpha, cur, model.layers[il].ssm_alpha_s);
    alpha = ggml_reshape_3d(ctx0, alpha, num_v_heads, n_seq_tokens, n_seqs_tok);
'''),
        ('''    gate = ggml_reshape_4d(ctx0, gate, 1, num_v_heads, n_seq_tokens, n_seqs);
''',
         '''    gate = ggml_reshape_4d(ctx0, gate, 1, num_v_heads, n_seq_tokens, n_seqs_tok);
'''),
        ('''    ggml_tensor * conv_input = build_conv_state_at(inp, conv_states_all, qkv_mixed,
            conv_kernel_size - 1, conv_channels, il);

    // strixllama: deferred rollback (llm_graph_input_rs::lazy_mode): a short batch runs the net that records instead
    // of snapshotting and reads its states from their rows itself; any other first replays the records the states
    // still carry, in place, so the gather and the plain net see them as they expect
    const int lazy_mode = inp->lazy_mode;
    ggml_tensor * state = nullptr;
    if (lazy_mode != 1) {
        ggml_tensor * ssm_src = ssm_states_all;
        if (lazy_mode == 2) {
            ssm_src = ggml_gated_delta_net_replay(ctx0, ssm_states_all, mctx_cur->get_rec_l(il), inp->lazy_info,
                    (int) head_v_dim, (int) num_v_heads, (int) num_k_heads);
        }
        state = build_rs(inp, ssm_src, hparams.n_embd_s(), n_seqs);
        state = ggml_reshape_4d(ctx0, state, head_v_dim, head_v_dim, num_v_heads, n_seqs);
        cb(state, "state_predelta", il);
    }

    ggml_tensor * conv_output_proper = ggml_ssm_conv(ctx0, conv_input, conv_kernel);
    cb(conv_output_proper, "conv_output_raw", il);

    ggml_tensor * conv_output_silu = ggml_silu(ctx0, conv_output_proper);
    cb(conv_output_silu, "conv_output_silu", il);

    ggml_tensor * conv_qkv_mix = conv_output_silu;

    int64_t nb1_qkv = ggml_row_size(conv_qkv_mix->type, conv_channels);

    // Extract the convolved Q, K, V from conv_output
    ggml_tensor * q_conv = ggml_view_4d(ctx0, conv_qkv_mix, head_k_dim, num_k_heads, n_seq_tokens, n_seqs,
            ggml_row_size(conv_qkv_mix->type, head_k_dim),
            nb1_qkv,
            nb1_qkv * n_seq_tokens,
            0);

    ggml_tensor * k_conv = ggml_view_4d(ctx0, conv_qkv_mix, head_k_dim, num_k_heads, n_seq_tokens, n_seqs,
            ggml_row_size(conv_qkv_mix->type, head_k_dim),
            nb1_qkv,
            nb1_qkv * n_seq_tokens,
            head_k_dim * num_k_heads * ggml_element_size(conv_qkv_mix));

    ggml_tensor * v_conv = ggml_view_4d(ctx0, conv_qkv_mix, head_v_dim, num_v_heads, n_seq_tokens, n_seqs,
            ggml_row_size(conv_qkv_mix->type, head_v_dim),
            nb1_qkv,
            nb1_qkv * n_seq_tokens,
            ggml_row_size(conv_qkv_mix->type, 2 * head_k_dim * num_k_heads));

    cb(q_conv, "q_conv", il);
    cb(k_conv, "k_conv", il);
    cb(v_conv, "v_conv", il);

    const float eps_norm = hparams.f_norm_rms_eps;

    q_conv = build_gdn_l2_norm(ctx0, q_conv, eps_norm);
    k_conv = build_gdn_l2_norm(ctx0, k_conv, eps_norm);

    // repeat to match shapes when head keys != value keys; unneeded with the fused GDN (and the deferred-rollback net)
    if (num_k_heads != num_v_heads && (!cparams.fused_gdn_ar || !cparams.fused_gdn_ch) && lazy_mode != 1) {
        GGML_ASSERT(num_v_heads % num_k_heads == 0);
        q_conv = ggml_repeat_4d(ctx0, q_conv, head_k_dim, num_v_heads, n_seq_tokens, n_seqs);
        k_conv = ggml_repeat_4d(ctx0, k_conv, head_k_dim, num_v_heads, n_seq_tokens, n_seqs);
    }

    cb(q_conv, "q_conv_predelta", il);
    cb(k_conv, "k_conv_predelta", il);
    cb(v_conv, "v_conv_predelta", il);

    ggml_tensor * output = nullptr;
    if (lazy_mode == 1) {
        output = ggml_gated_delta_net_lazy(ctx0, q_conv, k_conv, v_conv, gate, beta, ssm_states_all,
                mctx_cur->get_rec_l(il), inp->lazy_info);
        output = ggml_reshape_4d(ctx0, output, head_v_dim, num_v_heads, n_seq_tokens, n_seqs);
        cb(output, "attn_output", il);
    } else {
        output = build_recurrent_attn(inp, ssm_states_all, q_conv, k_conv, v_conv, gate, beta, state, il);
    }

    ggml_tensor * z_2d = ggml_reshape_4d(ctx0, z, head_v_dim, num_v_heads, n_seq_tokens, n_seqs);

    // gated normalization, as self.norm(core_attn_out, z) in the reference
    ggml_tensor * attn_out_norm = build_norm_gated(output, model.layers[il].ssm_norm, z_2d, il);

    // strixllama: one column per token, not a batch per sequence (STRIX_GDN_OUT_2D=0: as upstream): with several
    // sequences decoding at once, a 3-D input made the projection a batched matrix-vector product per sequence
    static const bool out_2d = !getenv("STRIX_GDN_OUT_2D") || atoi(getenv("STRIX_GDN_OUT_2D")) != 0;
    ggml_tensor * final_output = out_2d && n_seqs > 1
        ? ggml_reshape_2d(ctx0, attn_out_norm, head_v_dim * num_v_heads, n_seq_tokens * n_seqs)
        : ggml_reshape_3d(ctx0, attn_out_norm, head_v_dim * num_v_heads, n_seq_tokens, n_seqs);
    cb(final_output, "final_output", il);

    cur = build_lora_mm(model.layers[il].ssm_out, final_output, model.layers[il].ssm_out_s);
    cb(cur, "linear_attn_out", il);

    cur = ggml_reshape_2d(ctx0, cur, n_embd, n_seq_tokens * n_seqs);
''',
         '''    // strixllama: deferred rollback (llm_graph_input_rs::lazy_mode): a short batch runs the net that records instead
    // of snapshotting and reads its states from their rows itself; any other first replays the records the states
    // still carry, in place, so the gather and the plain net see them as they expect. A ragged ubatch is never short
    const int lazy_mode = inp->lazy_mode;
    GGML_ASSERT(!ragged || lazy_mode != 1);
    ggml_tensor * states = nullptr;

    std::vector<ggml_tensor *> outputs;
    for (const auto & g : qwen4exp_seq_groups(ubatch)) {
        const int64_t n_grp_tok  = g.n_tok;
        const int64_t n_grp_seqs = g.n_seqs;

        // the group's tokens, the columns [t0, t0 + n_tok*n_seqs) - the whole tensors when it is the only group
        ggml_tensor * x_g    = qkv_mixed;
        ggml_tensor * beta_g = beta;
        ggml_tensor * gate_g = gate;
        if (ragged) {
            x_g    = ggml_view_3d(ctx0, qkv_mixed, qkv_mixed->ne[0], n_grp_tok, n_grp_seqs,
                    qkv_mixed->nb[1], qkv_mixed->nb[1] * n_grp_tok, qkv_mixed->nb[1] * g.t0);
            beta_g = ggml_view_4d(ctx0, beta, 1, num_v_heads, n_grp_tok, n_grp_seqs,
                    beta->nb[1], beta->nb[2], beta->nb[2] * n_grp_tok, beta->nb[2] * g.t0);
            gate_g = ggml_view_4d(ctx0, gate, 1, num_v_heads, n_grp_tok, n_grp_seqs,
                    gate->nb[1], gate->nb[2], gate->nb[2] * n_grp_tok, gate->nb[2] * g.t0);
        }

        ggml_tensor * conv_input = build_conv_state_at(inp, conv_states_all, x_g,
                conv_kernel_size - 1, conv_channels, il, g.s0, ragged ? n_grp_seqs : -1);

        ggml_tensor * state = nullptr;
        if (lazy_mode != 1) {
            if (states == nullptr) {
                ggml_tensor * ssm_src = ssm_states_all;
                if (lazy_mode == 2) {
                    ssm_src = ggml_gated_delta_net_replay(ctx0, ssm_states_all, mctx_cur->get_rec_l(il), inp->lazy_info,
                            (int) head_v_dim, (int) num_v_heads, (int) num_k_heads);
                }
                states = build_rs(inp, ssm_src, hparams.n_embd_s(), n_seqs);
            }
            state = ragged ? ggml_view_2d(ctx0, states, states->ne[0], n_grp_seqs, states->nb[1], states->nb[1] * g.s0)
                           : states;
            state = ggml_reshape_4d(ctx0, state, head_v_dim, head_v_dim, num_v_heads, n_grp_seqs);
            cb(state, "state_predelta", il);
        }

        ggml_tensor * conv_output_proper = ggml_ssm_conv(ctx0, conv_input, conv_kernel);
        cb(conv_output_proper, "conv_output_raw", il);

        ggml_tensor * conv_output_silu = ggml_silu(ctx0, conv_output_proper);
        cb(conv_output_silu, "conv_output_silu", il);

        ggml_tensor * conv_qkv_mix = conv_output_silu;

        int64_t nb1_qkv = ggml_row_size(conv_qkv_mix->type, conv_channels);

        // Extract the convolved Q, K, V from conv_output
        ggml_tensor * q_conv = ggml_view_4d(ctx0, conv_qkv_mix, head_k_dim, num_k_heads, n_grp_tok, n_grp_seqs,
                ggml_row_size(conv_qkv_mix->type, head_k_dim),
                nb1_qkv,
                nb1_qkv * n_grp_tok,
                0);

        ggml_tensor * k_conv = ggml_view_4d(ctx0, conv_qkv_mix, head_k_dim, num_k_heads, n_grp_tok, n_grp_seqs,
                ggml_row_size(conv_qkv_mix->type, head_k_dim),
                nb1_qkv,
                nb1_qkv * n_grp_tok,
                head_k_dim * num_k_heads * ggml_element_size(conv_qkv_mix));

        ggml_tensor * v_conv = ggml_view_4d(ctx0, conv_qkv_mix, head_v_dim, num_v_heads, n_grp_tok, n_grp_seqs,
                ggml_row_size(conv_qkv_mix->type, head_v_dim),
                nb1_qkv,
                nb1_qkv * n_grp_tok,
                ggml_row_size(conv_qkv_mix->type, 2 * head_k_dim * num_k_heads));

        cb(q_conv, "q_conv", il);
        cb(k_conv, "k_conv", il);
        cb(v_conv, "v_conv", il);

        const float eps_norm = hparams.f_norm_rms_eps;

        q_conv = build_gdn_l2_norm(ctx0, q_conv, eps_norm);
        k_conv = build_gdn_l2_norm(ctx0, k_conv, eps_norm);

        // repeat to match shapes when head keys != value keys; unneeded with the fused GDN (and the deferred-rollback
        // net)
        if (num_k_heads != num_v_heads && (!cparams.fused_gdn_ar || !cparams.fused_gdn_ch) && lazy_mode != 1) {
            GGML_ASSERT(num_v_heads % num_k_heads == 0);
            q_conv = ggml_repeat_4d(ctx0, q_conv, head_k_dim, num_v_heads, n_grp_tok, n_grp_seqs);
            k_conv = ggml_repeat_4d(ctx0, k_conv, head_k_dim, num_v_heads, n_grp_tok, n_grp_seqs);
        }

        cb(q_conv, "q_conv_predelta", il);
        cb(k_conv, "k_conv_predelta", il);
        cb(v_conv, "v_conv_predelta", il);

        ggml_tensor * output = nullptr;
        if (lazy_mode == 1) {
            output = ggml_gated_delta_net_lazy(ctx0, q_conv, k_conv, v_conv, gate_g, beta_g, ssm_states_all,
                    mctx_cur->get_rec_l(il), inp->lazy_info);
            output = ggml_reshape_4d(ctx0, output, head_v_dim, num_v_heads, n_grp_tok, n_grp_seqs);
            cb(output, "attn_output", il);
        } else {
            output = build_recurrent_attn(inp, ssm_states_all, q_conv, k_conv, v_conv, gate_g, beta_g, state, il, g.s0);
        }
        outputs.push_back(output);
    }

    ggml_tensor * output = outputs[0];
    if (ragged) {
        output = qwen4exp_concat_groups(ctx0, outputs, head_v_dim * num_v_heads);
        output = ggml_reshape_4d(ctx0, output, head_v_dim, num_v_heads, n_seq_tokens, n_seqs_tok);
    }

    ggml_tensor * z_2d = ggml_reshape_4d(ctx0, z, head_v_dim, num_v_heads, n_seq_tokens, n_seqs_tok);

    // gated normalization, as self.norm(core_attn_out, z) in the reference
    ggml_tensor * attn_out_norm = build_norm_gated(output, model.layers[il].ssm_norm, z_2d, il);

    // strixllama: one column per token, not a batch per sequence (STRIX_GDN_OUT_2D=0: as upstream): with several
    // sequences decoding at once, a 3-D input made the projection a batched matrix-vector product per sequence
    static const bool out_2d = !getenv("STRIX_GDN_OUT_2D") || atoi(getenv("STRIX_GDN_OUT_2D")) != 0;
    ggml_tensor * final_output = out_2d && n_seqs_tok > 1
        ? ggml_reshape_2d(ctx0, attn_out_norm, head_v_dim * num_v_heads, n_seq_tokens * n_seqs_tok)
        : ggml_reshape_3d(ctx0, attn_out_norm, head_v_dim * num_v_heads, n_seq_tokens, n_seqs_tok);
    cb(final_output, "final_output", il);

    cur = build_lora_mm(model.layers[il].ssm_out, final_output, model.layers[il].ssm_out_s);
    cb(cur, "linear_attn_out", il);

    cur = ggml_reshape_2d(ctx0, cur, n_embd, n_seq_tokens * n_seqs_tok);
'''),
        ('''        int                  il) {
    const auto * mctx_cur = inp->mctx;

    const auto kv_head = mctx_cur->get_head();

    const int64_t n_seqs    = ubatch.n_seqs;
    const int64_t row_total = conv_states_all->ne[0];

    // the row is exactly this convolution's state, so the gather is reused as a whole
    GGML_ASSERT(state_cols * channels == row_total);

    auto it = rs_rows.find(conv_states_all);
    if (it == rs_rows.end()) {
        it = rs_rows.emplace(conv_states_all, build_rs(inp, conv_states_all, row_total, n_seqs)).first;
    }
    ggml_tensor * rows = it->second;
''',
         '''        int                  il,
        int64_t              s0,
        int64_t              n_seqs_grp) {
    const auto * mctx_cur = inp->mctx;

    // strixllama: the sequences of one group of a ragged ubatch are the sets from s0 on, in the cells from head + s0
    const auto kv_head = mctx_cur->get_head() + s0;

    const int64_t n_seqs_all = ubatch.n_seqs;
    const int64_t n_seqs     = n_seqs_grp < 0 ? n_seqs_all : n_seqs_grp;
    const int64_t row_total  = conv_states_all->ne[0];

    // the row is exactly this convolution's state, so the gather is reused as a whole
    GGML_ASSERT(state_cols * channels == row_total);

    auto it = rs_rows.find(conv_states_all);
    if (it == rs_rows.end()) {
        it = rs_rows.emplace(conv_states_all, build_rs(inp, conv_states_all, row_total, n_seqs_all)).first;
    }
    ggml_tensor * rows = it->second;
    if (n_seqs != n_seqs_all) {
        rows = ggml_view_2d(ctx0, rows, row_total, n_seqs, rows->nb[1], rows->nb[1] * s0);
    }
'''),
        ('''    // [hist + n_seq_tokens, hc_dim, n_seqs], tokens on ne[0]
    ggml_tensor * padded = build_conv_state_at(inp, inp->mctx->get_p_l(il),
            ggml_reshape_3d(ctx0, normalized, hc_dim, n_seq_tokens, n_seqs),
            hist, hc_dim, il);

    ggml_tensor * conv_out = nullptr;
    for (int64_t k = 0; k < kern; ++k) {
        // tap k reads (kern-1-k)*dilation positions back
        const int64_t start = hist - (kern - 1 - k) * dil;

        ggml_tensor * shifted = ggml_cont(ctx0,
                ggml_transpose(ctx0,
                        ggml_view_3d(ctx0, padded, n_seq_tokens, hc_dim, n_seqs,
                                padded->nb[1], padded->nb[2],
                                ggml_row_size(padded->type, start))));

        // column k of the [kern, hc_dim] kernel is one weight per channel
''',
         '''    // column k of the [kern, hc_dim] kernel is one weight per channel
    std::vector<ggml_tensor *> w_taps;
    for (int64_t k = 0; k < kern; ++k) {
'''),
        ('''
        ggml_tensor * term = ggml_mul(ctx0, shifted, wk);
        conv_out = conv_out ? ggml_add(ctx0, conv_out, term) : term;
    }
''',
         '''        w_taps.push_back(wk);
    }

    // strixllama: a ragged ubatch (llama_ubatch::ragged) runs the conv once per group of sequence sets with one token
    // count, each on its own history; an equal-length ubatch is one group
    const bool ragged = ubatch.ragged();
    std::vector<ggml_tensor *> conv_parts;
    for (const auto & g : qwen4exp_seq_groups(ubatch)) {
        const int64_t n_grp_tok  = g.n_tok;
        const int64_t n_grp_seqs = g.n_seqs;

        ggml_tensor * x_g = ragged
            ? ggml_view_3d(ctx0, normalized, hc_dim, n_grp_tok, n_grp_seqs,
                    normalized->nb[1], normalized->nb[1] * n_grp_tok, normalized->nb[1] * g.t0)
            : ggml_reshape_3d(ctx0, normalized, hc_dim, n_seq_tokens, n_seqs);

        // [hist + n_seq_tokens, hc_dim, n_seqs], tokens on ne[0]
        ggml_tensor * padded = build_conv_state_at(inp, inp->mctx->get_p_l(il), x_g,
                hist, hc_dim, il, g.s0, ragged ? n_grp_seqs : -1);

        ggml_tensor * conv_g = nullptr;
        for (int64_t k = 0; k < kern; ++k) {
            // tap k reads (kern-1-k)*dilation positions back
            const int64_t start = hist - (kern - 1 - k) * dil;

            ggml_tensor * shifted = ggml_cont(ctx0,
                    ggml_transpose(ctx0,
                            ggml_view_3d(ctx0, padded, n_grp_tok, hc_dim, n_grp_seqs,
                                    padded->nb[1], padded->nb[2],
                                    ggml_row_size(padded->type, start))));

            ggml_tensor * term = ggml_mul(ctx0, shifted, w_taps[k]);
            conv_g = conv_g ? ggml_add(ctx0, conv_g, term) : term;
        }
        conv_parts.push_back(conv_g);
    }

    ggml_tensor * conv_out = ragged ? qwen4exp_concat_groups(ctx0, conv_parts, hc_dim) : conv_parts[0];
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
