#!/usr/bin/env python3
"""Host buffers pad and zero quantized rows like device buffers

With experts in system memory (-ot ...=ROCm_Host, the manager's placement at a small carve), MMQ read the 640-wide down experts' last row past its end into the next tensor and took those bytes as block scales: every batch it ran (17 tokens up) came out NaN. Host buffers now pad quantized rows to MATRIX_ROW_PADDING and zero the padding, as device buffers do. At the 64 GB carve with 16 layers' experts in system memory the f16, MTP and q8_0 probes give 0.4.4's bits.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 3 hunks across 1 file(s).

Usage: python patches/apply_host_buft_padding.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'ggml_backend_cuda_host_buffer_type_get_alloc_size'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ggml-cuda.cu"): [
        ('''
static ggml_backend_buffer_t ggml_backend_cuda_host_buffer_type_alloc_buffer(ggml_backend_buffer_type_t buft, size_t size) {
''',
         '''
// strixllama: an integrated GPU computes on tensors in its host buffers in place (supports_buft), so quantized weights
// there need what a device buffer gives them: rows padded to MATRIX_ROW_PADDING, the padding zeroed. MMQ reads each
// matrix's last row that far; without it, with experts in system memory (-ot ...=ROCm_Host), the 640-wide down experts
// read the next tensor's bytes as block scales and every batch MMQ took (17 tokens up) came out NaN
static size_t ggml_backend_cuda_host_buffer_type_get_alloc_size(ggml_backend_buffer_type_t buft, const ggml_tensor * tensor) {
    size_t size = ggml_nbytes(tensor);
    if (ggml_is_quantized(tensor->type) && tensor->ne[0] % MATRIX_ROW_PADDING != 0) {
        size += ggml_row_size(tensor->type, MATRIX_ROW_PADDING - tensor->ne[0] % MATRIX_ROW_PADDING);
    }
    return size;

    GGML_UNUSED(buft);
}

static enum ggml_status ggml_backend_cuda_host_buffer_init_tensor(ggml_backend_buffer_t buffer, ggml_tensor * tensor) {
    if (tensor->view_src == nullptr && ggml_is_quantized(tensor->type) &&
            ggml_backend_buffer_get_usage(buffer) != GGML_BACKEND_BUFFER_USAGE_COMPUTE) {
        const size_t original_size = ggml_nbytes(tensor);
        const size_t padded_size   = ggml_backend_buft_get_alloc_size(buffer->buft, tensor);
        if (padded_size > original_size) {
            memset((char *) tensor->data + original_size, 0, padded_size - original_size);
        }
    }
    return GGML_STATUS_SUCCESS;
}

static ggml_backend_buffer_t ggml_backend_cuda_host_buffer_type_alloc_buffer(ggml_backend_buffer_type_t buft, size_t size) {
'''),
        ('''    buffer->iface.free_buffer = ggml_backend_cuda_host_buffer_free_buffer;

''',
         '''    buffer->iface.free_buffer = ggml_backend_cuda_host_buffer_free_buffer;
    buffer->iface.init_tensor = ggml_backend_cuda_host_buffer_init_tensor;

'''),
        ('''            /* .get_alloc_size   = */ ggml_backend_cpu_buffer_type()->iface.get_alloc_size,
''',
         '''            /* .get_alloc_size   = */ ggml_backend_cuda_host_buffer_type_get_alloc_size,
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
