#!/usr/bin/env python3
"""A ubatch of 33-127 queries a sequence reads the sparse selection; a maskless op with indices never reaches a kernel that ignores them

Between the decode gather (<= 32 queries) and the qsa3 prefill kernel (>= 128) the selected blocks went to the generic flash attention with the plain causal mask, which ignores them: dense attention over every visible cell instead of the model's sparse attention, for tool results and short follow-ups at depth. Such ubatches now take the top-k and the top-k mask. fattn.cu aborts when a maskless op with selected indices would reach a generic kernel - the class of 0.2.7's wide-window bug fails loudly instead of computing dense.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 5 hunks across 2 file(s).

Usage: python patches/apply_qsa_between_029.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'qwen4exp_qsa_between_kernels'

EDITS = {
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''
static bool qwen4exp_use_block_selection(bool blk_bias, int64_t n_stream, int64_t ratio, int64_t n_kv,
''',
         '''
// strixllama: the most queries the decode gather takes (qwen4exp_gather_attn); 32 covers eight slots verifying a draft
// of 3 each, and above that the gather reads more than it saves
static int64_t qwen4exp_gather_max_t() {
    static const int64_t v = getenv("LLAMA_QSA_DECODE_GATHER_MAX_T") ? (int64_t) atoll(getenv("LLAMA_QSA_DECODE_GATHER_MAX_T")) : 32;
    return v;
}

// strixllama: a ubatch between the two kernels that read the selected indices - more queries than the decode gather
// takes, fewer than the 128 the qsa3 prefill kernel needs. The selection went to the generic flash attention with the
// plain causal mask, which ignores it: dense attention over every visible cell instead of the model's sparse one.
// Such a ubatch takes the plain top-k and the top-k mask instead (the block selection's -1 sentinels are for the
// kernels only; the mask's set_rows cannot take them)
static bool qwen4exp_qsa_between_kernels(int64_t n_tps) {
    return n_tps > qwen4exp_gather_max_t() && n_tps < 128;
}

static bool qwen4exp_use_block_selection(bool blk_bias, int64_t n_stream, int64_t ratio, int64_t n_kv,
'''),
        ('''    return block_env && atoi(block_env)!=0 && direct_env && atoi(direct_env)!=0 &&
        blk_bias && n_stream==1 && ratio>1 && hparams.indexer_top_k%ratio==0 &&
''',
         '''    return block_env && atoi(block_env)!=0 && direct_env && atoi(direct_env)!=0 &&
        n_stream > 0 && !qwen4exp_qsa_between_kernels(ubatch.n_tokens / n_stream) &&
        blk_bias && n_stream==1 && ratio>1 && hparams.indexer_top_k%ratio==0 &&
'''),
        ('''        const bool direct_indices = direct_env && atoi(direct_env) != 0 &&
''',
         '''        const bool direct_indices = direct_env && atoi(direct_env) != 0 && !qwen4exp_qsa_between_kernels(n_tps) &&
'''),
        ('''        // 32 covers eight slots verifying a draft of 3 each; above that the gather reads more than it saves
        static const int64_t gather_max_t = []() {
            const char * e = getenv("LLAMA_QSA_DECODE_GATHER_MAX_T");
            return e ? (int64_t) atoll(e) : (int64_t) 32;
        }();
''',
         '''        const int64_t gather_max_t = qwen4exp_gather_max_t();
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "fattn.cu"): [
        ('''    }
    switch (ggml_cuda_get_best_fattn_kernel(ggml_cuda_get_device(), dst)) {
''',
         '''    }
    // strixllama: selected indices without a mask are for the qsa3 kernel alone. The kernels below ignore src[5], and
    // without the mask they attend to every cell of the window - later positions and other conversations included,
    // as 0.2.7's prompt chunks next to answering conversations did. Fail here rather than compute that
    if (dst->src[5] != nullptr && dst->src[3] == nullptr) {
        GGML_ABORT("QSA: a maskless attention op with selected indices reached a kernel that ignores them (q %lld x k %lld)",
                   (long long) dst->src[0]->ne[1], (long long) dst->src[1]->ne[1]);
    }
    switch (ggml_cuda_get_best_fattn_kernel(ggml_cuda_get_device(), dst)) {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
