#!/usr/bin/env python3
"""TOP_K: the one-pass row kernel from one row up.

The QSA decode's TOP_K has a row a query; below 32 rows it took the parallel radix path, a dozen launches (~340 us a strip at eight conversations).

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 1 hunks across 1 file(s).

Usage: python patches/apply_top_k_rows_036.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_TOP_K_ROWS_MIN'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "top-k.cu"): [
        ('''    if (!on || nrows < 32 || nrows > 65535 || ncols <= 1024 || k < 1 || k > ncols || ncols > 128 * bs) {
''',
         '''    // strixllama: from one row up (it took 32 and more): the QSA decode's TOP_K has a row a query - eight conversations
    // are eight rows of ~20-40K blocks - and top_k_parallel_radix_cuda's dozen launches cost ~340 us a strip there against
    // ~10 us here (a step at 8 x 20K 103 -> 97.6 ms); one conversation, at 110K or 210K, is unchanged. The same set either
    // way (see above). STRIX_TOP_K_ROWS_MIN=32 restores the old bound.
    static const int  min_rows = getenv("STRIX_TOP_K_ROWS_MIN") ? atoi(getenv("STRIX_TOP_K_ROWS_MIN")) : 1;
    if (!on || nrows < min_rows || nrows > 65535 || ncols <= 1024 || k < 1 || k > ncols || ncols > 128 * bs) {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
