#!/usr/bin/env python3
"""PLE reads: wake the drive ahead of a decode step's gather.

The drive and its link drop to a low-power state within ~1 ms of idle, and the first read after that takes ~640 us instead of ~150 (tmp/dec041/ssd_latency.cpp; polling the completion instead of waiting changes nothing, so it is the drive, not a sleeping core). A decode step's PLE gather (16 n-gram rows a token) nearly always misses a row or two of the RAM cache - new n-grams - so every step paid the wake-up with the GPU idle: a gather with no miss took 0.0-0.1 ms, with one 0.7. llama_lazy_reader::wake() reads one page ahead of it, fire and forget, when a small batch's GPU work is synchronized and when the next small batch starts. At 8 conversations the gather went 0.80 -> 0.45 ms. STRIX_PLE_WAKE=0: off.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 6 hunks across 3 file(s).

Usage: python patches/apply_ple_wake_041.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'qwen4exp_ple_wake'

EDITS = {
    os.path.join(tree, "src", "llama-lazy-reader.h"): [
        ('''
    void run_range_unbuffered(const std::vector<std::pair<int32_t, int32_t>> & pairs,
''',
         '''
    // strixllama: the drive and its link drop to a low-power state within ~1 ms of idle; the first read after that
    // takes ~640 us instead of ~150 (tmp/dec041/ssd_latency.cpp). A decode step's gather nearly always misses a row and
    // starts ~0.5-1.5 ms after the GPU step ends, with the GPU idle: wake() reads one page ahead of it, so its reads find
    // the drive up. Fire and forget; a wake still in flight is left alone. STRIX_PLE_WAKE=0: off
    mutable std::mutex wake_mutex;
    mutable OVERLAPPED wake_ov{};
    mutable HANDLE     wake_event   = nullptr;
    mutable uint8_t *  wake_buf     = nullptr;
    mutable bool       wake_pending = false;

    void wake() const {
        static const bool off = getenv("STRIX_PLE_WAKE") && atoi(getenv("STRIX_PLE_WAKE")) == 0;
        if (off || !unbuffered) {
            return;
        }
        std::lock_guard<std::mutex> lock(wake_mutex);
        if (wake_pending) {
            if (!HasOverlappedIoCompleted(&wake_ov)) {
                return;
            }
            DWORD got = 0;
            GetOverlappedResult(fd, &wake_ov, &got, FALSE);
            wake_pending = false;
        }
        if (!wake_buf) {
            wake_buf   = (uint8_t *) _aligned_malloc(UNBUF_PAGE, UNBUF_PAGE);
            wake_event = CreateEventW(nullptr, TRUE, FALSE, nullptr);
            if (!wake_buf || !wake_event) {
                return;
            }
        }
        const uint64_t p0 = (uint64_t) base / UNBUF_PAGE * UNBUF_PAGE;
        wake_ov = {};
        wake_ov.Offset     = (DWORD) p0;
        wake_ov.OffsetHigh = (DWORD) (p0 >> 32);
        wake_ov.hEvent     = wake_event;
        ResetEvent(wake_event);
        if (ReadFile(fd, wake_buf, (DWORD) UNBUF_PAGE, nullptr, &wake_ov) || GetLastError() == ERROR_IO_PENDING) {
            wake_pending = true;
        }
    }

    void run_range_unbuffered(const std::vector<std::pair<int32_t, int32_t>> & pairs,
'''),
        ('''    using file_handle = int;
#endif
''',
         '''    using file_handle = int;
    void wake() const {}
#endif
'''),
        ('''        if (prefetch_thread.joinable()) {
            prefetch_thread.join();
        }
        if (fd != INVALID_HANDLE_VALUE) {
''',
         '''        if (prefetch_thread.joinable()) {
            prefetch_thread.join();
        }
        // a wake-up read still in flight writes its buffer until it completes
        if (wake_pending) {
            DWORD got = 0;
            GetOverlappedResult(fd, &wake_ov, &got, TRUE);
        }
        if (wake_buf) {
            _aligned_free(wake_buf);
        }
        if (wake_event) {
            CloseHandle(wake_event);
        }
        if (fd != INVALID_HANDLE_VALUE) {
'''),
    ],
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''
void llm_graph_input_ple::set_input(const llama_ubatch * ubatch) {
''',
         '''
// strixllama: wake the drive the PLE rows are read from ahead of a small batch's gather (llama_lazy_reader::wake);
// llama_context calls it for every model
void qwen4exp_ple_wake(const llama_model & model_base) {
    if (model_base.arch != LLM_ARCH_QWEN4EXP) {
        return;
    }
    const auto & pmodel = static_cast<const llama_model_qwen4exp &>(model_base);
    if (pmodel.ple_reader) {
        pmodel.ple_reader->wake();
    }
}

void llm_graph_input_ple::set_input(const llama_ubatch * ubatch) {
'''),
    ],
    os.path.join(tree, "src", "llama-context.cpp"): [
        ('''    ggml_backend_sched_synchronize(sched.get());

''',
         '''    ggml_backend_sched_synchronize(sched.get());

    // strixllama: a small batch's GPU work is done; the next one's PLE gather will want the drive up
    if (n_queued_tokens > 0 && n_queued_tokens <= 64) {
        extern void qwen4exp_ple_wake(const llama_model & model);
        qwen4exp_ple_wake(model);
    }

'''),
        ('''    // so accept either present rather than requiring exactly one.
    GGML_ASSERT(batch_inp.token || batch_inp.embd);

    if (!memory) {
''',
         '''    // so accept either present rather than requiring exactly one.
    GGML_ASSERT(batch_inp.token || batch_inp.embd);

    // strixllama: a small batch's PLE gather comes after the batch preparation: wake the drive now
    if (batch_inp.n_tokens > 0 && batch_inp.n_tokens <= 64) {
        extern void qwen4exp_ple_wake(const llama_model & model);
        qwen4exp_ple_wake(model);
    }

    if (!memory) {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
