#!/usr/bin/env python3
"""0.5.5 -> 0.5.6: a tool whose parameters are alternatives that each require one is not called with none.

common_tool_parameters_flatten lists the parameters of oneOf / anyOf alternatives together, each required only where
every alternative requires it - none for Deep Rulith's OpenCase (caseType or caseId) - and the Qwen3-Coder grammar
then allowed a call with no parameter, which every alternative rejects; the model made it twice at 260K tokens of
context (10-09). When every alternative requires something the flat schema carries minProperties: 1, and a tool with
no required parameter but minProperties >= 1 takes at least one in the grammar. Checked: the grammar for OpenCase, and
a call that names its caseType.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 8 hunks across 2 file(s).

Usage: python patches/apply_tool_params_056.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'bool                                  need_one = false;'

EDITS = {
    os.path.join(tree, "common", "json-schema-to-grammar.cpp"): [
        ('''    std::set<std::string>                 forbidden;
    std::function<void(const json &, bool, int)> collect = [&](const json & s0, bool is_required, int depth) {
''',
         '''    std::set<std::string>                 forbidden;
    // strixllama: alternatives that each require a property, but no property in all of them (OpenCase: caseType or
    // caseId) - the flat list requires none, and the grammar let a call through with no parameter at all, which
    // every alternative rejects. minProperties: 1 on the flat schema keeps that much (issue: Deep Rulith, 10-09)
    bool                                  need_one = false;
    std::function<void(const json &, bool, int)> collect = [&](const json & s0, bool is_required, int depth) {
'''),
        ('''            size_t n_alt = 0;
''',
         '''            size_t n_alt = 0, n_alt_req = 0;
'''),
        ('''                collect(alt, false, depth + 1);
                if (alt.contains("required") && alt.at("required").is_array()) {
''',
         '''                collect(alt, false, depth + 1);
                bool alt_req = alt.contains("minProperties") && alt.at("minProperties").is_number() &&
                               alt.at("minProperties").get<double>() >= 1;
                if (alt.contains("required") && alt.at("required").is_array()) {
'''),
        ('''                            n_req[r.get<std::string>()]++;
                        }
''',
         '''                            n_req[r.get<std::string>()]++;
                            alt_req = true;
                        }
'''),
        ('''                    }
                }
            }
            if (is_required) {
''',
         '''                    }
                }
                n_alt_req += alt_req ? 1 : 0;
            }
            if (is_required) {
'''),
        ('''                        required.insert(k);
                    }
                }
            }
''',
         '''                        required.insert(k);
                    }
                }
                if (n_alt > 0 && n_alt_req == n_alt) {
                    need_one = true;
                }
            }
'''),
        ('''    out["required"]   = r;
    return out;
''',
         '''    out["required"]   = r;
    if (need_one && r.empty() && !p.empty() &&
            !(out.contains("minProperties") && out.at("minProperties").is_number() && out.at("minProperties").get<double>() >= 1)) {
        out["minProperties"] = 1;
    }
    return out;
'''),
    ],
    os.path.join(tree, "common", "parsers", "qwen3-coder.cpp"): [
        ('''                    args = args + p.zero_or_more(p.choice(optional_args));
''',
         '''                    // strixllama: none required, but the schema takes no empty call (minProperties, e.g. alternatives
                    // that each require one): at least one parameter. Deep Rulith's OpenCase came through empty twice
                    const json flat = common_tool_parameters_flatten(parameters);
                    const bool need_one = required_args.empty() && flat.is_object() && flat.contains("minProperties") &&
                                          flat.at("minProperties").is_number() && flat.at("minProperties").get<double>() >= 1;
                    args = need_one ? args + p.choice(optional_args) + p.zero_or_more(p.choice(optional_args))
                                    : args + p.zero_or_more(p.choice(optional_args));
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
