#!/usr/bin/env python3
"""0.4.3: prompt-processing fusions and the PLE pregather

Shorter prompts paid fixed costs and three avoidable memory passes: the shared expert's gating and add after the routed experts' weighted sum, the F32 copy of the hyper-connection streams, the GDN q/k scale after their norm; the expert ids went through a single-wave helper up to 4096 tokens; a prompt's PLE rows were read with the GPU idle for its first chunk and for chunks under 4096 tokens. All bitwise 0.4.2.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 81 hunks across 17 file(s).

Usage: python patches/apply_prefill_043.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'STRIX_SHEXP_TAIL'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ggml-cuda.cu"): [
        ('''// the 5-argument form lives in this backend's own moe-weighted-reduction.cu (shared-expert merge folded in)
''',
         '''// the 5-argument form lives in this backend's own moe-weighted-reduction.cu (shared-expert merge folded in; the gated
// shared expert's tail as well)
'''),
        ('''                                         ggml_tensor * dst, const ggml_tensor * merge);
''',
         '''                                         ggml_tensor * dst, const ggml_tensor * merge, const ggml_tensor * shexp,
                                         const ggml_tensor * sgate);
'''),
        ('''    if (it == g_strix_tl.end() || it->second.rows >= 64 || it->second.keys.empty()) {
''',
         '''    static const int64_t tl_rows = getenv("STRIX_GPU_TIMELINE_ROWS") ? atoll(getenv("STRIX_GPU_TIMELINE_ROWS")) : 64;   // DEV: prompt graphs too
    if (it == g_strix_tl.end() || it->second.rows >= tl_rows || it->second.keys.empty()) {
'''),
        ('''
static bool ggml_cuda_can_fuse(const struct ggml_cgraph *                cgraph,
''',
         '''
// strixllama (STRIX_HC_XRES): whether the combine's F32 normalised streams have a reader left. The HC down GEMM reads the
// BF16 copy, the inject is folded into the combine (inject_plan), and the gate GEMM's fused mix, which with Q8_0 weights
// reads the F32 streams, can form them again from the combine's F32 residual output, the per-row scale it then stores and
// gamma - the same two products in the same order, so the same bits. With no other reader the combine stops writing
// them: 40 KB a token per combine, two combines a layer
static void ggml_cuda_hc_xres_plan(const ggml_cgraph * graph, const int last, ggml_cuda_hc_combine_norm_args & args,
        ggml_backend_cuda_context & ctx) {
    static const bool on = !getenv("STRIX_HC_XRES") || atoi(getenv("STRIX_HC_XRES")) != 0;
    ggml_cuda_hc_xres_set(nullptr, nullptr, nullptr, nullptr);
    const ggml_tensor * xn = args.out_xn;
    const int64_t hc = args.out_res->ne[1], T = args.out_res->ne[2];
    if (!on || !args.store_xn_f32 || !args.out_xn_bf16 || args.res_out_bf16 || hc != 4 || T < 512 ||
            args.out_res->type != GGML_TYPE_F32 || args.gamma->type != GGML_TYPE_F32 || !ggml_is_contiguous(args.out_res) ||
            !ggml_is_contiguous(args.gamma) || xn->type != GGML_TYPE_F32 || !ggml_cuda_hc_cn_b256(args)) {
        return;
    }
    bool formed = false;
    int nread = 0;
    for (int n = last + 1; n < graph->n_nodes; ++n) {
        const ggml_tensor * t = graph->nodes[n];
        bool reads = false;
        for (int s = 0; s < GGML_MAX_SRC && t->src[s]; ++s) {
            if (t->src[s] == xn || t->src[s]->view_src == xn) { reads = true; }
        }
        if (!reads) {
            continue;
        }
        ++nread;
        if (g_hc_inject.node == t) {
            continue;                       // the inject, folded into the combine
        }
        if (t->op == GGML_OP_MUL_MAT && t->src[1] == xn && ggml_cuda_mmb_supported_mm(t->src[0], t->src[1], t)) {
            continue;                       // the HC down GEMM: the BF16 copy
        }
        if (t->op == GGML_OP_MUL && n >= 2) {
            ggml_cuda_hc_mix_args ma;
            const ggml_tensor * g = graph->nodes[n - 2];
            bool f32 = false;
            if (ggml_cuda_hc_mix_closed(graph, n - 1, ma) > 0 && ma.xn == xn && ma.gate == g && g->op == GGML_OP_MUL_MAT &&
                    g->src[0]->ne[0] == 320 && g->src[0]->ne[1] == 10240 && ggml_node_has_n_uses(graph, n - 2, 1) &&
                    ggml_cuda_mmb_supported_mm(g->src[0], g->src[1], g) &&
                    ggml_cuda_hc_gate_mix_ok(g->src[0], g->src[1], xn, ma.dst, ma.hc, &f32)) {
                formed = formed || f32;
                continue;                   // the gate GEMM's fused mix
            }
        }
        return;                             // another reader: the F32 streams stay
    }
    if (nread == 0) {
        return;
    }
    args.store_xn_f32 = false;
    if (formed) {
        args.row_scale = ggml_cuda_hc_row_scale_buf(ctx);
        ggml_cuda_hc_xres_set(xn->data, (const float *) args.out_res->data, args.row_scale, (const float *) args.gamma->data);
    }
    static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "HC_CN no F32 streams (%s): T=%lld\\n", formed ? "the mix forms them" : "no F32 reader", (long long) T);
}

static bool ggml_cuda_can_fuse(const struct ggml_cgraph *                cgraph,
'''),
        ('''        if (sk > 0) { ggml_cuda_op_norm_gated(*cuda_ctx, nm); return sk; }
    }
''',
         '''        if (sk > 0) { ggml_cuda_op_norm_gated(*cuda_ctx, nm); return sk; }
        ggml_cuda_norm_scale_match sm;
        if (ggml_cuda_norm_scale_match_at(cgraph, i, sm) > 0) { ggml_cuda_op_norm_scale(*cuda_ctx, sm); return 1; }
    }
'''),
        ('''            ggml_cuda_hc_inject_plan(cgraph, i + skip, args, *cuda_ctx);
            ggml_cuda_op_hc_combine_norm(*cuda_ctx, args);
''',
         '''            ggml_cuda_hc_inject_plan(cgraph, i + skip, args, *cuda_ctx);
            ggml_cuda_hc_xres_plan(cgraph, i + skip, args, *cuda_ctx);
            ggml_cuda_op_hc_combine_norm(*cuda_ctx, args);
'''),
        ('''        if (ggml_cuda_match_moe_weighted_reduction(cgraph, i, match)) {
            int count = match.node_count;
''',
         '''        if (ggml_cuda_match_moe_weighted_reduction(cgraph, i, match)) {
            // strixllama: the shared expert's tail right after the weighted sum - MUL(shexp, sigmoid gate [1, T]), ADD(sum,
            // that) - in the same kernel (qwen4exp builds the shared expert first for prompt-sized batches so that the
            // two follow the sum): the sum and the gated shared expert are no longer written out and read back, bitwise
            // the same (moe_shexp_tail). STRIX_SHEXP_TAIL=0: off
            static const bool shexp_tail = !getenv("STRIX_SHEXP_TAIL") || atoi(getenv("STRIX_SHEXP_TAIL")) != 0;
            const int im = i + match.node_count, ia = im + 1;
            if (shexp_tail && ia < cgraph->n_nodes && !ggml_cuda_mmb_is_bf16_only(match.dst)) {
                const ggml_tensor * mul = cgraph->nodes[im];
                ggml_tensor *       add = cgraph->nodes[ia];
                const ggml_tensor * sx  = mul->op == GGML_OP_MUL ? mul->src[0] : nullptr;
                const ggml_tensor * sg  = mul->op == GGML_OP_MUL ? mul->src[1] : nullptr;
                const bool shape_ok = sx && sg && add->op == GGML_OP_ADD &&
                    ((add->src[0] == match.dst && add->src[1] == mul) || (add->src[1] == match.dst && add->src[0] == mul)) &&
                    mul->type == GGML_TYPE_F32 && add->type == GGML_TYPE_F32 && sx->type == GGML_TYPE_F32 && sg->type == GGML_TYPE_F32 &&
                    ggml_is_contiguous(sx) && ggml_is_contiguous(sg) && ggml_is_contiguous(add) && ggml_is_contiguous(mul) &&
                    ggml_are_same_shape(sx, match.dst) && ggml_are_same_shape(add, match.dst) && ggml_are_same_shape(mul, match.dst) &&
                    sg->ne[0] == 1 && sg->ne[1] == match.dst->ne[1] && sg->ne[2] == 1 && sg->ne[3] == 1 &&
                    match.dst->ne[0] % 4 == 0;
                if (shape_ok && ggml_node_has_n_uses(cgraph, im - 1, 1) && ggml_node_has_n_uses(cgraph, im, 1)) {
                    const int count = match.node_count + 2;
                    if (ggml_cuda_check_fusion_memory_ranges(cgraph, i, count, &ia, 1)) {
                        ggml_cuda_op_moe_weighted_reduction(*cuda_ctx, match.experts, match.expert_scale, match.weights, add,
                                                            nullptr, sx, sg);
                        return count - 1;
                    }
                }
            }
            int count = match.node_count;
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "hc-cn.cu"): [
        ('''        const float * __restrict__ inj_w, float * __restrict__ inj_part) {
''',
         '''        const float * __restrict__ inj_w, float * __restrict__ inj_part, float * __restrict__ row_scale) {
'''),
        ('''    const float scale = rsqrtf(mean + eps);
    const float * g  = gamma  + (int64_t) c * n_embd;
''',
         '''    const float scale = rsqrtf(mean + eps);
    if (row_scale && tid == 0) {
        row_scale[row] = scale;
    }
    const float * g  = gamma  + (int64_t) c * n_embd;
'''),
        ('''            (int) n_embd, a.s1, a.b1, a.s2, a.b2, a.eps, a.inject_w, a.inject_part);
''',
         '''            (int) n_embd, a.s1, a.b1, a.s2, a.b2, a.eps, a.inject_w, a.inject_part, a.row_scale);
'''),
        ('''    }
    const ggml_cuda_kernel_launch_params launch_params(dim3((int) hc, (int) n_tokens, 1), HC_CN_BLOCK, 0, ctx.stream());
''',
         '''    }
    GGML_ASSERT(!a.row_scale && "the per-row scale is the 256-thread kernel's");
    const ggml_cuda_kernel_launch_params launch_params(dim3((int) hc, (int) n_tokens, 1), HC_CN_BLOCK, 0, ctx.stream());
'''),
        ('''// a captured graph; released with the backend (ggml_cuda_hc_release)
static ggml_cuda_pool_alloc<float> * g_hc_inject_part = nullptr;
''',
         '''// a captured graph; released with the backend (ggml_cuda_hc_release)
bool ggml_cuda_hc_cn_b256(const ggml_cuda_hc_combine_norm_args & a) {
    static const int shape = getenv("LLAMA_HC_CN_SHAPE") ? atoi(getenv("LLAMA_HC_CN_SHAPE")) : 0;
    return shape == 1 && a.out_res->ne[0] % 2 == 0 && a.out_res->ne[3] == 1 && a.out_res->ne[1] <= 4 &&
        a.out_res->ne[2] * a.out_res->ne[1] <= (int64_t) HC_INJ_MAX_T * 4;
}

static ggml_cuda_pool_alloc<float> * g_hc_row_scale = nullptr;
float * ggml_cuda_hc_row_scale_buf(ggml_backend_cuda_context & ctx) {
    if (!g_hc_row_scale) {
        g_hc_row_scale = new ggml_cuda_pool_alloc<float>(ctx.pool(), (size_t) HC_INJ_MAX_T * 4);
    }
    return g_hc_row_scale->get();
}

static ggml_cuda_pool_alloc<float> * g_hc_inject_part = nullptr;
'''),
        ('''    g_hc_inject_part = nullptr;
}
''',
         '''    g_hc_inject_part = nullptr;
    delete g_hc_row_scale;
    g_hc_row_scale = nullptr;
}
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "hc-cn.cuh"): [
        ('''    float *             inject_part  = nullptr;   // its per-stream partial dot products [T][hc][4]
};
''',
         '''    float *             inject_part  = nullptr;   // its per-stream partial dot products [T][hc][4]
    float *             row_scale    = nullptr;   // strixllama: each row's rsqrt(mean(x^2) + eps) [T * hc] (STRIX_HC_XRES)
};
'''),
        ('''void ggml_cuda_hc_release();
''',
         '''void ggml_cuda_hc_release();
// strixllama: the combine kernel the per-row scale needs (LLAMA_HC_CN_SHAPE=1), and a buffer for the scales
bool ggml_cuda_hc_cn_b256(const ggml_cuda_hc_combine_norm_args & args);
float * ggml_cuda_hc_row_scale_buf(ggml_backend_cuda_context & ctx);
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmb.cu"): [
        ('''template <int HC, int WTYPE = 0, bool XF32 = false>
__global__ void __launch_bounds__(MMB_NT, 2)
hc_gate_mix_kernel(const uint8_t * __restrict__ W, const uint16_t * __restrict__ Lo, const uint16_t * __restrict__ Xn,
        const float * __restrict__ XnF, float * __restrict__ Out,
        uint16_t * __restrict__ OutH, const bool store_f32,
        const int E, const int K, const int T, const float scale, const float bias, const int64_t xn_ld = 0) {
''',
         '''// XRES (strixllama): the F32 streams formed from the combine's F32 residual output Res, its per-row scale Rs and gamma
// Gm - x * scale * gamma, the combine's own two products in its order - instead of read back from a copy it wrote
template <int HC, int WTYPE = 0, bool XF32 = false, bool XRES = false>
__global__ void __launch_bounds__(MMB_NT, 2)
hc_gate_mix_kernel(const uint8_t * __restrict__ W, const uint16_t * __restrict__ Lo, const uint16_t * __restrict__ Xn,
        const float * __restrict__ XnF, float * __restrict__ Out,
        uint16_t * __restrict__ OutH, const bool store_f32,
        const int E, const int K, const int T, const float scale, const float bias, const int64_t xn_ld = 0,
        const float * __restrict__ Res = nullptr, const float * __restrict__ Rs = nullptr, const float * __restrict__ Gm = nullptr) {
'''),
        ('''            if constexpr (XF32) {
''',
         '''            if constexpr (XRES) {
                const float * rr = Res + (size_t)t * ((size_t)HC * E) + ch;
#pragma unroll
                for (int c = 0; c < HC; ++c) {
                    const float v    = gm_mul_rn(gm_mul_rn(Rs[(size_t)t * HC + c], rr[(size_t)c * E]), Gm[(size_t)c * E + ch]);
                    const float term = gm_mul_rn(v, gm_sigmoid(acc[c][j][e]));
                    s = (c == 0) ? term : gm_add_rn(s, term);
                }
            } else if constexpr (XF32) {
'''),
        ('''
// strixllama: ld - the copy's row stride in elements when its rows are padded (mmb_pad_ld), else 0 (rows of K)
''',
         '''
// strixllama: three tile classes - an expert of up to BN_SMALL rows gets one BN_SMALL-row tile, of up to BN_MID one
// BN_MID-row tile, a bigger one BN_BIG-row tiles. A tile reads its expert's weights once whatever its width, so an
// expert under BN_BIG rows in BN_SMALL tiles read them up to four times: at 2K tokens (median 31 rows an expert) the
// routed down projection read its weights 1.59 times an expert, here 1.15. Every row sees the same WMMA sequence in
// any class, so results do not depend on the split.
__global__ void mmb_build_desc3(const int32_t * __restrict__ bounds, uint32_t * __restrict__ desc_big, uint32_t * __restrict__ desc_mid,
        uint32_t * __restrict__ desc_small, const int E, const int nbig_max, const int nmid_max, const int nsmall_max,
        const int BN_BIG, const int BN_MID, const int BN_SMALL) {
    __shared__ int sb[1024], sm[1024], ss[1024];
    const int e = threadIdx.x;
    for (int i = e; i < nbig_max;   i += blockDim.x) desc_big[i]   = UINT32_MAX;
    for (int i = e; i < nmid_max;   i += blockDim.x) desc_mid[i]   = UINT32_MAX;
    for (int i = e; i < nsmall_max; i += blockDim.x) desc_small[i] = UINT32_MAX;
    const int cnt = (e < E) ? bounds[e + 1] - bounds[e] : 0;
    const int tb = cnt > BN_MID ? (cnt + BN_BIG - 1) / BN_BIG : 0;
    const int tm = cnt > BN_SMALL && cnt <= BN_MID ? 1 : 0;
    const int ts = cnt > 0 && cnt <= BN_SMALL ? 1 : 0;
    sb[e] = tb; sm[e] = tm; ss[e] = ts;
    __syncthreads();
    for (int off = 1; off < 1024; off <<= 1) {
        const int vb = (e >= off) ? sb[e - off] : 0, vm = (e >= off) ? sm[e - off] : 0, vs = (e >= off) ? ss[e - off] : 0;
        __syncthreads();
        sb[e] += vb; sm[e] += vm; ss[e] += vs;
        __syncthreads();
    }
    const int bb = sb[e] - tb, bm = sm[e] - tm, bs = ss[e] - ts;
    for (int jt = 0; jt < tb; ++jt) { const int idx = bb + jt; if (idx < nbig_max) desc_big[idx] = (uint32_t)e | ((uint32_t)jt << 16); }
    if (tm && bm < nmid_max)   desc_mid[bm]   = (uint32_t)e;
    if (ts && bs < nsmall_max) desc_small[bs] = (uint32_t)e;
}
static bool mmb_down_tiles3() { static const bool v = !getenv("STRIX_MMB_DOWN_TILES") || atoi(getenv("STRIX_MMB_DOWN_TILES")) != 2; return v; }

// strixllama: ld - the copy's row stride in elements when its rows are padded (mmb_pad_ld), else 0 (rows of K)
'''),
        ('''bool ggml_cuda_hc_gate_mix(ggml_backend_cuda_context & ctx, const ggml_tensor * w, const ggml_tensor * lo, const ggml_tensor * xn, ggml_tensor * dst,
        const int hc, const float scale, const float bias) {
    // strixllama: Q8_0 too - Unsloth's file keeps the HC weights at Q8_0, so with IQ4_NL only this never fired there
    const bool q8 = w->type == GGML_TYPE_Q8_0;
    if (!mmb_gatemix_flag() || hc != 4 || (w->type != GGML_TYPE_IQ4_NL && !q8) || lo->type != GGML_TYPE_F32 || !ggml_is_contiguous(lo) || !ggml_is_contiguous(dst)) return false;
    const int K = (int) w->ne[0], M = (int) w->ne[1], E = (int) dst->ne[0]; const int T = (int) ggml_nrows(dst);
    if (K % MMB_BK != 0 || M != hc * E || E % 32 != 0 || lo->ne[0] != K || ggml_nrows(lo) != T || xn->ne[0] != M || ggml_nrows(xn) != T || T < mmb_min_t()) return false;
''',
         '''struct mmb_xres_entry { const void * xn_data; const float * res; const float * rs; const float * gamma; };
static mmb_xres_entry g_mmb_xres = { nullptr, nullptr, nullptr, nullptr };
void ggml_cuda_hc_xres_set(const void * xn_data, const float * res, const float * row_scale, const float * gamma) {
    g_mmb_xres = { xn_data, res, row_scale, gamma };
}

bool ggml_cuda_hc_gate_mix_ok(const ggml_tensor * w, const ggml_tensor * lo, const ggml_tensor * xn, const ggml_tensor * dst, const int hc, bool * f32) {
    // strixllama: Q8_0 too - Unsloth's file keeps the HC weights at Q8_0, so with IQ4_NL only this never fired there
    const bool q8 = w->type == GGML_TYPE_Q8_0;
    if (!mmb_gatemix_flag() || hc != 4 || (w->type != GGML_TYPE_IQ4_NL && !q8) || lo->type != GGML_TYPE_F32 || !ggml_is_contiguous(lo) || !ggml_is_contiguous(dst)) return false;
    const int K = (int) w->ne[0], M = (int) w->ne[1], E = (int) dst->ne[0]; const int T = (int) ggml_nrows(dst);
    if (K % MMB_BK != 0 || M != hc * E || E % 32 != 0 || lo->ne[0] != K || ggml_nrows(lo) != T || xn->ne[0] != M || ggml_nrows(xn) != T || T < mmb_min_t()) return false;
    if (f32) { *f32 = q8 && xn->type == GGML_TYPE_F32 && ggml_is_contiguous(xn) && !ggml_cuda_mmb_is_bf16_only(xn); }
    return true;
}

bool ggml_cuda_hc_gate_mix(ggml_backend_cuda_context & ctx, const ggml_tensor * w, const ggml_tensor * lo, const ggml_tensor * xn, ggml_tensor * dst,
        const int hc, const float scale, const float bias) {
    const bool q8 = w->type == GGML_TYPE_Q8_0;
    if (!ggml_cuda_hc_gate_mix_ok(w, lo, xn, dst, hc, nullptr)) return false;
    const int K = (int) w->ne[0], M = (int) w->ne[1], E = (int) dst->ne[0]; const int T = (int) ggml_nrows(dst);
    // strixllama: the combine that wrote xn left only its BF16 copy, the F32 residual and the row scales (STRIX_HC_XRES)
    const mmb_xres_entry xres = g_mmb_xres;
    g_mmb_xres = { nullptr, nullptr, nullptr, nullptr };
    if (xres.xn_data && xres.xn_data == xn->data) {
        GGML_ASSERT(q8 && xn->type == GGML_TYPE_F32 && "formed streams stand in for the F32 ones only");
        cudaStream_t stream = ctx.stream();
        const uint16_t * lo16 = mmb_bf16_activation(ctx, lo, (size_t) T * K, stream);
        uint16_t * outh = ggml_cuda_mmb_slot_reserve(ctx, 3, dst, (size_t) T * E);
        const bool store_f32 = !(outh && ggml_cuda_mmb_is_bf16_only(dst));
        dim3 grid(E / 32, (T + 127) / 128);
        hc_gate_mix_kernel<4, 1, true, true><<<grid, MMB_NT, 0, stream>>>((const uint8_t *) w->data, lo16, nullptr, nullptr, (float *) dst->data,
            outh, store_f32, E, K, T, scale, bias, 0, xres.res, xres.rs, xres.gamma);
        CUDA_CHECK(cudaGetLastError());
        static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "HC_GATEMIX streams formed from the residual (XRES): E=%d K=%d T=%d\\n", E, K, T);
        return true;
    }
'''),
        ('''    const int nbig_max   = n_rows / BN + E + 1;
    const int nsmall_max = E * ((THRESH + BN_SMALL - 1) / BN_SMALL) + 1;
    ggml_cuda_pool_alloc<uint32_t> desc_big(ctx.pool(), nbig_max);
    ggml_cuda_pool_alloc<uint32_t> desc_small(ctx.pool(), nsmall_max);
    mmb_build_desc2<<<1, 1024, 0, stream>>>(bounds.get(), desc_big.get(), desc_small.get(), E, nbig_max, nsmall_max, BN, BN_SMALL, THRESH);

    const uint8_t * W = (const uint8_t *) src0->data; float * D = (float *) dst->data; const size_t eb = (size_t) src0->nb[2];
    uint16_t * Dh = (mmb_down16_flag() && ggml_cuda_mmb_is_bf16_only(dst)) ? (uint16_t *) dst->data : nullptr;
    const bool store_f32 = Dh == nullptr;
    if (Dh) { static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "MMB_DOWN16 routed down BF16 in place: M=%d K=%d rows=%d\\n", M, K, n_rows); }
''',
         '''    const uint8_t * W = (const uint8_t *) src0->data; float * D = (float *) dst->data; const size_t eb = (size_t) src0->nb[2];
    uint16_t * Dh = (mmb_down16_flag() && ggml_cuda_mmb_is_bf16_only(dst)) ? (uint16_t *) dst->data : nullptr;
    const bool store_f32 = Dh == nullptr;
    if (Dh) { static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "MMB_DOWN16 routed down BF16 in place: M=%d K=%d rows=%d\\n", M, K, n_rows); }
    if (mmb_down_tiles3() && E <= 1024) {
        constexpr int BN_MID = 64;
        const int nbig_max = n_rows / BN + E + 1, nmid_max = E + 1, nsmall_max = E + 1;
        ggml_cuda_pool_alloc<uint32_t> desc_big(ctx.pool(), nbig_max);
        ggml_cuda_pool_alloc<uint32_t> desc_mid(ctx.pool(), nmid_max);
        ggml_cuda_pool_alloc<uint32_t> desc_small(ctx.pool(), nsmall_max);
        mmb_build_desc3<<<1, 1024, 0, stream>>>(bounds.get(), desc_big.get(), desc_mid.get(), desc_small.get(), E, nbig_max, nmid_max, nsmall_max, BN, BN_MID, BN_SMALL);
        dim3 gbig((M + 127) / 128, nbig_max), gmid((M + 127) / 128, nmid_max), gsmall((M + 127) / 128, nsmall_max);
        if (src0->type == GGML_TYPE_Q5_1) {
            mmb_routed_kernel<128, BN, 32, 64, 4><<<gbig, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_big.get(), M, K);
            mmb_routed_kernel<128, BN_MID, 32, 32, 4><<<gmid, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_mid.get(), M, K);
            mmb_routed_kernel<128, BN_SMALL, 32, 16, 4><<<gsmall, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_small.get(), M, K);
        } else {
            mmb_routed_kernel<128, BN, 32, 64><<<gbig, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_big.get(), M, K);
            mmb_routed_kernel<128, BN_MID, 32, 32><<<gmid, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_mid.get(), M, K);
            mmb_routed_kernel<128, BN_SMALL, 32, 16><<<gsmall, MMB_NT, 0, stream>>>(W, eb, xhp, D, Dh, store_f32, ids_src1.get(), ids_dst.get(), bounds.get(), desc_small.get(), M, K);
        }
        CUDA_CHECK(cudaGetLastError());
        return;
    }
    const int nbig_max   = n_rows / BN + E + 1;
    const int nsmall_max = E * ((THRESH + BN_SMALL - 1) / BN_SMALL) + 1;
    ggml_cuda_pool_alloc<uint32_t> desc_big(ctx.pool(), nbig_max);
    ggml_cuda_pool_alloc<uint32_t> desc_small(ctx.pool(), nsmall_max);
    mmb_build_desc2<<<1, 1024, 0, stream>>>(bounds.get(), desc_big.get(), desc_small.get(), E, nbig_max, nsmall_max, BN, BN_SMALL, THRESH);
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmb.cuh"): [
        ('''bool ggml_cuda_hc_gate_mix(ggml_backend_cuda_context & ctx, const ggml_tensor * w, const ggml_tensor * lo, const ggml_tensor * xn, ggml_tensor * dst, int hc, float scale, float bias);
bool ggml_cuda_mmb_supported_glu(const ggml_tensor * gw, const ggml_tensor * uw, const ggml_tensor * src1, const ggml_tensor * ids, const ggml_tensor * glu);
''',
         '''bool ggml_cuda_hc_gate_mix(ggml_backend_cuda_context & ctx, const ggml_tensor * w, const ggml_tensor * lo, const ggml_tensor * xn, ggml_tensor * dst, int hc, float scale, float bias);
// strixllama: whether ggml_cuda_hc_gate_mix will run for these tensors (the streams' copies aside), and whether it reads
// the F32 streams (*f32) - which it can instead form from a combine's residual output (ggml_cuda_hc_xres_set)
bool ggml_cuda_hc_gate_mix_ok(const ggml_tensor * w, const ggml_tensor * lo, const ggml_tensor * xn, const ggml_tensor * dst, int hc, bool * f32);
void ggml_cuda_hc_xres_set(const void * xn_data, const float * res, const float * row_scale, const float * gamma);
bool ggml_cuda_mmb_supported_glu(const ggml_tensor * gw, const ggml_tensor * uw, const ggml_tensor * src1, const ggml_tensor * ids, const ggml_tensor * glu);
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmid.cu"): [
        ('''
bool ggml_cuda_launch_mm_ids_bounded(
''',
         '''
// strixllama: the sorted route from 64 tokens on (STRIX_IDS_ROUTE_MIN; it took over above 4096 only). Below that the
// helper runs a single wave per expert over every token's ids: at 1984 tokens 0.62 ms of each routed GEMM's 4.8 ms
// (down) and 0.68 of the gate/up's, the sorted route a few tens of microseconds. Rows keep their order within an expert.
static int mm_ids_route_min_tokens() {
    static const int v = getenv("STRIX_IDS_ROUTE_MIN") ? atoi(getenv("STRIX_IDS_ROUTE_MIN")) : 64;
    return v;
}

bool ggml_cuda_launch_mm_ids_bounded(
'''),
        ('''            tokens<=4096 || tokens>32768 || (channels!=1 && channels!=used) ||
''',
         '''            tokens<=mm_ids_route_min_tokens() || tokens>32768 || (channels!=1 && channels!=used) ||
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "moe-weighted-reduction.cu"): [
        ('''__device__ __forceinline__ float moe_bf2f(const uint16_t h) { return __uint_as_float(((uint32_t) h) << 16); }

''',
         '''__device__ __forceinline__ float moe_bf2f(const uint16_t h) { return __uint_as_float(((uint32_t) h) << 16); }

// strixllama: the shared expert's tail - ffn_out = sum + shexp * gate, as the graph's MUL and ADD would compute it (two
// separately rounded operations; written as instructions so the compiler cannot contract them into one FMA)
#if defined(__HIP_PLATFORM_AMD__)
__device__ __forceinline__ float moe_mul_rn(const float a, const float b) { float r; asm("v_mul_f32_e32 %0, %1, %2" : "=v"(r) : "v"(a), "v"(b)); return r; }
__device__ __forceinline__ float moe_add_rn(const float a, const float b) { float r; asm("v_add_f32_e32 %0, %1, %2" : "=v"(r) : "v"(a), "v"(b)); return r; }
#else
__device__ __forceinline__ float moe_mul_rn(const float a, const float b) { return __fmul_rn(a, b); }
__device__ __forceinline__ float moe_add_rn(const float a, const float b) { return __fadd_rn(a, b); }
#endif
__device__ __forceinline__ float4 moe_shexp_tail(const float4 sum, const float * __restrict__ shexp, const float * __restrict__ sgate,
                                                  const int64_t token, const int64_t n_embd, const int64_t col4) {
    const float  g = sgate[token];
    const float4 s = *(const float4 *)(shexp + token * n_embd + col4);
    float4 o;
    o.x = moe_add_rn(sum.x, moe_mul_rn(s.x, g)); o.y = moe_add_rn(sum.y, moe_mul_rn(s.y, g));
    o.z = moe_add_rn(sum.z, moe_mul_rn(s.z, g)); o.w = moe_add_rn(sum.w, moe_mul_rn(s.w, g));
    return o;
}

'''),
        ('''                                                     const int64_t n_embd,
                                                     const int     n_expert_used) {
    const int64_t token = blockIdx.x;
''',
         '''                                                     const int64_t n_embd,
                                                     const int     n_expert_used,
                                                     const float * __restrict__ shexp = nullptr,
                                                     const float * __restrict__ sgate = nullptr) {
    const int64_t token = blockIdx.x;
'''),
        ('''        sum.x += (e.x * scale) * w; sum.y += (e.y * scale) * w; sum.z += (e.z * scale) * w; sum.w += (e.w * scale) * w;
    }
    *(float4 *)(dst + token * n_embd + col4) = sum;
}
''',
         '''        sum.x += (e.x * scale) * w; sum.y += (e.y * scale) * w; sum.z += (e.z * scale) * w; sum.w += (e.w * scale) * w;
    }
    if (shexp) { sum = moe_shexp_tail(sum, shexp, sgate, token, n_embd, col4); }
    *(float4 *)(dst + token * n_embd + col4) = sum;
}
'''),
        ('''                                                      const int     n_expert_used) {
''',
         '''                                                      const int     n_expert_used,
                                                      const float * __restrict__ shexp = nullptr,
                                                      const float * __restrict__ sgate = nullptr) {
'''),
        ('''        sum.z += (moe_bf2f(h.z) * scale) * w; sum.w += (moe_bf2f(h.w) * scale) * w;
    }
    *(float4 *)(dst + token * n_embd + col4) = sum;
}
''',
         '''        sum.z += (moe_bf2f(h.z) * scale) * w; sum.w += (moe_bf2f(h.w) * scale) * w;
    }
    if (shexp) { sum = moe_shexp_tail(sum, shexp, sgate, token, n_embd, col4); }
    *(float4 *)(dst + token * n_embd + col4) = sum;
}
'''),
        ('''                                          cudaStream_t  stream) {
''',
         '''                                          cudaStream_t  stream,
                                          const float * shexp = nullptr,
                                          const float * sgate = nullptr) {
'''),
        ('''        moe_weighted_reduction_f32_v4<<<blocks, threads, 0, stream>>>(experts, expert_scale, weights, dst, n_embd, n_expert_used);
''',
         '''        moe_weighted_reduction_f32_v4<<<blocks, threads, 0, stream>>>(experts, expert_scale, weights, dst, n_embd, n_expert_used, shexp, sgate);
'''),
        ('''    }
    const dim3 blocks(n_tokens, (n_embd + threads - 1) / threads, 1);
''',
         '''    }
    GGML_ASSERT(shexp == nullptr && "the shared-expert tail needs the vectorized kernel");
    const dim3 blocks(n_tokens, (n_embd + threads - 1) / threads, 1);
'''),
        ('''                                         const ggml_tensor *         merge) {
''',
         '''                                         const ggml_tensor *         merge,
                                         const ggml_tensor *         shexp,
                                         const ggml_tensor *         sgate) {
'''),
        ('''    GGML_ASSERT(merge == nullptr && "shared-expert merge is only fused on the BF16 output path");
    if (ggml_cuda_mmb_down16() && ggml_cuda_mmb_is_bf16_only(experts)) {
''',
         '''    GGML_ASSERT(merge == nullptr && "shared-expert merge is only fused on the BF16 output path");
    const float * sx = shexp ? (const float *) shexp->data : nullptr;
    const float * sg = shexp ? (const float *) sgate->data : nullptr;
    if (shexp) { static unsigned h = 0; if (h++ < 2) fprintf(stderr, "MOE_RED + gated shared expert: n_embd=%lld tokens=%lld\\n", (long long) n_embd, (long long) n_tokens); }
    if (ggml_cuda_mmb_down16() && ggml_cuda_mmb_is_bf16_only(experts)) {
'''),
        ('''            (float *) dst->data, n_embd, (int) n_expert_used);
''',
         '''            (float *) dst->data, n_embd, (int) n_expert_used, sx, sg);
'''),
        ('''                                  (float *) dst->data, n_embd, n_tokens, (int) n_expert_used, stream);
''',
         '''                                  (float *) dst->data, n_embd, n_tokens, (int) n_expert_used, stream, sx, sg);
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "moe-weighted-reduction.cuh"): [
        ('''                                         const ggml_tensor *         merge = nullptr);
''',
         '''                                         const ggml_tensor *         merge = nullptr,
                                         const ggml_tensor *         shexp = nullptr,
                                         const ggml_tensor *         sgate = nullptr);
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "norm-gated.cu"): [
        ('''template <bool GATE, bool HAS_W = true>
''',
         '''// POST (strixllama): the SCALE after a plain norm - the gated delta net's L2 norm of q and k is rms_norm then scale by
// 1/sqrt(n) - applied as scale_f32 writes it (`scale * x + bias`), so the norm's output is not written and read back
template <bool GATE, bool HAS_W = true, bool POST = false>
'''),
        ('''        const int64_t stride_row, const int64_t stride_channel, const int64_t stride_sample, const float eps) {
''',
         '''        const int64_t stride_row, const int64_t stride_channel, const int64_t stride_sample, const float eps,
        const float post_scale = 1.0f, const float post_bias = 0.0f) {
'''),
        ('''            if constexpr (HAS_W) { t = scale * x[col] * w[col]; } else { t = scale * x[col]; }
            if (GATE) { const float s = 1.0f / (1.0f + expf(-z[col])); dst[col] = t * s; } else { dst[col] = t; }
''',
         '''            if constexpr (HAS_W) { t = scale * x[col] * w[col]; } else { t = scale * x[col]; }
            if constexpr (POST) { t = post_scale * t + post_bias; }
            if (GATE) { const float s = 1.0f / (1.0f + expf(-z[col])); dst[col] = t * s; } else { dst[col] = t; }
'''),
        ('''        ncols, nrows, nchannels, total, stride_row, stride_channel, stride_sample, eps);
''',
         '''        ncols, nrows, nchannels, total, stride_row, stride_channel, stride_sample, eps, 1.0f, 0.0f);
'''),
        ('''    return true;
}
''',
         '''    return true;
}

// strixllama: RMS_NORM of narrow rows followed by SCALE, its only reader (STRIX_NORM_SCALE=0: off)
int ggml_cuda_norm_scale_match_at(const ggml_cgraph * cgraph, int i, ggml_cuda_norm_scale_match & m) {
    static const bool on = !getenv("STRIX_NORM_SCALE") || atoi(getenv("STRIX_NORM_SCALE")) != 0;
    if (!on || !norm_rows_enabled() || i + 1 >= cgraph->n_nodes) return 0;
    const ggml_tensor * rms = cgraph->nodes[i]; ggml_tensor * sc = cgraph->nodes[i+1];
    if (rms->op != GGML_OP_RMS_NORM || sc->op != GGML_OP_SCALE || sc->src[0] != rms || !ggml_node_has_n_uses(cgraph, i, 1)) return 0;
    const ggml_tensor * x = rms->src[0];
    if (x->type != GGML_TYPE_F32 || rms->type != GGML_TYPE_F32 || sc->type != GGML_TYPE_F32 || x->nb[0] != 4) return 0;
    if (x->ne[0] > 256 || x->ne[0] % 32 != 0 || x->ne[1] * x->ne[2] * x->ne[3] < 4096) return 0;
    if (!ggml_is_contiguous(rms) || !ggml_is_contiguous(sc) || !ggml_are_same_shape(rms, sc)) return 0;
    float eps; memcpy(&eps, rms->op_params, sizeof(float)); if (eps < 0.0f) return 0;
    float s, b; memcpy(&s, (const float *) sc->op_params + 0, sizeof(float)); memcpy(&b, (const float *) sc->op_params + 1, sizeof(float));
    m.x = x; m.dst = sc; m.eps = eps; m.scale = s; m.bias = b;
    return 1;
}

void ggml_cuda_op_norm_scale(ggml_backend_cuda_context & ctx, const ggml_cuda_norm_scale_match & m) {
    const ggml_tensor * x = m.x;
    static unsigned hits = 0; if (hits++ < 2) fprintf(stderr, "NORM_ROWS+SCALE fused: ncols=%d rows=%lld\\n", (int) x->ne[0], (long long) (x->ne[1]*x->ne[2]*x->ne[3]));
    const int64_t total = x->ne[1] * x->ne[2] * x->ne[3];
    const dim3 grid((unsigned) ((total + 7) / 8)), block(256);
    const ggml_cuda_kernel_launch_params lp(grid, block, 0, ctx.stream());
    ggml_cuda_kernel_launch(rms_rows_f32<false, false, true>, lp, (const float *) x->data, (const float *) nullptr, (const float *) nullptr,
        (float *) m.dst->data, (int) x->ne[0], x->ne[1], x->ne[2], total, (int64_t) (x->nb[1] / 4), (int64_t) (x->nb[2] / 4),
        (int64_t) (x->nb[3] / 4), m.eps, m.scale, m.bias);
}
'''),
        ('''        (int) x->ne[0], x->ne[1], x->ne[2], total, (int64_t) (x->nb[1] / 4), (int64_t) (x->nb[2] / 4), (int64_t) (x->nb[3] / 4), m.eps);
    else     ggml_cuda_kernel_launch(rms_rows_f32<false>, lp, (const float *) x->data, (const float *) m.w->data, (const float *) nullptr, (float *) m.dst->data,
        (int) x->ne[0], x->ne[1], x->ne[2], total, (int64_t) (x->nb[1] / 4), (int64_t) (x->nb[2] / 4), (int64_t) (x->nb[3] / 4), m.eps);
''',
         '''        (int) x->ne[0], x->ne[1], x->ne[2], total, (int64_t) (x->nb[1] / 4), (int64_t) (x->nb[2] / 4), (int64_t) (x->nb[3] / 4), m.eps, 1.0f, 0.0f);
    else     ggml_cuda_kernel_launch(rms_rows_f32<false>, lp, (const float *) x->data, (const float *) m.w->data, (const float *) nullptr, (float *) m.dst->data,
        (int) x->ne[0], x->ne[1], x->ne[2], total, (int64_t) (x->nb[1] / 4), (int64_t) (x->nb[2] / 4), (int64_t) (x->nb[3] / 4), m.eps, 1.0f, 0.0f);
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "norm-gated.cuh"): [
        ('''int  ggml_cuda_norm_rows_match_at(const ggml_cgraph * cgraph, int i, ggml_cuda_norm_gated_match & m);
bool ggml_cuda_rms_rows_plain(const float * x, float * dst, int ncols, int64_t nrows, int64_t nchannels, int64_t nsamples,
''',
         '''int  ggml_cuda_norm_rows_match_at(const ggml_cgraph * cgraph, int i, ggml_cuda_norm_gated_match & m);
struct ggml_cuda_norm_scale_match { const ggml_tensor * x; ggml_tensor * dst; float eps, scale, bias; };
int  ggml_cuda_norm_scale_match_at(const ggml_cgraph * cgraph, int i, ggml_cuda_norm_scale_match & m);
void ggml_cuda_op_norm_scale(ggml_backend_cuda_context & ctx, const ggml_cuda_norm_scale_match & m);
bool ggml_cuda_rms_rows_plain(const float * x, float * dst, int ncols, int64_t nrows, int64_t nchannels, int64_t nsamples,
'''),
    ],
    os.path.join(tree, "include", "llama.h"): [
        ('''    LLAMA_API void llama_strix_prefetch(struct llama_context * ctx, const llama_token * tokens, int32_t n_tokens, int32_t n_context);

''',
         '''    LLAMA_API void llama_strix_prefetch(struct llama_context * ctx, const llama_token * tokens, int32_t n_tokens, int32_t n_context);
    // strixllama: the same rows for the batch about to run, read now on a thread of their own (a prompt's first batch)
    LLAMA_API void llama_strix_pregather_now(struct llama_context * ctx, const llama_token * tokens, int32_t n_tokens, int32_t n_context);

'''),
    ],
    os.path.join(tree, "src", "llama-context.cpp"): [
        ('''
void llama_strix_prefetch(llama_context * ctx, const llama_token * tokens, int32_t n_tokens, int32_t n_context) {
''',
         '''
void llama_strix_pregather_now(llama_context * ctx, const llama_token * tokens, int32_t n_tokens, int32_t n_context) {
    extern void qwen4exp_ple_pregather_now(const llama_model & model, const llama_token * tokens, int32_t n_tokens, int32_t n_skip);
    if (ctx && tokens && n_tokens > n_context && n_context >= 0) {
        qwen4exp_ple_pregather_now(ctx->get_model(), tokens, n_tokens, n_context);
    }
}

void llama_strix_prefetch(llama_context * ctx, const llama_token * tokens, int32_t n_tokens, int32_t n_context) {
'''),
    ],
    os.path.join(tree, "src", "llama-graph.cpp"): [
        ('''    if (!weight_before_ffn) {
        experts = ggml_mul(ctx0, experts, weights);
''',
         '''    if (!weight_before_ffn) {
        if (moe_before_weighting) {
            ggml_build_forward_expand(gf, experts);
            std::function<void()> hook;
            hook.swap(moe_before_weighting);
            hook();
        }
        experts = ggml_mul(ctx0, experts, weights);
'''),
    ],
    os.path.join(tree, "src", "llama-graph.h"): [
        ('''
    llm_graph_context(const llm_graph_params & params);
''',
         '''
    // strixllama: run once by the next build_moe_ffn between the experts' down projection and their weighting (graph
    // order only: what a model puts into the graph there comes before the weighted sum)
    mutable std::function<void()> moe_before_weighting;

    llm_graph_context(const llm_graph_params & params);
'''),
    ],
    os.path.join(tree, "src", "llama-lazy-reader.h"): [
        ('''#include <cstring>
#include <mutex>
''',
         '''#include <cstring>
#include <condition_variable>
#include <functional>
#include <mutex>
'''),
        ('''
    template <typename F>
''',
         '''
    // strixllama: runs after the prefetch before it, on its own thread, and never makes the caller wait for that one
    template <typename F>
'''),
        ('''        if (prefetch_thread.joinable()) {
            prefetch_thread.join();
        }
        prefetch_thread = std::thread([fn = std::forward<F>(work)]() {
''',
         '''        std::thread prev = std::move(prefetch_thread);
        prefetch_thread = std::thread([prev = std::move(prev), fn = std::forward<F>(work)]() mutable {
            if (prev.joinable()) {
                prev.join();
            }
'''),
        ('''
    mutable std::mutex prefetch_mutex;
''',
         '''
    // strixllama: a pregather announced for the next batch waits until the batch about to run has its own rows
    // (launch_deferred, from the gather's input): started at once it shared the drive with that batch's gather, which
    // the GPU waits for. A newer announcement replaces one still waiting.
    void defer_prefetch(std::function<void()> work) const {
        std::lock_guard<std::mutex> lock(prefetch_mutex);
        deferred = std::move(work);
    }

    void launch_deferred() const {
        std::function<void()> work;
        {
            std::lock_guard<std::mutex> lock(prefetch_mutex);
            work.swap(deferred);
        }
        if (work) {
            launch_prefetch(std::move(work));
        }
    }

    mutable std::mutex prefetch_mutex;
'''),
        ('''    mutable std::thread prefetch_thread;

''',
         '''    mutable std::thread prefetch_thread;
    mutable std::function<void()> deferred;

'''),
        ('''    ~llama_lazy_reader() {
#ifdef _WIN32
''',
         '''    ~llama_lazy_reader() {
        if (now_thread.joinable()) {
            now_thread.join();
        }
#ifdef _WIN32
'''),
        ('''        std::sort(pairs.begin(), pairs.end()); // equal rows adjacent, file order

''',
         '''        std::sort(pairs.begin(), pairs.end()); // equal rows adjacent, file order
        const auto strixllama_t1 = std::chrono::steady_clock::now();
        auto strixllama_t2 = strixllama_t1, strixllama_t3 = strixllama_t1;

'''),
        ('''            }
            if (!miss.empty()) {
''',
         '''            }
            strixllama_t2 = std::chrono::steady_clock::now();
            if (!miss.empty()) {
'''),
        ('''                read_pairs(miss, dst, raw.data());
                std::lock_guard<std::mutex> lock(cache_mutex);
''',
         '''                read_pairs(miss, dst, raw.data());
                strixllama_t3 = std::chrono::steady_clock::now();
                std::lock_guard<std::mutex> lock(cache_mutex);
'''),
        ('''            fprintf(stderr, "PLE_GATHER rows=%lld uniq=%lld cached=%lld row_bytes=%zu ms=%.1f\\n",
                    (long long) n, (long long) uniq, (long long) n_hit, row_size, ms);
''',
         '''            auto ms_of = [](std::chrono::steady_clock::time_point a, std::chrono::steady_clock::time_point b) {
                return std::chrono::duration<double, std::milli>(b - a).count(); };
            fprintf(stderr, "PLE_GATHER rows=%lld uniq=%lld cached=%lld row_bytes=%zu ms=%.1f (sort %.1f hits %.1f read %.1f)\\n",
                    (long long) n, (long long) uniq, (long long) n_hit, row_size, ms, ms_of(strixllama_t0, strixllama_t1),
                    ms_of(strixllama_t1, strixllama_t2), ms_of(strixllama_t2, strixllama_t3));
'''),
        ('''        std::vector<uint8_t> data;      // rows.size() * head_dim floats
    };
''',
         '''        std::vector<uint8_t> data;      // rows.size() * head_dim floats
        uint64_t id    = 0;             // strixllama: a pregather announced before it ran (pregather_now) has one ...
        bool     ready = true;          // ... and is not ready while it runs: a take of its rows waits for it
    };
'''),
        ('''    mutable std::mutex pre_mutex;
    mutable std::vector<pregathered> pre;
''',
         '''    mutable std::mutex pre_mutex;
    mutable std::condition_variable pre_cv;
    mutable uint64_t pre_next_id = 1;
    mutable std::vector<pregathered> pre;
'''),
        ('''    void pregather(const int32_t * rows, int64_t n) const {
        pregathered p;
        p.rows.assign(rows, rows + n);
        p.data.resize((size_t) n * head_dim * sizeof(float));
        gather(rows, n, (float *) p.data.data());
        std::lock_guard<std::mutex> lock(pre_mutex);
        pre.push_back(std::move(p));
        if (pre.size() > 2) {
            pre.erase(pre.begin());
''',
         '''    // keep the newest few: a running pregather is never dropped, its taker waits for it
    void pre_trim() const {
        while (pre.size() > 3) {
            auto it = std::find_if(pre.begin(), pre.end(), [](const pregathered & p) { return p.ready; });
            if (it == pre.end()) {
                break;
            }
            pre.erase(it);
'''),
        ('''        }
    }

    // the gathered rows for `rows`, when a pregather covered them: the batch a caller announced can come out shorter
''',
         '''        }
    }

    void pregather(const int32_t * rows, int64_t n, uint64_t id = 0) const {
        std::vector<uint8_t> data((size_t) n * head_dim * sizeof(float));
        bool ok = true;
        try {
            gather(rows, n, (float *) data.data());
        } catch (...) {
            ok = false;   // an announced entry is still released below: its taker reads the rows itself
            if (!id) {
                throw;
            }
        }
        {
            std::lock_guard<std::mutex> lock(pre_mutex);
            auto it = id ? std::find_if(pre.begin(), pre.end(), [id](const pregathered & p) { return p.id == id; }) : pre.end();
            if (it != pre.end()) {
                if (ok) {
                    it->data.swap(data);
                } else {
                    pre.erase(it);
                }
            } else if (!id) {
                pregathered p;
                p.rows.assign(rows, rows + n);
                p.data.swap(data);
                pre.push_back(std::move(p));
            }
            for (auto & p : pre) {
                if (p.id == id) {
                    p.ready = true;
                }
            }
            pre_trim();
        }
        pre_cv.notify_all();
    }

    // strixllama: a pregather of the batch about to run - its first chunk, which no earlier batch announced - started at
    // once on a thread of its own, so its reads overlap the batch's preparation and graph build; announced first, so the
    // batch's gather waits for it rather than reading the rows again
    void pregather_now(std::vector<int32_t> rows) const {
        uint64_t id;
        {
            std::lock_guard<std::mutex> lock(pre_mutex);
            for (const auto & p : pre) {     // already announced or gathered
                if (p.rows.size() >= rows.size() && std::equal(rows.begin(), rows.end(), p.rows.begin())) {
                    return;
                }
            }
            id = pre_next_id++;
            pregathered p;
            p.rows  = rows;
            p.id    = id;
            p.ready = false;
            pre.push_back(std::move(p));
        }
        std::lock_guard<std::mutex> lock(now_mutex);
        std::thread prev = std::move(now_thread);
        now_thread = std::thread([this, prev = std::move(prev), rows = std::move(rows), id]() mutable {
            if (prev.joinable()) {
                prev.join();
            }
            try {
                pregather(rows.data(), (int64_t) rows.size(), id);
            } catch (...) {
                LLAMA_LOG_WARN("lazy pregather skipped after an exception\\n");
            }
        });
    }
    mutable std::mutex  now_mutex;
    mutable std::thread now_thread;

    // the gathered rows for `rows`, when a pregather covered them: the batch a caller announced can come out shorter
'''),
        ('''    bool take_pregathered(const int32_t * rows, int64_t n, std::vector<uint8_t> & out) const {
        std::lock_guard<std::mutex> lock(pre_mutex);
        for (auto it = pre.begin(); it != pre.end(); ++it) {
''',
         '''    bool take_pregathered(const int32_t * rows, int64_t n, std::vector<uint8_t> & out) const {
        std::unique_lock<std::mutex> lock(pre_mutex);
        // a match still being gathered: wait for it (it is released whether or not its reads succeed)
        auto wait_ready = [&](uint64_t id) {
            pre_cv.wait(lock, [&]() {
                auto it = std::find_if(pre.begin(), pre.end(), [id](const pregathered & p) { return p.id == id; });
                return it == pre.end() || it->ready;
            });
            return std::find_if(pre.begin(), pre.end(), [id](const pregathered & p) { return p.id == id; });
        };
        for (auto it = pre.begin(); it != pre.end(); ++it) {
'''),
        ('''            if ((int64_t) it->rows.size() < n || memcmp(it->rows.data(), rows, (size_t) n * sizeof(int32_t)) != 0) {
                continue;
            }
            const size_t bytes = (size_t) n * head_dim * sizeof(float);
''',
         '''            if ((int64_t) it->rows.size() < n || memcmp(it->rows.data(), rows, (size_t) n * sizeof(int32_t)) != 0) {
                continue;
            }
            if (!it->ready) {
                it = wait_ready(it->id);
                if (it == pre.end()) {
                    return false;
                }
            }
            const size_t bytes = (size_t) n * head_dim * sizeof(float);
'''),
        ('''        }
        return false;
    }
''',
         '''        }
        // strixllama: a prompt chunk that shares its pass with other conversations sits inside the batch, after their
        // tokens (or its pregather ran short of it): take the longest run of pregathered rows found in the batch and
        // read the rows around it. A row's data does not depend on where it sits, so any match is exact.
        int64_t best = -1, best_o = 0, best_len = 0;
        for (size_t k = 0; k < pre.size(); ++k) {
            const auto & e = pre[k];
            if (e.rows.empty()) { continue; }
            for (int64_t o = 0; o < n && best_len < n - o; ++o) {
                if (rows[o] != e.rows[0]) { continue; }
                const int64_t lim = std::min<int64_t>((int64_t) e.rows.size(), n - o);
                int64_t len = 1;
                while (len < lim && rows[o + len] == e.rows[len]) { ++len; }
                if (len > best_len) { best = (int64_t) k; best_o = o; best_len = len; }
            }
        }
        // a short coincidental match must not use up the pregather of a later batch
        if (best < 0 || (best_len < 1024 && best_len < (int64_t) pre[best].rows.size())) {
            return false;
        }
        if (!pre[best].ready) {
            const auto it = wait_ready(pre[best].id);
            if (it == pre.end()) {
                return false;
            }
            best = it - pre.begin();
        }
        const size_t rb = head_dim * sizeof(float);
        out.resize((size_t) n * rb);
        memcpy(out.data() + (size_t) best_o * rb, pre[best].data.data(), (size_t) best_len * rb);
        pre.erase(pre.begin() + best);
        lock.unlock();
        if (best_o > 0) {
            gather(rows, best_o, (float *) out.data());
        }
        if (best_o + best_len < n) {
            gather(rows + best_o + best_len, n - best_o - best_len, (float *) (out.data() + (size_t) (best_o + best_len) * rb));
        }
        return true;
    }
'''),
    ],
    os.path.join(tree, "src", "models", "qwen4exp.cpp"): [
        ('''
    ggml_tensor * moe_out =
''',
         '''
    const bool has_shexp = model.layers[il].ffn_up_shexp != nullptr;
    ggml_tensor * ffn_shexp   = nullptr;
    ggml_tensor * shared_gate = nullptr;
    auto build_shexp = [&]() {
        ffn_shexp =
            build_ffn(cur,
                model.layers[il].ffn_up_shexp, NULL, model.layers[il].ffn_up_shexp_s,
                model.layers[il].ffn_gate_shexp, NULL, model.layers[il].ffn_gate_shexp_s,
                model.layers[il].ffn_down_shexp, NULL, model.layers[il].ffn_down_shexp_s,
                NULL,
                LLM_FFN_SILU, LLM_FFN_PAR, il);
        cb(ffn_shexp, "ffn_shexp", il);

        // shared expert has its own sigmoided gate (ffn_gate_inp_shexp, one value per token)
        shared_gate = build_lora_mm(model.layers[il].ffn_gate_inp_shexp, cur);
        cb(shared_gate, "shared_expert_gate", il);

        shared_gate = ggml_sigmoid(ctx0, shared_gate);
        cb(shared_gate, "shared_expert_gate_sigmoid", il);

        ggml_build_forward_expand(gf, ffn_shexp);
        ggml_build_forward_expand(gf, shared_gate);
    };
    // strixllama: for a prompt-sized batch the shared expert enters the graph between the routed experts' down projection
    // and their weighted sum, so that its gating and the final add come right after the sum, which then runs them in
    // the same kernel (ggml-cuda, STRIX_SHEXP_TAIL). Graph order only: every value is the same. Before the routed
    // experts it would end the routed input's life early and let their fused gate/up kernel's output take its buffer,
    // which that kernel cannot share. STRIX_SHEXP_MOVE=0: the old order
    static const bool shexp_move = !getenv("STRIX_SHEXP_MOVE") || atoi(getenv("STRIX_SHEXP_MOVE")) != 0;
    if (has_shexp && shexp_move && n_tokens >= 512) {
        moe_before_weighting = build_shexp;
    }

    ggml_tensor * moe_out =
'''),
        ('''    // shared experts, as in the Qwen3Next reference
    if (model.layers[il].ffn_up_shexp != nullptr) {
        ggml_tensor * ffn_shexp =
            build_ffn(cur,
                model.layers[il].ffn_up_shexp, NULL, model.layers[il].ffn_up_shexp_s,
                model.layers[il].ffn_gate_shexp, NULL, model.layers[il].ffn_gate_shexp_s,
                model.layers[il].ffn_down_shexp, NULL, model.layers[il].ffn_down_shexp_s,
                NULL,
                LLM_FFN_SILU, LLM_FFN_PAR, il);
        cb(ffn_shexp, "ffn_shexp", il);

        // shared expert has its own sigmoided gate (ffn_gate_inp_shexp, one value per token)
        ggml_tensor * shared_gate = build_lora_mm(model.layers[il].ffn_gate_inp_shexp, cur);
        cb(shared_gate, "shared_expert_gate", il);

        shared_gate = ggml_sigmoid(ctx0, shared_gate);
        cb(shared_gate, "shared_expert_gate_sigmoid", il);
''',
         '''    moe_before_weighting = nullptr;   // a path of build_moe_ffn without the hook point

    // shared experts, as in the Qwen3Next reference
    if (has_shexp) {
        if (!ffn_shexp) {
            build_shexp();
        }
'''),
        ('''// than only warmed in the file cache
void qwen4exp_ple_prefetch(const llama_model & model_base, const llama_token * tokens, int32_t n_tokens,
''',
         '''// than only warmed in the file cache
// the table rows the gather of these tokens reads, for the tokens after the first n_skip (context only)
static std::vector<int32_t> qwen4exp_ple_rows(const llama_hparams & hp, const std::vector<llama_token> & toks, int64_t n_skip) {
    const int64_t n_gram = hp.ple_ngram_size, n_heads = hp.ple_n_heads, per_gram = hp.ple_heads_per_ngram;
    const int64_t eos = hp.ple_eos_token_id;
    const int64_t n = (int64_t) toks.size();
    std::vector<int32_t> idx((size_t) n_heads * (n - n_skip));
    std::vector<int64_t> ctx(n_gram);
    for (int64_t i = n_skip; i < n; ++i) {
        ctx[0] = toks[i];
        bool cut = false;
        for (int64_t sft = 1; sft < n_gram; ++sft) {
            const int64_t j = i - sft;                       // contiguous single-sequence prefill
            const llama_token t = (cut || j < 0) ? LLAMA_TOKEN_NULL : toks[j];
            cut = cut || t < 0 || t == eos;
            ctx[sft] = cut ? eos : t;
        }
        for (int64_t g = 2; g <= n_gram; ++g) {
            uint64_t mixed = (uint64_t) ctx[0] * hp.ple_layer_multipliers[0];
            for (int64_t j = 1; j < g; ++j) { mixed ^= (uint64_t) ctx[j] * hp.ple_layer_multipliers[j]; }
            const int64_t base = (g - 2) * per_gram;
            for (int64_t q = 0; q < per_gram; ++q) {
                const int64_t h_i = base + q;
                idx[(size_t) (i - n_skip) * n_heads + h_i] = (int32_t) (mixed % hp.ple_head_vocab_sizes[h_i] + hp.ple_head_offsets[h_i]);
            }
        }
    }
    return idx;
}

// strixllama: the rows of the batch about to run, read at once on a thread of their own (llama_strix_pregather_now):
// a prompt's first batch, which no earlier batch announced, otherwise reads them only after its graph is built
void qwen4exp_ple_pregather_now(const llama_model & model_base, const llama_token * tokens, int32_t n_tokens, int32_t n_skip) {
    if (!tokens || n_tokens - n_skip < 64 || n_skip < 0 || model_base.arch != LLM_ARCH_QWEN4EXP) { return; }
    const auto & pmodel = static_cast<const llama_model_qwen4exp &>(model_base);
    static const bool off = (getenv("LLAMA_PLE_PREFETCH") && atoi(getenv("LLAMA_PLE_PREFETCH")) == 0) ||
                            (getenv("STRIX_PLE_NOW") && atoi(getenv("STRIX_PLE_NOW")) == 0);
    if (!pmodel.ple_reader || off || pmodel.hparams.ple_n_heads <= 0 || pmodel.hparams.ple_ngram_size < 2) { return; }
    pmodel.ple_reader->pregather_now(qwen4exp_ple_rows(pmodel.hparams, std::vector<llama_token>(tokens, tokens + n_tokens), n_skip));
}

void qwen4exp_ple_prefetch(const llama_model & model_base, const llama_token * tokens, int32_t n_tokens,
'''),
        ('''    if (!tokens || n_tokens - n_skip < 4096 || model_base.arch != LLM_ARCH_QWEN4EXP) { return; }
''',
         '''    // strixllama: a pregather serves chunks of any length (the server announces only real ones); a page-cache prefetch
    // pays off only for big batches
    if (!tokens || n_tokens - n_skip < (pregather ? 64 : 4096) || model_base.arch != LLM_ARCH_QWEN4EXP) { return; }
'''),
        ('''    const int64_t n_gram = hp.ple_ngram_size, n_heads = hp.ple_n_heads, per_gram = hp.ple_heads_per_ngram;
    const int64_t eos = hp.ple_eos_token_id, n_prev = n_gram - 1;
    if (n_heads <= 0 || n_gram < 2) { return; }
''',
         '''    if (hp.ple_n_heads <= 0 || hp.ple_ngram_size < 2) { return; }
'''),
        ('''    auto prefetch = [reader = pmodel.ple_reader, toks = std::move(toks), n_gram, n_heads, per_gram, eos, n_prev, hp, n_skip, pregather]() {
        const int64_t n = (int64_t) toks.size();
        std::vector<int32_t> idx((size_t) n_heads * n);
        std::vector<int64_t> ctx(n_gram);
        for (int64_t i = 0; i < n; ++i) {
            ctx[0] = toks[i];
            bool cut = false;
            for (int64_t sft = 1; sft < n_gram; ++sft) {
                const int64_t j = i - sft;                       // contiguous single-sequence prefill
                const llama_token t = (cut || j < 0) ? LLAMA_TOKEN_NULL : toks[j];
                cut = cut || t < 0 || t == eos;
                ctx[sft] = cut ? eos : t;
            }
            for (int64_t g = 2; g <= n_gram; ++g) {
                uint64_t mixed = (uint64_t) ctx[0] * hp.ple_layer_multipliers[0];
                for (int64_t j = 1; j < g; ++j) { mixed ^= (uint64_t) ctx[j] * hp.ple_layer_multipliers[j]; }
                const int64_t base = (g - 2) * per_gram;
                for (int64_t q = 0; q < per_gram; ++q) {
                    const int64_t h_i = base + q;
                    idx[(size_t) i * n_heads + h_i] = (int32_t) (mixed % hp.ple_head_vocab_sizes[h_i] + hp.ple_head_offsets[h_i]);
                }
            }
        }
        const int32_t * first = idx.data() + (size_t) n_skip * n_heads;
        const int64_t   count = (int64_t) idx.size() - (int64_t) n_skip * n_heads;
''',
         '''    auto prefetch = [reader = pmodel.ple_reader, toks = std::move(toks), hp, n_skip, pregather]() {
        const std::vector<int32_t> idx = qwen4exp_ple_rows(hp, toks, n_skip);
'''),
        ('''            reader->pregather(first, count);
''',
         '''            reader->pregather(idx.data(), (int64_t) idx.size());
'''),
        ('''            reader->prefetch(first, count);
''',
         '''            reader->prefetch(idx.data(), (int64_t) idx.size());
'''),
        ('''    pmodel.ple_reader->launch_prefetch(std::move(prefetch));
''',
         '''    if (pregather) {
        pmodel.ple_reader->defer_prefetch(std::move(prefetch));
    } else {
        pmodel.ple_reader->launch_prefetch(std::move(prefetch));
    }
'''),
        ('''        }
        ggml_backend_tensor_set(data, staging.data(), 0, staging.size());
''',
         '''        }
#ifdef _WIN32
        pmodel.ple_reader->launch_deferred();   // the next batch's pregather, now that the drive is free
#endif
        ggml_backend_tensor_set(data, staging.data(), 0, staging.size());
'''),
    ],
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''    std::mt19937 spec_verify_rng;

''',
         '''    std::mt19937 spec_verify_rng;

    // strixllama: where the prompt chunk starts whose per-layer-embedding rows the last step announced (-1: none)
    int64_t ple_announced = -1;

'''),
        ('''        spec_is_replay = false;

''',
         '''        spec_is_replay = false;
        ple_announced  = -1;

'''),
        ('''            }
        }

        auto & alora_scale       = batch.alora_scale;
''',
         '''            }
        }
        // strixllama: the prompt tokens a step takes, which the next step's per-layer-embedding pregather expects
        const int32_t n_prompt_step = std::max<int32_t>(1, n_batch_prompt - batch.size());

        auto & alora_scale       = batch.alora_scale;
'''),
        ('''                    // n-gram lookups reach back two tokens, so those come along as context.
''',
         '''                    // n-gram lookups reach back two tokens, so those come along as context. The next chunk is as long
                    // as this step's: n_batch alone, the prefill budget while others generate (it then follows their
                    // tokens in the batch, which the reader allows for). Chunks under 4096 tokens used to gather for
                    // themselves - every 2048-token chunk beside generating conversations, the last chunk of a prompt.
                    // This chunk's own rows, when the step before did not announce them (a prompt's first chunk): read
                    // now, on a thread of their own, so the reads overlap the rest of the step's preparation and the
                    // graph build; the batch's gather waits for them
                    {
                        const int64_t cur_end = slot.prompt.n_tokens();
                        const int64_t cur_beg = cur_end - (int64_t) (batch.size() - n_tokens_prev);
                        if (cur_end - cur_beg >= 64 && cur_beg != slot.ple_announced) {
                            const int64_t beg = std::max<int64_t>(0, cur_beg - 2);
                            std::vector<llama_token> toks;
                            toks.reserve(cur_end - beg);
                            bool media = false;
                            for (int64_t i = beg; i < cur_end && !media; ++i) {
                                const llama_token t = input_tokens[i];
                                media = t == LLAMA_TOKEN_NULL;
                                toks.push_back(t);
                            }
                            if (!media) {
                                llama_strix_pregather_now(ctx_tgt, toks.data(), (int32_t) toks.size(), (int32_t) (cur_beg - beg));
                            }
                        }
                        slot.ple_announced = -1;
                    }
'''),
        ('''                        const int64_t end = std::min<int64_t>(slot.task->n_tokens(), nxt + n_batch);
''',
         '''                        const int64_t end = std::min<int64_t>(slot.task->n_tokens(), nxt + n_prompt_step);
'''),
        ('''                        if (end - nxt >= 4096) {
''',
         '''                        if (end - nxt >= 64) {
'''),
        ('''                                llama_strix_prefetch(ctx_tgt, toks.data(), (int32_t) toks.size(), (int32_t) (nxt - beg));
                            }
''',
         '''                                llama_strix_prefetch(ctx_tgt, toks.data(), (int32_t) toks.size(), (int32_t) (nxt - beg));
                                slot.ple_announced = nxt;
                            }
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
