#!/usr/bin/env python3
"""The 5-8 column q8_0 GEMV keeps two iterations' loads in flight.

mul_mat_vec_q8_0_i8's K loop waited for each iteration's loads before issuing the next; unrolled by two the latency-bound products speed up - eight columns of [10240 -> 320] 26.3 -> 22.1 us, 97 of them a step - with each lane's operations in the same order, so the output bits do not change (gemv_bench hashes equal at 5-8 columns).

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 1 hunks across 1 file(s).

Usage: python patches/apply_mmvq_i8_unroll_037.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = "two iterations' loads in flight"

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "mmvq.cu"): [
        ('''
    for (int kbx = k0; kbx < blocks_per_row_x; kbx += blocks_per_iter) {
''',
         '''
    // two iterations' loads in flight: eight columns of [10240 -> 320] 26.3 -> 22.6 us (4: 24.9), the same bits
#pragma unroll 2
    for (int kbx = k0; kbx < blocks_per_row_x; kbx += blocks_per_iter) {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
