#!/usr/bin/env python3
"""BF16 twins of the bfloat16-valued F32 weights, read by decode batches through the vector kernel.

The MoE routers, the shared experts' gates, the delta-net alpha/beta and the hyper-connection injects are stored F32 but every value is a bfloat16 (0.31 GB read a token). build_bf16_twins checks each such weight and keeps a BF16 copy; build_lora_mm uses it for batches of at most 8 tokens, where the F32 original takes mul_mat_vec_f, whose bf16 loop is its f32 loop - bf16 widens to f32 exactly - so the products are the same bits (gemv_bench hashes at 1-8 columns). GGML_BF16_TWIN_MAGIC keeps a twin on the vector kernel from 4 columns, where bf16 would take the WMMA kernel. Router [2560 -> 512] 28 -> 17 us at one column; one conversation ~0.7 ms a token. STRIX_BF16_TWINS=0: none.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 9 hunks across 5 file(s).

Usage: python patches/apply_bf16_twins_040.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'GGML_BF16_TWIN_MAGIC'

EDITS = {
    os.path.join(tree, "ggml", "include", "ggml.h"): [
        ('''    #define GGML_FLASH_ATTN_EXT_GATHER 0x47415448
    GGML_API struct ggml_tensor * ggml_flash_attn_ext_gather(
''',
         '''    #define GGML_FLASH_ATTN_EXT_GATHER 0x47415448

    // strixllama: op_params[0] of a weight that is the BF16 twin of an F32 weight (llama_model::build_bf16_twins): the
    // CUDA backend multiplies it with mul_mat_vec_f up to 8 columns, as it does the F32 original
    #define GGML_BF16_TWIN_MAGIC 0x54324642
    GGML_API struct ggml_tensor * ggml_flash_attn_ext_gather(
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ggml-cuda.cu"): [
        ('''    if (hint != GGML_HINT_SRC0_IS_HADAMARD && ggml_cuda_skinny_f32(ctx, src0, src1, dst)) {
        return;
''',
         '''    if (hint != GGML_HINT_SRC0_IS_HADAMARD && ggml_cuda_skinny_f32(ctx, src0, src1, dst)) {
        return;
    }

    // strixllama: the BF16 twin of an F32 weight takes the vector kernel up to 8 columns, as its original does - bf16
    // widens to f32 exactly and mul_mat_vec_f's bf16 loop is its f32 loop, so the products are the same bits (bf16
    // alone would take the WMMA kernel from 4 columns on RDNA, with other sums)
    if (src0->type == GGML_TYPE_BF16 && src0->op == GGML_OP_NONE && ggml_get_op_params_i32(src0, 0) == GGML_BF16_TWIN_MAGIC &&
            ne11 <= MMVF_MAX_BATCH_SIZE && src1->type == GGML_TYPE_F32 && dst->type == GGML_TYPE_F32 &&
            ggml_cuda_should_use_mmvf(src0->type, ggml_cuda_info().devices[ctx.device].cc, src0->ne, src0->nb, 1)) {
        ggml_cuda_mul_mat_vec_f(ctx, src0, src1, nullptr, dst);
        return;
'''),
    ],
    os.path.join(tree, "src", "llama-graph.cpp"): [
        ('''        if (ggml_tensor * twin = llama_decode_twin(w)) {
            w_mm = twin;
''',
         '''        if (ggml_tensor * twin = llama_decode_twin(w)) {
            w_mm = twin;
        }
    }
    // strixllama: the BF16 twin of a bfloat16-valued F32 weight, for batches the vector kernel takes (build_bf16_twins)
    if (n_tokens <= 8) {
        if (ggml_tensor * twin = llama_bf16_twin(w)) {
            w_mm = twin;
'''),
    ],
    os.path.join(tree, "src", "llama-model.cpp"): [
        ('''
int64_t llama_decode_twin_max_tokens() {
''',
         '''
static std::unordered_map<const ggml_tensor *, ggml_tensor *> g_bf16_twins;

ggml_tensor * llama_bf16_twin(const ggml_tensor * w) {
    std::lock_guard<std::mutex> lock(g_decode_twin_mutex);
    const auto it = g_bf16_twins.find(w);
    return it == g_bf16_twins.end() ? nullptr : it->second;
}

int64_t llama_decode_twin_max_tokens() {
'''),
        ('''
llama_model::llama_model(const llama_model_params & params) : params(params), pimpl(std::make_unique<impl>()) {
''',
         '''
// strixllama: BF16 twins of the F32 weights whose every value is a bfloat16 - the MoE routers, the shared experts' gates,
// the delta-net alpha / beta and the hyper-connection injects of Qwen3.8-Flash-Next, 0.31 GB a token as F32. A decode
// batch (at most 8 tokens) multiplies them with mul_mat_vec_f, whose bf16 loop is its f32 loop and bf16 widens to f32
// exactly: the same products at half the bytes (router [2560 -> 512] 29 -> 18 us). Prefill keeps the originals and
// their kernels. Twins carry GGML_BF16_TWIN_MAGIC so the backend keeps them on the vector kernel. STRIX_BF16_TWINS=0: none.
void llama_model::build_bf16_twins() {
    const char * e = getenv("STRIX_BF16_TWINS");
    if (e != nullptr && atoi(e) == 0) {
        return;
    }
    const int64_t t0 = ggml_time_us();
    static const char * const families[] = { "ffn_gate_inp", "ssm_alpha", "ssm_beta", "_inject" };

    std::map<ggml_backend_buffer_type_t, std::vector<std::pair<std::string, ggml_tensor *>>> groups;
    size_t n_inexact = 0;
    for (const auto & [name, t] : tensors_by_name) {
        if (t == nullptr || t->type != GGML_TYPE_F32 || t->buffer == nullptr || ggml_n_dims(t) > 2 || t->ne[0] % 2 != 0 ||
                !ggml_is_contiguous(t) || ggml_backend_buft_is_host(ggml_backend_buffer_get_type(t->buffer))) {
            continue;
        }
        bool family = false;
        for (const char * f : families) {
            family = family || name.find(f) != std::string::npos;
        }
        if (!family) {
            continue;
        }
        std::vector<uint32_t> bits(ggml_nelements(t));
        ggml_backend_tensor_get(t, bits.data(), 0, ggml_nbytes(t));
        bool exact = true;
        for (const uint32_t u : bits) {
            exact = exact && (u & 0xffffu) == 0;
        }
        if (!exact) {
            ++n_inexact;
            continue;
        }
        groups[ggml_backend_buffer_get_type(t->buffer)].emplace_back(name, t);
    }

    size_t n_twins = 0, bytes = 0;
    for (auto & [buft, list] : groups) {
        ggml_init_params ip = { ggml_tensor_overhead() * (list.size() + 1), nullptr, true };
        ggml_context * ctx = ggml_init(ip);
        if (ctx == nullptr) {
            throw std::runtime_error("failed to create bf16 twin context");
        }
        pimpl->twin_ctxs.emplace_back(ctx);
        std::vector<std::pair<ggml_tensor *, ggml_tensor *>> pairs;
        for (auto & [name, t] : list) {
            ggml_tensor * twin = ggml_new_tensor(ctx, GGML_TYPE_BF16, ggml_n_dims(t), t->ne);
            ggml_format_name(twin, "%s.bf16", name.c_str());
            ((int32_t *) twin->op_params)[0] = GGML_BF16_TWIN_MAGIC;
            pairs.emplace_back(t, twin);
        }
        ggml_backend_buffer_t buf = ggml_backend_alloc_ctx_tensors_from_buft(ctx, buft);
        if (buf == nullptr) {
            throw std::runtime_error(format("failed to allocate bf16 twin buffer on %s", ggml_backend_buft_name(buft)));
        }
        pimpl->twin_bufs.emplace_back(buf);
        bytes += ggml_backend_buffer_get_size(buf);
        for (auto & [t, twin] : pairs) {
            std::vector<uint32_t> bits(ggml_nelements(t));
            ggml_backend_tensor_get(t, bits.data(), 0, ggml_nbytes(t));
            std::vector<uint16_t> half(bits.size());
            for (size_t k = 0; k < bits.size(); ++k) {
                half[k] = (uint16_t) (bits[k] >> 16);
            }
            ggml_backend_tensor_set(twin, half.data(), 0, ggml_nbytes(twin));
            bf16_twins[t] = twin;
            ++n_twins;
        }
    }
    {
        std::lock_guard<std::mutex> lock(g_decode_twin_mutex);
        for (const auto & [t, twin] : bf16_twins) {
            g_bf16_twins[t] = twin;
        }
    }
    // stderr: the server's log keeps none of the library's load messages
    fprintf(stderr, "%s: %zu F32 weights got BF16 twins (%.2f GiB, %.1f s), %zu kept F32 (not all bfloat16); used for batches of <= 8 tokens\\n",
            __func__, n_twins, bytes / 1024.0 / 1024.0 / 1024.0, (ggml_time_us() - t0) / 1e6, n_inexact);
}

llama_model::llama_model(const llama_model_params & params) : params(params), pimpl(std::make_unique<impl>()) {
'''),
        ('''            g_decode_twins.erase(t);
        }
''',
         '''            g_decode_twins.erase(t);
        }
    }
    if (!bf16_twins.empty()) {
        std::lock_guard<std::mutex> lock(g_decode_twin_mutex);
        for (const auto & [t, twin] : bf16_twins) {
            g_bf16_twins.erase(t);
        }
'''),
        ('''    build_decode_twins();

''',
         '''    build_decode_twins();
    // strixllama: BF16 copies of the bfloat16-valued F32 weights for decode batches (STRIX_BF16_TWINS=0: none)
    build_bf16_twins();

'''),
    ],
    os.path.join(tree, "src", "llama-model.h"): [
        ('''
    // for keeping track of associated LoRA adapters
''',
         '''
    // strixllama: BF16 twins of the F32 weights whose values are all bfloat16 (build_bf16_twins), used by batches of at
    // most 8 tokens (llama_bf16_twin)
    std::unordered_map<const ggml_tensor *, ggml_tensor *> bf16_twins;
    void build_bf16_twins();

    // for keeping track of associated LoRA adapters
'''),
        ('''int64_t       llama_decode_twin_max_tokens();

''',
         '''int64_t       llama_decode_twin_max_tokens();
// strixllama: the BF16 twin of an F32 weight (null if none); used for batches of at most 8 tokens
ggml_tensor * llama_bf16_twin(const ggml_tensor * w);

'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
