#!/usr/bin/env python3
"""Images in several resident conversations; attention rows copied on the device

An image's cells repeat one position under M-RoPE, so the sparse attention ranks cells, and it ranked only while the cache held one sequence: an image in a second resident conversation asserted in set_input_qsa (group_members). Each sequence of a ubatch is now ranked among its own cells, which is also what one resident sequence gets (that path is unchanged, bitwise), so image input and several slots go together. kv_rows_copy gives the prefix cache device-to-device row copies.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 11 hunks across 2 file(s).

Usage: python patches/apply_image_rank_per_seq.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'seq_order'

EDITS = {
    os.path.join(tree, "src", "llama-memory-hybrid-idx.cpp"): [
        ('''
bool llama_memory_hybrid_idx::kv_alloc(llama_seq_id seq_id, const llama_token * tokens, uint32_t n) {
''',
         '''
bool llama_memory_hybrid_idx::kv_rows_copy(llama_seq_id seq_src, llama_seq_id seq_dst, llama_pos p0, uint32_t n) {
    if (kv_row_size() == 0) {
        return false;
    }
    return get_mem_attn()->seq_rows_copy(seq_src, seq_dst, p0, n) &&
           (!mem_idx || mem_idx->seq_rows_copy(seq_src, seq_dst, p0, n));
}

bool llama_memory_hybrid_idx::kv_alloc(llama_seq_id seq_id, const llama_token * tokens, uint32_t n) {
'''),
        ('''    std::vector<int32_t> rank;

''',
         '''    std::vector<int32_t> rank;
    // strixllama: with several sequences resident, the cells of each sequence of the ubatch, ranked among themselves
    std::map<llama_seq_id, std::vector<int32_t>> seq_order;

'''),
        ('''        if ((dup || oor) && ubatch->is_pos_2d() && one_seq) {
            order.clear();
            order.reserve(n_kv);

            for (int64_t j = 0; j < n_kv; ++j) {
                if (!cells.is_empty(j)) {
                    order.push_back((int32_t) j);
                }
            }

''',
         '''        //
        // strixllama: with several sequences resident, each sequence of the ubatch is ranked among its own cells: the
        // cells of the others are invisible to its queries and left out of its blocks, so a cell's rank is its place
        // in its own conversation, as with one sequence resident. The ranking used to need one sequence in the whole
        // cache, and an image in a second resident conversation aborted the server below (group_members): unranked,
        // the image's repeated positions put two cells in one block slot. A cell two sequences of the ubatch share has
        // two places, so such a ubatch is not ranked (seq_cp; not what the slots do).
        if ((dup || oor) && ubatch->is_pos_2d()) {
'''),
        ('''            std::sort(order.begin(), order.end(), [&cells](int32_t a, int32_t b) {
''',
         '''            auto by_pos = [&cells](int32_t a, int32_t b) {
'''),
        ('''            });

            rank.assign(n_kv, -1);
''',
         '''            };

            order.clear();
            seq_order.clear();
            bool shared = false;
'''),
        ('''            for (int64_t k = 0; k < (int64_t) order.size(); ++k) {
                rank[order[k]] = (int32_t) k;
''',
         '''            for (int64_t j = 0; j < n_kv && !shared; ++j) {
                if (cells.is_empty(j)) {
                    continue;
                }
                if (one_seq) {
                    order.push_back((int32_t) j);
                    continue;
                }
                const auto own = cells.seq_get_all(j) & active_seqs;
                if (own.count() > 1) {
                    shared = true;
                } else if (own.any()) {
                    for (int sq = 0; sq < LLAMA_MAX_SEQ; ++sq) {
                        if (own.test(sq)) {
                            seq_order[sq].push_back((int32_t) j);
                            break;
                        }
                    }
                }
'''),
        ('''            ranked = true;
''',
         '''            if (!shared) {
                rank.assign(n_kv, -1);
                if (one_seq) {
                    std::sort(order.begin(), order.end(), by_pos);
                    for (int64_t k = 0; k < (int64_t) order.size(); ++k) {
                        rank[order[k]] = (int32_t) k;
                    }
                } else {
                    for (auto & [sq, ord] : seq_order) {
                        std::sort(ord.begin(), ord.end(), by_pos);
                        for (int64_t k = 0; k < (int64_t) ord.size(); ++k) {
                            rank[ord[k]] = (int32_t) k;
                        }
                    }
                }
'''),
        ('''            group_cells();
''',
         '''                ranked = true;

                group_cells();
            }
'''),
        ('''                int64_t lo = 0;
                int64_t hi = (int64_t) order.size();
''',
         '''                // the query's place among its own sequence's cells
                const std::vector<int32_t> & ord = one_seq ? order : seq_order[seq_id];

                int64_t lo = 0;
                int64_t hi = (int64_t) ord.size();
'''),
        ('''                    const int32_t   c   = order[mid];
''',
         '''                    const int32_t   c   = ord[mid];
'''),
    ],
    os.path.join(tree, "src", "llama-memory-hybrid-idx.h"): [
        ('''    bool   kv_rows_set(llama_seq_id seq_id, llama_pos p0, uint32_t n, const uint8_t * src, uint32_t src_rows);
    // seq_id loses everything it held and gets attention and indexer cells for positions [0, n) of `tokens`
''',
         '''    bool   kv_rows_set(llama_seq_id seq_id, llama_pos p0, uint32_t n, const uint8_t * src, uint32_t src_rows);
    // strixllama: the rows of seq_src at positions [p0, p0 + n) into seq_dst's cells for them (kv_alloc), on the device
    bool   kv_rows_copy(llama_seq_id seq_src, llama_seq_id seq_dst, llama_pos p0, uint32_t n);
    // seq_id loses everything it held and gets attention and indexer cells for positions [0, n) of `tokens`
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
