#!/usr/bin/env python3
"""0.5.5: a conversation's next request keeps the tokens the model generated.

A tool call's follow-up, an agent's next step or the next chat turn sends the model's answer back as text, and the
server tokenized that text again. The chat template renders it byte for byte, but sampling can produce a tokenization
the tokenizer never gives (a word in two pieces that comes back as one), so the cached prefix stopped inside the answer
and everything after the nearest checkpoint - the answer's start - was processed again. In the request logs of 10-08/09,
3 of 7 requests that continued a conversation lost their whole previous answer this way (one of two tool-call
follow-ups, two of five chat turns): 2.8K, 5.7K and 0.7K tokens processed again, the text identical in all three.
splice_own_tokens: when the prompt's text after the common prefix starts with the text of the slot's own remaining
tokens, those tokens are kept and only the text after them is tokenized again (text only after the common prefix, an
image before it stays; a cut on a character boundary; at least 16 tokens; the message spans are found again).
Whitespace the template trims off the end of an answer is kept from the slot when the text continues with the end of
the turn. STRIX_SPLICE_OWN=0 turns it off.
A second cause, with MTP: an end of turn accepted as a draft token was followed into the cache by the tokens drafted
after it (the newline, the next turn's start); the next turn parted from the slot before the state it held, and the
whole answer was processed again. The tokens after an end of turn are now dropped like a rejected draft.
Measured on one slot: the 10-09 web-search follow-up (7,822 tokens, the answer's token split as sampling can) processed
4,228 tokens in 3.7 s against 7,822 in 6.9 s without it (the app, with its checkpoint at the answer's start, processed
6,994); a third greedy chat turn 326 -> 26 tokens processed; an answer ending with a newline 63 / 63 tokens reused.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 6 hunks across 2 file(s).

Usage: python patches/apply_own_tokens_055.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'void splice_own_tokens(server_slot & slot, server_task & task)'

EDITS = {
    os.path.join(tree, "tools", "server", "server-context.cpp"): [
        ('''
    bool launch_slot_with_task(server_slot & slot, server_task && task) {
''',
         '''
    // strixllama: a conversation's next request (a tool call's follow-up, an agent step, the next chat turn) sends the
    // model's own answer back as text. The chat template renders that text byte for byte as it was generated, but
    // tokenizing it again does not always give the tokens the model sampled (a word it produced in two pieces comes
    // back as one), so the cached prefix stopped inside the answer and everything after the nearest checkpoint - the
    // reasoning and the calls - was processed again: 7K of a 7.8K-token follow-up for two web searches, 5.7K tokens of
    // a 31K chat turn (10-08/09). When the text after the common prefix starts with the text of the slot's own
    // remaining tokens, those tokens are kept as they are and only the text after them is tokenized again; the slot
    // continues where its answer ended. The tokens the model sees are the ones it produced, which is what its cache
    // holds. Text only after the common prefix (an image before it stays); the cut falls at a token of the slot's own
    // on a character boundary; at least 16 tokens. The template also trims an answer's content, so whitespace the model ended it with is missing from the
    // text: when all the slot has left is whitespace and the text continues with the end of the turn, the slot keeps
    // it too. STRIX_SPLICE_OWN=0: off.
    void splice_own_tokens(server_slot & slot, server_task & task) {
        static const bool on = !getenv("STRIX_SPLICE_OWN") || atoi(getenv("STRIX_SPLICE_OWN")) != 0;
        if (!on || !task.params.cache_prompt || slot.prompt.tokens.empty() || task.tokens.empty()) {
            return;
        }
        const server_tokens & ct = slot.prompt.tokens; // indexed: get_tokens() refuses prompts that may hold media
        const server_tokens & pt = task.tokens;
        const size_t k = ct.get_common_prefix(pt);
        if (k == 0 || ct.size() <= k || pt.size() <= k) {
            return;
        }
        for (size_t i = k; i < pt.size(); ++i) {
            if (pt[i] == LLAMA_TOKEN_NULL) {
                return; // an image or audio chunk after the prefix
            }
        }
        for (size_t i = k; i < ct.size(); ++i) {
            if (ct[i] == LLAMA_TOKEN_NULL) {
                return;
            }
        }
        // the prompt's text after the common prefix, built only as far as it is read
        std::string text;
        size_t n_text = k;
        const auto text_to = [&](size_t n) {
            while (text.size() < n && n_text < pt.size()) {
                text += common_token_to_piece(ctx_tgt, pt[n_text++], true);
            }
            return text.size() >= n;
        };
        size_t off = 0, n_keep = 0, off_keep = 0, i = k;
        for (; i < ct.size(); ++i) {
            const std::string piece = common_token_to_piece(ctx_tgt, ct[i], true);
            if (piece.empty() || !text_to(off + piece.size()) || text.compare(off, piece.size(), piece) != 0) {
                break;
            }
            off += piece.size();
            if (text_to(off + 1) && ((unsigned char) text[off] & 0xC0) == 0x80) {
                continue; // inside a multi-byte character: not a place to cut
            }
            n_keep   = i + 1 - k;
            off_keep = off;
        }
        // the trimmed end of an answer: whitespace only left in the slot, the end of the turn next in the text
        bool ws_tail = false;
        if (i < ct.size() && k + n_keep == i && text_to(off_keep + 1)) {
            bool all_ws = true;
            for (size_t j = i; j < ct.size() && all_ws; ++j) {
                const std::string piece = common_token_to_piece(ctx_tgt, ct[j], true);
                all_ws = !piece.empty() && piece.find_first_not_of(" \\t\\r\\n") == std::string::npos;
            }
            bool turn_end = false;
            for (const llama_token eog : { llama_vocab_eot(vocab), llama_vocab_eos(vocab) }) {
                if (eog == LLAMA_TOKEN_NULL) {
                    continue;
                }
                const std::string piece = common_token_to_piece(ctx_tgt, eog, true);
                turn_end = turn_end || (!piece.empty() && text_to(off_keep + piece.size()) &&
                                        text.compare(off_keep, piece.size(), piece) == 0);
            }
            if (all_ws && turn_end) {
                n_keep  = ct.size() - k;
                ws_tail = true;
            }
        }
        if ((!ws_tail && n_keep < 16) || n_keep == 0) {
            return;
        }
        text_to(std::string::npos); // the rest of the prompt
        if (off_keep >= text.size()) {
            return;
        }
        const llama_tokens rest = common_tokenize(ctx_tgt, text.substr(off_keep), false, true);
        if ((int64_t) (k + n_keep + rest.size()) >= (int64_t) slot.n_ctx) {
            return;
        }
        const size_t n_before = pt.size();
        task.tokens.keep_first(k); // the prefix keeps its images
        for (size_t j = k; j < k + n_keep; ++j) {
            task.tokens.push_back(ct[j]);
        }
        for (const llama_token t : rest) {
            task.tokens.push_back(t);
        }
        if (task.params.message_delims) {
            task.params.message_spans = task.tokens.find_message_spans(*task.params.message_delims);
        }
        SLT_INF(slot, "own tokens kept: %zu more of its %zu (common prefix %zu%s); prompt %zu -> %zu tokens\\n",
                n_keep, ct.size(), k, ws_tail ? ", trimmed whitespace" : "", n_before, task.tokens.size());
    }

    bool launch_slot_with_task(server_slot & slot, server_task && task) {
'''),
        ('''            }
        }

        if (!task.tokens.validate(ctx_tgt)) {
''',
         '''            }
        }

        splice_own_tokens(slot, task);

        if (!task.tokens.validate(ctx_tgt)) {
'''),
        ('''
                const uint32_t n_rollback = slot.spec_draft.size() + 1 - accepted.size();
''',
         '''
                // strixllama: a turn that ends at an accepted draft token (the end of turn drafted with what follows it,
                // a newline, the next turn's start) drops the tokens after it as a rejected draft. Kept, they went into
                // the slot's cache and memory, past the end of the answer, and the next request of the conversation -
                // the answer, the end of turn, the next message - parted from the slot before the state it held: the
                // whole answer was processed again from its checkpoint (326 of 810 tokens for a third chat turn)
                for (size_t i = 0; i + 1 < accepted.size(); ++i) {
                    if (llama_vocab_is_eog(vocab, accepted[i])) {
                        accepted.resize(i + 1);
                        break;
                    }
                }

                const uint32_t n_rollback = slot.spec_draft.size() + 1 - accepted.size();
'''),
        ('''        delimiters.tokenize(ctx_server.vocab);

''',
         '''        delimiters.tokenize(ctx_server.vocab);
        const auto message_delims = std::make_shared<const common_chat_msg_delimiters>(delimiters);

'''),
        ('''            task.params.message_spans = task.tokens.find_message_spans(delimiters);
''',
         '''            task.params.message_spans  = task.tokens.find_message_spans(delimiters);
            task.params.message_delims = message_delims;
'''),
    ],
    os.path.join(tree, "tools", "server", "server-task.h"): [
        ('''    common_chat_msg_spans message_spans;

''',
         '''    common_chat_msg_spans message_spans;
    // strixllama: the delimiters they were found with, to find them again when the prompt's tokens change
    // (server_context_impl::splice_own_tokens)
    std::shared_ptr<const common_chat_msg_delimiters> message_delims;

'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
