#!/usr/bin/env python3
"""DEV: an in-run A/B for the HIP backend (STRIX_AB=<n>).

Every n decode graphs (first node < 64 rows) the side flips between A and B and every HIP graph is captured anew; switches that read ggml_cuda_strix_ab() (or ggml_backend_cuda_strix_ab through the registry) follow it, and the GPU timeline (STRIX_GPU_TIMELINE) keeps the two sides' tables apart, leaving out the two graphs after each flip. Sequential runs on this machine drift 3-5% over minutes (heat, other work); alternating inside one run puts the drift on both sides. Measurement only: nothing changes unless STRIX_AB is set.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 9 hunks across 2 file(s).

Usage: python patches/apply_ab_switch_041.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'g_strix_ab_since'

EDITS = {
    os.path.join(tree, "ggml", "src", "ggml-cuda", "ggml-cuda.cu"): [
        ('''
struct strix_tl_acc {
''',
         '''
// strixllama DEV: STRIX_AB=<n>, an in-run A/B: every n decode graphs (first node < 64 rows) the side flips between A
// and B and every HIP graph is captured anew (as a STRIX_REPEAT_FILE change does). Switches that read
// ggml_cuda_strix_ab() follow it; the GPU timeline keeps the sides apart. Drift then falls on both sides alike.
static int g_strix_ab = 0;
static int g_strix_ab_since = 0;   // decode graphs since the last flip: the first two (captured anew) are not timed
int ggml_cuda_strix_ab() {
    return g_strix_ab;
}

static void strix_ab_step(const ggml_cgraph * cgraph);

struct strix_tl_acc {
'''),
        ('''static std::map<std::pair<size_t, int64_t>, strix_tl_acc> g_strix_tl_accs;   // by graph: dispatches, first node's rows
''',
         '''static std::map<std::pair<size_t, int64_t>, strix_tl_acc> g_strix_tl_accs;   // by graph: dispatches, first node's rows (+ 1e9 on side B)
'''),
        ('''    }
    const strix_tl_capture & c = it->second;
''',
         '''    }
    if (getenv("STRIX_AB") && g_strix_ab_since < 2) {
        return;
    }
    const strix_tl_capture & c = it->second;
'''),
        ('''    strix_tl_acc & a = g_strix_tl_accs[std::make_pair(c.keys.size(), c.rows)];
''',
         '''    strix_tl_acc & a = g_strix_tl_accs[std::make_pair(c.keys.size(), c.rows + (g_strix_ab ? 1000000000LL : 0))];
'''),
        ('''    fprintf(stderr, "GPU_TIMELINE: [%lld rows] %d graphs, a graph: span %.0f us, dispatches %.0f, their sum %.0f us, timestamp cost %.2f us each\\n",
            (long long) c.rows, a.graphs, a.span_us / g, (double) c.keys.size(), a.sum_us / g, a.overhead_us / g);
''',
         '''    fprintf(stderr, "GPU_TIMELINE: [%lld rows%s] %d graphs, a graph: span %.0f us, dispatches %.0f, their sum %.0f us, timestamp cost %.2f us each\\n",
            (long long) c.rows, getenv("STRIX_AB") ? (g_strix_ab ? ", B" : ", A") : "", a.graphs, a.span_us / g,
            (double) c.keys.size(), a.sum_us / g, a.overhead_us / g);
'''),
        ('''
// graph timing / mark-lifetime instrumentation (LLAMA_GRAPH_TIMING=1)
''',
         '''
static void strix_ab_step(const ggml_cgraph * cgraph) {
    static const int every = getenv("STRIX_AB") ? atoi(getenv("STRIX_AB")) : 0;
    if (every <= 0 || cgraph->n_nodes < 64 || ggml_nrows(cgraph->nodes[0]) >= 64) {
        return;
    }
    static int computes = 0;
    if (++computes % every == 0) {
        g_strix_ab ^= 1;
        ++g_strix_rep_gen;      // every graph captured anew
        g_strix_ab_since = 0;
    } else {
        ++g_strix_ab_since;
    }
}

// graph timing / mark-lifetime instrumentation (LLAMA_GRAPH_TIMING=1)
'''),
        ('''    strix_repeat_file_reload();
    if (strix_tl_every() > 0 && !g_strix_tl_buf) {
''',
         '''    strix_repeat_file_reload();
    strix_ab_step(cgraph);
    if (strix_tl_every() > 0 && !g_strix_tl_buf) {
'''),
        ('''    }
    return nullptr;
''',
         '''    }
    // strixllama DEV: the side of the in-run A/B (STRIX_AB), for switches outside the backend
    if (strcmp(name, "ggml_backend_cuda_strix_ab") == 0) {
        return (void *)ggml_cuda_strix_ab;
    }
    return nullptr;
'''),
    ],
    os.path.join(tree, "ggml", "src", "ggml-cuda", "common.cuh"): [
        ('''
struct ggml_cuda_pool {
''',
         '''
// strixllama DEV: the side (0 = A, 1 = B) of the in-run A/B (STRIX_AB, ggml-cuda.cu)
int ggml_cuda_strix_ab();

struct ggml_cuda_pool {
'''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
