#!/usr/bin/env python3
"""0.5.3: tool parameters in any JSON Schema form, allOf requiring what its parts require.

The per-parameter tool grammars (Qwen3-Coder via foreach_parameter, DeepSeek, Kimi K3, MiniCPM5, MiniMax M3, Muse
Glimmer, the auto parser) read a tool's top-level properties only. A top-level $ref, parameters split over allOf parts or
oneOf alternatives given as $refs left the tool with no parameter and every call arrived as {}.
common_tool_parameters_flatten (json-schema-to-grammar) spells the properties and required list out for all of them;
a plain schema comes back unchanged and what the model is shown is not affected.
json-schema-to-grammar merged allOf of objects requiring every property of a required part (Rulith's ApplyBatch atoms:
allOf [$ref atom, {not: {required: [naf]}}] forced negated and naf into every call); parts now require what they list,
{not: {required}} parts leave those properties out, nested allOf and oneOf parts contribute their properties.
resolves_to_string: allOf of a string $ref and a constraint is a string. Probed: five schema shapes 1/5 -> 5/5 as
asked, Deep Rulith's OpenCase / QueryBoard / ApplyBatch arrive complete.

Generated by tools/make_patch_script.py from the tree it must reproduce, so every anchor is
unique by construction. 26 hunks across 9 file(s).

Usage: python patches/apply_tool_schemas_053.py [tree]
"""
import io
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tree = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "src", "llama.cpp")
MARKER = 'common_tool_parameters_flatten'

EDITS = {
    os.path.join(tree, "common", "chat-auto-parser-generator.cpp"): [
        ('''        auto                  params     = func.contains("parameters") ? func.at("parameters") : json::object();
''',
         '''        auto                  params     = common_tool_parameters_flatten(func.contains("parameters") ? func.at("parameters") : json::object());
'''),
    ],
    os.path.join(tree, "common", "json-schema-to-grammar.cpp"): [
        ('''#include <map>
#include <regex>
''',
         '''#include <map>
#include <set>
#include <regex>
'''),
        ('''            const std::string& hybrid_name = name;
            std::function<void(const json &, bool)> add_component = [&](const json & comp_schema, bool is_required) {
''',
         '''            const std::string& hybrid_name = name;
            // strixllama: a component's properties are required as its own "required" list says, not all of them -
            // Rulith's ApplyBatch head atoms (allOf: [$ref atom, {not: {required: [naf]}}], the atom requiring only
            // predicate) had predicate, args, negated and naf all forced, so every call carried "negated":false,"naf":false
            // and was rejected. A {not: {required: [...]}} component forbids those properties: they are left out.
            std::unordered_set<std::string> forbidden;
            std::function<void(const json &, bool)> add_component = [&](const json & comp_schema, bool is_required) {
'''),
        ('''                        properties.emplace_back(prop.key(), prop.value());
                        if (is_required) {
                            required.insert(prop.key());
''',
         '''                        bool seen = false;
                        for (const auto & p : properties) {
                            seen = seen || p.first == prop.key();
                        }
                        if (!seen) {
                            properties.emplace_back(prop.key(), prop.value());
                        }
                    }
                    if (is_required && comp_schema.contains("required") && comp_schema["required"].is_array()) {
                        for (const auto & r : comp_schema["required"]) {
                            if (r.is_string()) {
                                required.insert(r.get<std::string>());
                            }
                        }
                    }
                } else if (comp_schema.contains("not") && comp_schema["not"].is_object() && comp_schema["not"].size() == 1 &&
                           comp_schema["not"].contains("required") && comp_schema["not"]["required"].is_array()) {
                    for (const auto & r : comp_schema["not"]["required"]) {
                        if (r.is_string()) {
                            forbidden.insert(r.get<std::string>());
'''),
        ('''            for (const auto & t : schema["allOf"]) {
                if (t.contains("anyOf")) {
                    for (const auto & tt : t["anyOf"]) {
''',
         '''            // strixllama: oneOf parts count as anyOf ones (optional properties) and a nested allOf contributes its parts
            // - both had their properties dropped, so the value lost those fields
            std::function<void(const json &, int)> add_part = [&](const json & t, int depth) {
                const json & r = t.contains("$ref") && t["$ref"].is_string() && _refs.count(t["$ref"].get<std::string>()) ?
                                 _refs[t["$ref"].get<std::string>()] : t;
                if (depth < 8 && r.contains("allOf") && r["allOf"].is_array() && !r.contains("properties")) {
                    for (const auto & tt : r["allOf"]) {
                        add_part(tt, depth + 1);
                    }
                } else if (t.contains("anyOf") || t.contains("oneOf")) {
                    for (const auto & tt : t.contains("anyOf") ? t["anyOf"] : t["oneOf"]) {
'''),
        ('''                    add_component(t, true);
                }
            }
            if (!enum_values.empty()) {
''',
         '''                    add_component(t, true);
                }
            };
            for (const auto & t : schema["allOf"]) {
                add_part(t, 0);
            }
            if (!enum_values.empty()) {
'''),
        ('''                    return _add_rule(rule_name, "(" + string_join(enum_intersection, " | ") + ")");
                }
''',
         '''                    return _add_rule(rule_name, "(" + string_join(enum_intersection, " | ") + ")");
                }
            }
            if (!forbidden.empty()) {
                std::vector<std::pair<std::string, json>> kept;
                for (const auto & p : properties) {
                    if (forbidden.find(p.first) == forbidden.end()) {
                        kept.push_back(p);
                    }
                }
                properties = std::move(kept);
                for (const auto & f : forbidden) {
                    required.erase(f);
                }
'''),
        ('''
void common_schema_info::resolve_refs(common_json & schema) {
''',
         '''
common_json common_tool_parameters_flatten(const common_json & params) {
    if (!params.is_object()) {
        return params;
    }
    const bool combined = params.contains("$ref") || params.contains("allOf") || params.contains("oneOf") ||
                          params.contains("anyOf") || params.contains("not");
    if (!combined) {
        return params;
    }
    // local references only: #/$defs/NAME and #/definitions/NAME of this schema
    auto resolve = [&](const json & s0) -> json {
        json s = s0;
        for (int depth = 0; depth < 16 && s.is_object() && s.contains("$ref") && s.at("$ref").is_string(); ++depth) {
            const std::string ref = s.at("$ref").get<std::string>();
            json next;
            bool found = false;
            for (const char * key : {"$defs", "definitions"}) {
                const std::string prefix = std::string("#/") + key + "/";
                if (ref.rfind(prefix, 0) == 0 && params.contains(key) && params.at(key).is_object()) {
                    const std::string name = ref.substr(prefix.size());
                    if (params.at(key).contains(name)) {
                        next  = params.at(key).at(name);
                        found = true;
                    }
                }
            }
            if (!found) {
                break;
            }
            s = next;
        }
        return s;
    };
    std::vector<std::string>              order;
    std::map<std::string, json>           props;
    std::set<std::string>                 required;
    std::set<std::string>                 forbidden;
    std::function<void(const json &, bool, int)> collect = [&](const json & s0, bool is_required, int depth) {
        if (depth > 16) {
            return;
        }
        const json s = resolve(s0);
        if (!s.is_object()) {
            return;
        }
        if (s.contains("properties") && s.at("properties").is_object()) {
            for (const auto & [k, v] : s.at("properties").items()) {
                if (props.find(k) == props.end()) {
                    order.push_back(k);
                    props[k] = v;
                }
            }
        }
        if (is_required && s.contains("required") && s.at("required").is_array()) {
            for (const auto & r : s.at("required")) {
                if (r.is_string()) {
                    required.insert(r.get<std::string>());
                }
            }
        }
        if (s.contains("not") && s.at("not").is_object() && s.at("not").contains("required") &&
                s.at("not").at("required").is_array()) {
            for (const auto & r : s.at("not").at("required")) {
                if (r.is_string()) {
                    forbidden.insert(r.get<std::string>());
                }
            }
        }
        if (s.contains("allOf") && s.at("allOf").is_array()) {
            for (const auto & part : s.at("allOf")) {
                collect(part, is_required, depth + 1);
            }
        }
        for (const char * key : {"oneOf", "anyOf"}) {
            if (!s.contains(key) || !s.at(key).is_array()) {
                continue;
            }
            size_t n_alt = 0;
            std::map<std::string, size_t> n_req;
            for (const auto & alt0 : s.at(key)) {
                const json alt = resolve(alt0);
                if (!alt.is_object()) {
                    continue;
                }
                ++n_alt;
                collect(alt, false, depth + 1);
                if (alt.contains("required") && alt.at("required").is_array()) {
                    for (const auto & r : alt.at("required")) {
                        if (r.is_string()) {
                            n_req[r.get<std::string>()]++;
                        }
                    }
                }
            }
            if (is_required) {
                for (const auto & [k, n] : n_req) {
                    if (n_alt > 0 && n == n_alt) {
                        required.insert(k);
                    }
                }
            }
        }
    };
    collect(params, true, 0);
    if (order.empty()) {
        return params;
    }
    json out   = params;
    json p     = json::object();
    json r     = json::array();
    for (const auto & k : order) {
        if (forbidden.find(k) != forbidden.end()) {
            continue;
        }
        p[k] = props[k];
        if (required.find(k) != required.end()) {
            r.push_back(k);
        }
    }
    out["properties"] = p;
    out["required"]   = r;
    return out;
}

void common_schema_info::resolve_refs(common_json & schema) {
'''),
        ('''        // Check allOf - all components must be compatible with string type
''',
         '''        // Check allOf - a string when a part says so and no part names another type (strixllama: a part that only
        // constrains, {minLength: 1} next to a string $ref, made the value JSON and the model had to quote it)
'''),
        ('''            bool all_string = true;
''',
         '''            bool any_string = false;
            bool other_type = false;
'''),
        ('''                if (!check(component)) {
                    all_string = false;
                    break;
''',
         '''                if (check(component)) {
                    any_string = true;
                } else if (component.is_object() && component.contains("type") &&
                           !(component["type"].is_string() && component["type"] == "string")) {
                    other_type = true;
'''),
        ('''            if (all_string) {
''',
         '''            if (any_string && !other_type) {
'''),
    ],
    os.path.join(tree, "common", "json-schema-to-grammar.h"): [
        ('''class common_schema_converter;

''',
         '''class common_schema_converter;

// strixllama: a tool's parameters schema with its properties and required list spelled out at the top level, however
// the schema states them: a top-level $ref (to #/$defs or #/definitions), allOf parts (each requiring what it requires),
// oneOf / anyOf alternatives (offered together, required only where every alternative requires them) and
// {not: {required: [...]}} (those left out). A schema that already lists its properties plainly comes back unchanged.
// For the formats that build one grammar rule per parameter; what the model is shown is not affected.
common_json common_tool_parameters_flatten(const common_json & params);

'''),
    ],
    os.path.join(tree, "common", "parsers", "deepseek.cpp"): [
        ('''#include "parsers.h"
''',
         '''#include "json-schema-to-grammar.h"
#include "parsers.h"
'''),
        ('''                auto         params   = function.contains("parameters") ? function.at("parameters") : json::object();
''',
         '''                auto         params   = common_tool_parameters_flatten(function.contains("parameters") ? function.at("parameters") : json::object());
'''),
    ],
    os.path.join(tree, "common", "parsers", "kimi-k3.cpp"): [
        ('''#include "parsers.h"
''',
         '''#include "json-schema-to-grammar.h"
#include "parsers.h"
'''),
        ('''            const json   schema   = function.contains("parameters") ? function.at("parameters") : json::object();
''',
         '''            const json   schema   = common_tool_parameters_flatten(function.contains("parameters") ? function.at("parameters") : json::object());
'''),
    ],
    os.path.join(tree, "common", "parsers", "minicpm5.cpp"): [
        ('''#include "parsers.h"
''',
         '''#include "json-schema-to-grammar.h"
#include "parsers.h"
'''),
        ('''                auto              params   = function.contains("parameters") ? function.at("parameters") : json::object();
''',
         '''                auto              params   = common_tool_parameters_flatten(function.contains("parameters") ? function.at("parameters") : json::object());
'''),
    ],
    os.path.join(tree, "common", "parsers", "minimax-m3.cpp"): [
        ('''#include "parsers.h"
''',
         '''#include "json-schema-to-grammar.h"
#include "parsers.h"
'''),
        ('''            auto         params   = function.contains("parameters") ? function.at("parameters") : json::object();
''',
         '''            auto         params   = common_tool_parameters_flatten(function.contains("parameters") ? function.at("parameters") : json::object());
'''),
    ],
    os.path.join(tree, "common", "parsers", "muse-glimmer.cpp"): [
        ('''#include "parsers.h"
''',
         '''#include "json-schema-to-grammar.h"
#include "parsers.h"
'''),
        ('''                auto              params   = function.contains("parameters") ? function.at("parameters") : json::object();
''',
         '''                auto              params   = common_tool_parameters_flatten(function.contains("parameters") ? function.at("parameters") : json::object());
'''),
    ],
    os.path.join(tree, "common", "parsers", "parsers.cpp"): [
        ('''#include "parsers.h"

''',
         '''#include "parsers.h"
#include "json-schema-to-grammar.h"

'''),
        ('''    const auto & params = function.at("parameters");
''',
         '''    // strixllama: the parameters as one flat list whatever form the schema takes (common_tool_parameters_flatten): a
    // top-level oneOf, allOf or $ref had no parameter here, so the grammar allowed an empty call and nothing else
    const json params = common_tool_parameters_flatten(function.at("parameters"));
'''),
        ('''        // strixllama: parameters given only as oneOf / anyOf alternatives of objects (Rulith's OpenCase: caseType with
        // businessKey, or caseId) had no parameter at all here, so the tool-call grammar allowed an empty call and
        // nothing else - every call arrived as {}. Every alternative's properties are offered, each required only where
        // all alternatives require it; which combination is valid stays the tool's to check
        const char * key = params.contains("oneOf") ? "oneOf" : params.contains("anyOf") ? "anyOf" : nullptr;
        if (!key || !params.at(key).is_array()) {
            return;
        }
        std::vector<std::string>        order;
        std::map<std::string, json>     props;
        std::map<std::string, size_t>   n_required;
        size_t n_alt = 0;
        for (const auto & alt : params.at(key)) {
            if (!alt.is_object() || !alt.contains("properties") || !alt.at("properties").is_object()) {
                continue;
            }
            ++n_alt;
            for (const auto & [name, prop] : alt.at("properties").items()) {
                if (props.find(name) == props.end()) {
                    order.push_back(name);
                    props[name] = prop;
                }
            }
            if (alt.contains("required") && alt.at("required").is_array()) {
                for (const auto & r : alt.at("required")) {
                    if (r.is_string()) {
                        n_required[r.get<std::string>()]++;
                    }
                }
            }
        }
        for (const auto & name : order) {
            fn(name, props[name], n_alt > 0 && n_required[name] == n_alt);
        }
''',
         ''''''),
    ],
}


def main():
    texts = {p: io.open(p, encoding="utf-8").read() for p in EDITS}
    if any(MARKER in t for t in texts.values()):
        print("already applied")
        return
    for p, pairs in EDITS.items():
        for old, new in pairs:
            if texts[p].count(old) != 1:
                sys.exit("anchor found %d times, expected once, in %s" % (texts[p].count(old), p))
            texts[p] = texts[p].replace(old, new, 1)
    for p, t in texts.items():
        io.open(p, "w", encoding="utf-8", newline="").write(t)
    print("patched", ", ".join(os.path.basename(p) for p in EDITS))


if __name__ == "__main__":
    main()
